-- MEIS tenant: backfill COMMENT ON for objects created before V1 carried metadata comments
-- Safe to re-run: COMMENT ON overwrites existing descriptions

COMMENT ON TABLE campus IS '院区表';
COMMENT ON COLUMN campus.id IS '主键';
COMMENT ON COLUMN campus.campus_code IS '院区编码';
COMMENT ON COLUMN campus.campus_name IS '院区名称';
COMMENT ON COLUMN campus.address IS '地址';
COMMENT ON COLUMN campus.contact_phone IS '联系电话';
COMMENT ON COLUMN campus.is_active IS '是否启用';
COMMENT ON COLUMN campus.created_at IS '创建时间';
COMMENT ON COLUMN campus.updated_at IS '更新时间';
COMMENT ON TABLE building IS '建筑物表';
COMMENT ON COLUMN building.id IS '主键';
COMMENT ON COLUMN building.campus_id IS '所属院区';
COMMENT ON COLUMN building.building_code IS '建筑物编码';
COMMENT ON COLUMN building.building_name IS '建筑物名称';
COMMENT ON COLUMN building.floor_count IS '楼层数';
COMMENT ON COLUMN building.is_active IS '是否启用';
COMMENT ON COLUMN building.created_at IS '创建时间';
COMMENT ON COLUMN building.updated_at IS '更新时间';
COMMENT ON TABLE department IS '科室表';
COMMENT ON COLUMN department.id IS '主键';
COMMENT ON COLUMN department.dept_code IS '科室编码';
COMMENT ON COLUMN department.dept_name IS '科室名称';
COMMENT ON COLUMN department.parent_id IS '关联上级';
COMMENT ON COLUMN department.campus_id IS '所属院区';
COMMENT ON COLUMN department.building_id IS '所属建筑物';
COMMENT ON COLUMN department.floor_number IS '所在楼层';
COMMENT ON COLUMN department.room_number IS '房间号';
COMMENT ON COLUMN department.manager_id IS '关联负责人';
COMMENT ON COLUMN department.contact_phone IS '联系电话';
COMMENT ON COLUMN department.is_clinical IS '是否临床科室';
COMMENT ON COLUMN department.sort_order IS '排序号';
COMMENT ON COLUMN department.is_active IS '是否启用';
COMMENT ON COLUMN department.created_at IS '创建时间';
COMMENT ON COLUMN department.updated_at IS '更新时间';
COMMENT ON COLUMN department.pinyin_code IS '拼音简码（检索）';
COMMENT ON TABLE sys_user IS '用户表';
COMMENT ON COLUMN sys_user.id IS '主键';
COMMENT ON COLUMN sys_user.username IS '登录用户名';
COMMENT ON COLUMN sys_user.password_hash IS '密码哈希';
COMMENT ON COLUMN sys_user.real_name IS '真实姓名';
COMMENT ON COLUMN sys_user.employee_no IS '工号';
COMMENT ON COLUMN sys_user.phone IS '手机号';
COMMENT ON COLUMN sys_user.email IS '电子邮箱';
COMMENT ON COLUMN sys_user.dept_id IS '所属科室';
COMMENT ON COLUMN sys_user.role_ids IS '角色ID列表';
COMMENT ON COLUMN sys_user.avatar_url IS '头像地址';
COMMENT ON COLUMN sys_user.last_login_at IS '最后登录时间';
COMMENT ON COLUMN sys_user.last_login_ip IS '最后登录IP';
COMMENT ON COLUMN sys_user.is_locked IS '是否锁定';
COMMENT ON COLUMN sys_user.is_active IS '是否启用';
COMMENT ON COLUMN sys_user.created_at IS '创建时间';
COMMENT ON COLUMN sys_user.updated_at IS '更新时间';
COMMENT ON COLUMN sys_user.permissions IS '权限JSON';
COMMENT ON COLUMN sys_user.permission_mode IS '权限模式（synced/custom）';
COMMENT ON TABLE sys_role IS '角色表';
COMMENT ON COLUMN sys_role.id IS '主键';
COMMENT ON COLUMN sys_role.role_code IS '角色编码';
COMMENT ON COLUMN sys_role.role_name IS '角色名称';
COMMENT ON COLUMN sys_role.description IS '描述';
COMMENT ON COLUMN sys_role.permissions IS '权限JSON';
COMMENT ON COLUMN sys_role.sort_order IS '排序号';
COMMENT ON COLUMN sys_role.is_active IS '是否启用';
COMMENT ON COLUMN sys_role.created_at IS '创建时间';
COMMENT ON COLUMN sys_role.updated_at IS '更新时间';
COMMENT ON TABLE sys_operation_log IS '操作日志表';
COMMENT ON COLUMN sys_operation_log.id IS '主键';
COMMENT ON COLUMN sys_operation_log.user_id IS '关联用户';
COMMENT ON COLUMN sys_operation_log.operation_type IS '操作类型';
COMMENT ON COLUMN sys_operation_log.module_name IS '模块名称';
COMMENT ON COLUMN sys_operation_log.operation_desc IS '操作说明';
COMMENT ON COLUMN sys_operation_log.request_method IS 'HTTP方法';
COMMENT ON COLUMN sys_operation_log.request_url IS '请求URL';
COMMENT ON COLUMN sys_operation_log.request_params IS '请求参数JSON';
COMMENT ON COLUMN sys_operation_log.response_result IS '响应结果JSON';
COMMENT ON COLUMN sys_operation_log.ip_address IS '客户端IP';
COMMENT ON COLUMN sys_operation_log.user_agent IS '浏览器UA';
COMMENT ON COLUMN sys_operation_log.execution_time IS '执行耗时(ms)';
COMMENT ON COLUMN sys_operation_log.status IS '状态';
COMMENT ON COLUMN sys_operation_log.error_msg IS '错误信息';
COMMENT ON COLUMN sys_operation_log.created_at IS '创建时间';
COMMENT ON TABLE medical_device_category IS '医疗器械分类目录';
COMMENT ON COLUMN medical_device_category.id IS '主键';
COMMENT ON COLUMN medical_device_category.category_code IS '分类编码';
COMMENT ON COLUMN medical_device_category.category_name IS '分类名称';
COMMENT ON COLUMN medical_device_category.parent_code IS '上级分类编码';
COMMENT ON COLUMN medical_device_category.level IS '层级';
COMMENT ON COLUMN medical_device_category.full_path IS '层级完整路径';
COMMENT ON COLUMN medical_device_category.sort_order IS '排序号';
COMMENT ON COLUMN medical_device_category.is_active IS '是否启用';
COMMENT ON COLUMN medical_device_category.created_at IS '创建时间';
COMMENT ON COLUMN medical_device_category.updated_at IS '更新时间';
COMMENT ON TABLE supplier IS '供应商表';
COMMENT ON COLUMN supplier.id IS '主键';
COMMENT ON COLUMN supplier.supplier_code IS '供应商编码';
COMMENT ON COLUMN supplier.supplier_name IS '供应商名称';
COMMENT ON COLUMN supplier.unified_social_credit_code IS 'unifiedsocialcredit编码';
COMMENT ON COLUMN supplier.legal_representative IS 'legal representative';
COMMENT ON COLUMN supplier.contact_person IS 'contact person';
COMMENT ON COLUMN supplier.contact_phone IS '联系电话';
COMMENT ON COLUMN supplier.address IS '地址';
COMMENT ON COLUMN supplier.bank_account IS 'bank account';
COMMENT ON COLUMN supplier.bank_name IS 'bank名称';
COMMENT ON COLUMN supplier.qualification_files IS 'qualification files';
COMMENT ON COLUMN supplier.rating IS 'rating';
COMMENT ON COLUMN supplier.is_authorized IS '是否authorized';
COMMENT ON COLUMN supplier.is_active IS '是否启用';
COMMENT ON COLUMN supplier.created_at IS '创建时间';
COMMENT ON COLUMN supplier.updated_at IS '更新时间';
COMMENT ON COLUMN supplier.pinyin_code IS '拼音简码（检索）';
COMMENT ON TABLE manufacturer IS '生产厂商表';
COMMENT ON COLUMN manufacturer.id IS '主键';
COMMENT ON COLUMN manufacturer.manufacturer_code IS '生产厂商编码';
COMMENT ON COLUMN manufacturer.manufacturer_name IS '生产厂商名称';
COMMENT ON COLUMN manufacturer.country IS 'country';
COMMENT ON COLUMN manufacturer.is_domestic IS '是否domestic';
COMMENT ON COLUMN manufacturer.contact_phone IS '联系电话';
COMMENT ON COLUMN manufacturer.website IS 'website';
COMMENT ON COLUMN manufacturer.is_active IS '是否启用';
COMMENT ON COLUMN manufacturer.created_at IS '创建时间';
COMMENT ON COLUMN manufacturer.updated_at IS '更新时间';
COMMENT ON COLUMN manufacturer.pinyin_code IS '拼音简码（检索）';
COMMENT ON TABLE purchase_plan IS '采购计划表';
COMMENT ON COLUMN purchase_plan.id IS '主键';
COMMENT ON COLUMN purchase_plan.plan_code IS '订阅计划编码';
COMMENT ON COLUMN purchase_plan.plan_year IS '计划年度';
COMMENT ON COLUMN purchase_plan.campus_id IS '所属院区';
COMMENT ON COLUMN purchase_plan.dept_id IS '所属科室';
COMMENT ON COLUMN purchase_plan.applicant_id IS '关联申请人';
COMMENT ON COLUMN purchase_plan.total_budget IS '总预算';
COMMENT ON COLUMN purchase_plan.justification IS '论证/申请理由';
COMMENT ON COLUMN purchase_plan.approval_status IS '审批状态';
COMMENT ON COLUMN purchase_plan.approved_by IS '审核人';
COMMENT ON COLUMN purchase_plan.approved_at IS '审核时间';
COMMENT ON COLUMN purchase_plan.remark IS '备注';
COMMENT ON COLUMN purchase_plan.is_active IS '是否启用';
COMMENT ON COLUMN purchase_plan.created_at IS '创建时间';
COMMENT ON COLUMN purchase_plan.updated_at IS '更新时间';
COMMENT ON COLUMN purchase_plan.plan_type IS '计划类型';
COMMENT ON COLUMN purchase_plan.fund_source IS '资金来源';
COMMENT ON COLUMN purchase_plan.business_chain_no IS '采购业务链编号（计划→入库追溯）';
COMMENT ON COLUMN purchase_plan.is_large_equipment IS '是否大型医用设备';
COMMENT ON COLUMN purchase_plan.large_equipment_class IS '大型设备分类';
COMMENT ON COLUMN purchase_plan.benefit_analysis_url IS '效益分析附件URL';
COMMENT ON COLUMN purchase_plan.dept_argument_url IS '科室论证附件URL';
COMMENT ON COLUMN purchase_plan.version IS '乐观锁版本号';
COMMENT ON COLUMN purchase_plan.device_name IS '设备名称';
COMMENT ON COLUMN purchase_plan.unit IS '单位';
COMMENT ON COLUMN purchase_plan.model IS '型号';
COMMENT ON COLUMN purchase_plan.fill_date IS '填报日期';
COMMENT ON COLUMN purchase_plan.existing_device_status IS '现有设备运行状态';
COMMENT ON COLUMN purchase_plan.existing_device_usage_freq IS '现有设备使用频次';
COMMENT ON COLUMN purchase_plan.reference_manufacturer IS '参考厂家';
COMMENT ON COLUMN purchase_plan.specification IS '规格型号';
COMMENT ON COLUMN purchase_plan.brand IS '品牌';
COMMENT ON COLUMN purchase_plan.quantity IS '数量';
COMMENT ON COLUMN purchase_plan.similar_device_count IS '同类设备数量';
COMMENT ON COLUMN purchase_plan.demand_level IS '需求程度';
COMMENT ON COLUMN purchase_plan.product_attribute_req IS '产品属性要求';
COMMENT ON COLUMN purchase_plan.other_condition_confirm IS '其他条件确认';
COMMENT ON COLUMN purchase_plan.unit_budget_price IS '单价(预算/元)';
COMMENT ON COLUMN purchase_plan.category_id IS '类别';
COMMENT ON COLUMN purchase_plan.demand_nature IS '需求性质';
COMMENT ON COLUMN purchase_plan.prefer_import IS '是否首选进口产品';
COMMENT ON TABLE purchase_plan_item IS '采购计划明细表';
COMMENT ON COLUMN purchase_plan_item.id IS '主键';
COMMENT ON COLUMN purchase_plan_item.plan_id IS '采购计划';
COMMENT ON COLUMN purchase_plan_item.device_name IS '设备名称';
COMMENT ON COLUMN purchase_plan_item.category_id IS '设备分类';
COMMENT ON COLUMN purchase_plan_item.quantity IS '数量';
COMMENT ON COLUMN purchase_plan_item.estimated_price IS '预估单价';
COMMENT ON COLUMN purchase_plan_item.total_price IS '合计金额';
COMMENT ON COLUMN purchase_plan_item.specification IS '规格型号';
COMMENT ON COLUMN purchase_plan_item.justification IS '论证/申请理由';
COMMENT ON COLUMN purchase_plan_item.priority IS '优先级';
COMMENT ON COLUMN purchase_plan_item.created_at IS '创建时间';
COMMENT ON COLUMN purchase_plan_item.use_dept_id IS '使用科室';
COMMENT ON COLUMN purchase_plan_item.is_imported IS '是否进口设备';
COMMENT ON COLUMN purchase_plan_item.registration_no IS '医疗器械注册证号';
COMMENT ON COLUMN purchase_plan_item.unit IS '计量单位';
COMMENT ON COLUMN purchase_plan_item.brand_intent IS '意向品牌';
COMMENT ON COLUMN purchase_plan_item.is_metrology IS '是否计量器具';
COMMENT ON COLUMN purchase_plan_item.udi_code IS 'UDI唯一器械标识';
COMMENT ON COLUMN purchase_plan_item.similar_device_count IS '同类设备数量';
COMMENT ON COLUMN purchase_plan_item.demand_level IS '需求程度';
COMMENT ON COLUMN purchase_plan_item.product_attribute_req IS '产品属性要求';
COMMENT ON COLUMN purchase_plan_item.fund_source IS '资金来源';
COMMENT ON COLUMN purchase_plan_item.demand_nature IS '需求性质';
COMMENT ON COLUMN purchase_plan_item.existing_device_status IS '现有设备运行状态';
COMMENT ON COLUMN purchase_plan_item.existing_device_usage_freq IS '现有设备使用频次';
COMMENT ON COLUMN purchase_plan_item.other_condition_confirm IS '其他条件确认';
COMMENT ON COLUMN purchase_plan_item.is_large_equipment IS '是否大型设备';
COMMENT ON COLUMN purchase_plan_item.large_equipment_class IS '大型设备分类';
COMMENT ON COLUMN purchase_plan_item.order_no IS '订单号（DD-yyyyMMdd+4位日流水）';
COMMENT ON COLUMN purchase_plan_item.bidding_no IS '招标单号（ZB-yyyyMMdd+4位日流水）';
COMMENT ON COLUMN purchase_plan_item.order_review_comment IS '订单审核意见';
COMMENT ON COLUMN purchase_plan_item.order_reviewed_at IS '订单审核时间';
COMMENT ON COLUMN purchase_plan_item.order_reviewed_by IS '订单审核人';
COMMENT ON COLUMN purchase_plan_item.order_reviewed_by_name IS '订单审核人姓名快照';
COMMENT ON COLUMN purchase_plan_item.bargain_meeting_location IS '议价会议地点';
COMMENT ON COLUMN purchase_plan_item.bargain_meeting_time IS '议价会议时间';
COMMENT ON COLUMN purchase_plan_item.bargain_participant_depts IS '议价参与部门';
COMMENT ON COLUMN purchase_plan_item.bargain_dept_opinion IS '议价设备科意见';
COMMENT ON COLUMN purchase_plan_item.bargain_meeting_content IS '议价会议内容';
COMMENT ON COLUMN purchase_plan_item.bargain_meeting_conclusion IS '议价会议结论';
COMMENT ON COLUMN purchase_plan_item.bargain_record_url IS '议价记录附件URL';
COMMENT ON COLUMN purchase_plan_item.bargain_review_result IS '议价审核结果(passed/rejected)';
COMMENT ON COLUMN purchase_plan_item.bargain_review_comment IS '议价建议';
COMMENT ON COLUMN purchase_plan_item.bargain_reviewed_at IS '议价审核时间';
COMMENT ON COLUMN purchase_plan_item.bargain_reviewed_by IS '议价审核人';
COMMENT ON COLUMN purchase_plan_item.bargain_reviewed_by_name IS '议价审核人姓名快照';
COMMENT ON COLUMN purchase_plan_item.bargain_at IS '议价保存时间';
COMMENT ON COLUMN purchase_plan_item.bargain_by IS '议价操作人';
COMMENT ON COLUMN purchase_plan_item.bargain_by_name IS '议价操作人姓名快照';
COMMENT ON COLUMN purchase_plan_item.bidding_review_result IS '招标审核结果(passed/rejected)';
COMMENT ON COLUMN purchase_plan_item.bidding_review_comment IS '招标建议';
COMMENT ON COLUMN purchase_plan_item.bidding_reviewed_at IS '招标审核时间';
COMMENT ON COLUMN purchase_plan_item.bidding_reviewed_by IS '招标审核人';
COMMENT ON COLUMN purchase_plan_item.bidding_reviewed_by_name IS '招标审核人姓名快照';
COMMENT ON TABLE purchase_plan_item_bid_supplier IS '采购计划明细招标供应商';
COMMENT ON COLUMN purchase_plan_item_bid_supplier.id IS '主键';
COMMENT ON COLUMN purchase_plan_item_bid_supplier.plan_item_id IS '计划明细';
COMMENT ON COLUMN purchase_plan_item_bid_supplier.supplier_id IS '供应商';
COMMENT ON COLUMN purchase_plan_item_bid_supplier.supplier_name IS '供应商名称快照';
COMMENT ON COLUMN purchase_plan_item_bid_supplier.contact_person IS '联系人快照';
COMMENT ON COLUMN purchase_plan_item_bid_supplier.contact_phone IS '联系电话快照';
COMMENT ON COLUMN purchase_plan_item_bid_supplier.brand IS '品牌';
COMMENT ON COLUMN purchase_plan_item_bid_supplier.specification IS '规格型号';
COMMENT ON COLUMN purchase_plan_item_bid_supplier.final_amount IS '最终金额';
COMMENT ON COLUMN purchase_plan_item_bid_supplier.warranty_period IS '质保期';
COMMENT ON COLUMN purchase_plan_item_bid_supplier.preferential_terms IS '优惠条款';
COMMENT ON COLUMN purchase_plan_item_bid_supplier.bid_doc_url IS '投标信息附件URL';
COMMENT ON COLUMN purchase_plan_item_bid_supplier.is_winner IS '是否中标';
COMMENT ON COLUMN purchase_plan_item_bid_supplier.sort_order IS '排序号';
COMMENT ON COLUMN purchase_plan_item_bid_supplier.created_at IS '创建时间';
COMMENT ON COLUMN purchase_plan_item_bid_supplier.updated_at IS '更新时间';
COMMENT ON COLUMN purchase_plan_item_bid_supplier.created_by IS '创建人';
COMMENT ON COLUMN purchase_plan_item_bid_supplier.created_by_name IS '创建人姓名快照';
COMMENT ON COLUMN purchase_plan_item_bid_supplier.updated_by IS '更新人';
COMMENT ON COLUMN purchase_plan_item_bid_supplier.updated_by_name IS '更新人姓名快照';
COMMENT ON COLUMN purchase_plan_item_bid_supplier.is_deleted IS '软删标记';
COMMENT ON COLUMN purchase_plan_item_bid_supplier.deleted_at IS '删除时间';
COMMENT ON COLUMN purchase_plan_item_bid_supplier.deleted_by IS '删除人';
COMMENT ON COLUMN purchase_plan_item_bid_supplier.deleted_by_name IS '删除人姓名快照';
COMMENT ON TABLE purchase_project IS '采购项目表';
COMMENT ON COLUMN purchase_project.id IS '主键';
COMMENT ON COLUMN purchase_project.project_code IS '项目编码';
COMMENT ON COLUMN purchase_project.project_name IS '项目名称';
COMMENT ON COLUMN purchase_project.plan_id IS '采购计划';
COMMENT ON COLUMN purchase_project.purchase_method IS 'purchase method';
COMMENT ON COLUMN purchase_project.supplier_id IS '供应商';
COMMENT ON COLUMN purchase_project.total_amount IS 'total金额';
COMMENT ON COLUMN purchase_project.bid_open_date IS 'bidopen日期';
COMMENT ON COLUMN purchase_project.award_date IS 'award日期';
COMMENT ON COLUMN purchase_project.status IS '状态';
COMMENT ON COLUMN purchase_project.created_at IS '创建时间';
COMMENT ON COLUMN purchase_project.updated_at IS '更新时间';
COMMENT ON COLUMN purchase_project.bid_sections IS '招标标段说明';
COMMENT ON COLUMN purchase_project.bid_evaluation IS '评标结果摘要';
COMMENT ON COLUMN purchase_project.argument_report_url IS '论证报告URL';
COMMENT ON COLUMN purchase_project.budget_amount IS '预算金额';
COMMENT ON COLUMN purchase_project.approval_status IS '审批状态';
COMMENT ON COLUMN purchase_project.business_chain_no IS '采购业务链编号（计划→入库追溯）';
COMMENT ON COLUMN purchase_project.bid_agency IS '招标代理机构';
COMMENT ON COLUMN purchase_project.notice_date IS '招标公告日期';
COMMENT ON COLUMN purchase_project.control_price IS '招标控制价';
COMMENT ON COLUMN purchase_project.version IS '乐观锁版本号';
COMMENT ON TABLE purchase_contract IS '采购合同表';
COMMENT ON COLUMN purchase_contract.id IS '主键';
COMMENT ON COLUMN purchase_contract.contract_code IS '合同编码';
COMMENT ON TABLE purchase_contract_item IS '采购合同设备明细';
COMMENT ON COLUMN purchase_contract_item.id IS '主键';
COMMENT ON COLUMN purchase_contract_item.contract_id IS '采购合同';
COMMENT ON COLUMN purchase_contract_item.device_name IS '设备名称';
COMMENT ON COLUMN purchase_contract_item.specification IS '设备规格型号';
COMMENT ON COLUMN purchase_contract_item.brand IS '品牌';
COMMENT ON COLUMN purchase_contract_item.quantity IS '数量';
COMMENT ON COLUMN purchase_contract_item.unit_price IS '单价';
COMMENT ON COLUMN purchase_contract_item.amount IS '金额';
COMMENT ON COLUMN purchase_contract_item.manufacturer_id IS '生产厂家';
COMMENT ON COLUMN purchase_contract_item.manufacturer_name IS '生产厂家名称快照';
COMMENT ON COLUMN purchase_contract_item.sort_order IS '排序号';
COMMENT ON COLUMN purchase_contract_item.created_at IS '创建时间';
COMMENT ON COLUMN purchase_contract_item.updated_at IS '更新时间';
COMMENT ON COLUMN purchase_contract_item.created_by IS '创建人';
COMMENT ON COLUMN purchase_contract_item.created_by_name IS '创建人姓名快照';
COMMENT ON COLUMN purchase_contract_item.updated_by IS '更新人';
COMMENT ON COLUMN purchase_contract_item.updated_by_name IS '更新人姓名快照';
COMMENT ON COLUMN purchase_contract_item.is_deleted IS '软删标记';
COMMENT ON COLUMN purchase_contract_item.deleted_at IS '删除时间';
COMMENT ON COLUMN purchase_contract_item.deleted_by IS '删除人';
COMMENT ON COLUMN purchase_contract_item.deleted_by_name IS '删除人姓名快照';
COMMENT ON COLUMN purchase_contract.contract_name IS '合同名称';
COMMENT ON COLUMN purchase_contract.project_id IS '采购项目';
COMMENT ON COLUMN purchase_contract.supplier_id IS '供应商';
COMMENT ON COLUMN purchase_contract.sign_date IS 'sign日期';
COMMENT ON COLUMN purchase_contract.start_date IS '维保日期';
COMMENT ON COLUMN purchase_contract.fund_source IS '资金来源';
COMMENT ON COLUMN purchase_contract.end_date IS '结束日期';
COMMENT ON COLUMN purchase_contract.contract_amount IS 'contract金额';
COMMENT ON COLUMN purchase_contract.warranty_period IS 'warranty period';
COMMENT ON COLUMN purchase_contract.contract_file_url IS 'contractfile附件地址';
COMMENT ON COLUMN purchase_contract.payment_terms IS 'payment terms';
COMMENT ON COLUMN purchase_contract.status IS '状态';
COMMENT ON COLUMN purchase_contract.remark IS '备注';
COMMENT ON COLUMN purchase_contract.created_at IS '创建时间';
COMMENT ON COLUMN purchase_contract.updated_at IS '更新时间';
COMMENT ON COLUMN purchase_contract.approval_status IS '审批状态';
COMMENT ON COLUMN purchase_contract.acceptance_status IS '安装验收状态';
COMMENT ON COLUMN purchase_contract.invoice_summary IS '发票汇总说明';
COMMENT ON COLUMN purchase_contract.delivery_deadline IS '交货期限';
COMMENT ON COLUMN purchase_contract.acceptance_report_url IS '验收报告URL';
COMMENT ON COLUMN purchase_contract.paid_amount IS '已付金额';
COMMENT ON COLUMN purchase_contract.payment_progress IS '付款进度（%）';
COMMENT ON COLUMN purchase_contract.business_chain_no IS '采购业务链编号（计划→入库追溯）';
COMMENT ON COLUMN purchase_contract.contract_type IS '合同类型';
COMMENT ON COLUMN purchase_contract.performance_bond IS '履约保证金';
COMMENT ON COLUMN purchase_contract.registration_cert_url IS '注册证附件URL';
COMMENT ON COLUMN purchase_contract.version IS '乐观锁版本号';
COMMENT ON TABLE contract_payment IS '合同付款记录表';
COMMENT ON COLUMN contract_payment.id IS '主键';
COMMENT ON COLUMN contract_payment.contract_id IS '采购合同';
COMMENT ON COLUMN contract_payment.payment_no IS '付款编号';
COMMENT ON COLUMN contract_payment.payment_stage IS 'payment stage';
COMMENT ON COLUMN contract_payment.payment_amount IS 'payment金额';
COMMENT ON COLUMN contract_payment.payment_ratio IS '支付比例(%)';
COMMENT ON COLUMN contract_payment.payment_condition IS '付款条件';
COMMENT ON COLUMN contract_payment.payment_date IS 'payment日期';
COMMENT ON COLUMN contract_payment.invoice_no IS '发票编号';
COMMENT ON COLUMN contract_payment.invoice_url IS 'invoice附件地址';
COMMENT ON COLUMN contract_payment.payee_account IS 'payee account';
COMMENT ON COLUMN contract_payment.status IS '状态';
COMMENT ON COLUMN contract_payment.remark IS '备注';
COMMENT ON COLUMN contract_payment.created_at IS '创建时间';
COMMENT ON COLUMN contract_payment.updated_at IS '更新时间';
COMMENT ON COLUMN contract_payment.approval_status IS '审批状态';
COMMENT ON COLUMN contract_payment.finance_auditor_id IS '财务审核人';
COMMENT ON COLUMN contract_payment.finance_audit_date IS '财务审核日期';
COMMENT ON COLUMN contract_payment.invoice_type IS '发票类型';
COMMENT ON COLUMN contract_payment.tax_amount IS '税额';
COMMENT ON COLUMN contract_payment.voucher_no IS '财务凭证号';
COMMENT ON TABLE medical_device IS '设备档案主表';
COMMENT ON COLUMN medical_device.id IS '主键';
COMMENT ON COLUMN medical_device.device_code IS '设备编码';
COMMENT ON COLUMN medical_device.device_name IS '设备名称';
COMMENT ON COLUMN medical_device.pinyin_code IS '拼音简码（设备名称首拼；检索）';
COMMENT ON COLUMN medical_device.brand IS '品牌';
COMMENT ON COLUMN medical_device.model IS '型号';
COMMENT ON COLUMN medical_device.serial_number IS '出厂序列号';
COMMENT ON COLUMN medical_device.category_id IS '设备分类(68)';
COMMENT ON COLUMN medical_device.unit_id IS '计量单位（unit_dict）';
COMMENT ON COLUMN medical_device.manufacturer_id IS '生产厂商';
COMMENT ON COLUMN medical_device.supplier_id IS '供应商';
COMMENT ON COLUMN medical_device.country_of_origin IS '原产国';
COMMENT ON COLUMN medical_device.is_imported IS '是否进口设备';
COMMENT ON COLUMN medical_device.original_value IS '原值';
COMMENT ON COLUMN medical_device.net_value IS '净值';
COMMENT ON COLUMN medical_device.depreciation_years IS '折旧年限';
COMMENT ON COLUMN medical_device.monthly_depreciation IS '月折旧额';
COMMENT ON COLUMN medical_device.accumulated_depreciation IS '累计折旧';
COMMENT ON COLUMN medical_device.financial_code IS '财务编码';
COMMENT ON COLUMN medical_device.campus_id IS '所属院区';
COMMENT ON COLUMN medical_device.building_id IS '所属建筑物';
COMMENT ON COLUMN medical_device.dept_id IS '所属科室';
COMMENT ON COLUMN medical_device.location_detail IS '详细位置';
COMMENT ON COLUMN medical_device.purchase_date IS '采购日期';
COMMENT ON COLUMN medical_device.acceptance_date IS '验收日期';
COMMENT ON COLUMN medical_device.enable_date IS '启用日期';
COMMENT ON COLUMN medical_device.warranty_end_date IS '保修截止日期';
COMMENT ON COLUMN medical_device.device_status IS '设备运行状态';
COMMENT ON COLUMN medical_device.risk_level IS '风险等级';
COMMENT ON COLUMN medical_device.is_life_support IS '是否生命支持设备';
COMMENT ON COLUMN medical_device.is_emergency IS '是否应急设备';
COMMENT ON COLUMN medical_device.qr_code_url IS '二维码地址';
COMMENT ON COLUMN medical_device.label_printed IS '是否已打印标签';
COMMENT ON COLUMN medical_device.manual_files IS '说明书附件JSON';
COMMENT ON COLUMN medical_device.certificate_files IS '证书附件JSON';
COMMENT ON COLUMN medical_device.remark IS '备注';
COMMENT ON COLUMN medical_device.is_active IS '是否启用';
COMMENT ON COLUMN medical_device.created_at IS '创建时间';
COMMENT ON COLUMN medical_device.updated_at IS '更新时间';
COMMENT ON COLUMN medical_device.created_by IS '制单人';
COMMENT ON COLUMN medical_device.updated_by IS '最后修改人';
COMMENT ON COLUMN medical_device.contract_id IS '采购合同';
COMMENT ON COLUMN medical_device.extension_data IS '扩展字段JSON（未建模列）';
COMMENT ON COLUMN medical_device.specification IS '规格型号';
COMMENT ON COLUMN medical_device.registration_no IS '医疗器械注册证号';
COMMENT ON COLUMN medical_device.production_date IS '生产日期';
COMMENT ON COLUMN medical_device.service_life_years IS '设计使用年限（年）';
COMMENT ON COLUMN medical_device.calibration_period_days IS '计量检定周期（天）';
COMMENT ON COLUMN medical_device.last_calibration_date IS '上次检定日期';
COMMENT ON COLUMN medical_device.next_calibration_date IS '下次检定日期';
COMMENT ON COLUMN medical_device.service_expiry_date IS '使用年限到期日';
COMMENT ON TABLE device_accessory IS '设备附属低值品表';
COMMENT ON COLUMN device_accessory.id IS '主键';
COMMENT ON COLUMN device_accessory.device_id IS '关联设备';
COMMENT ON COLUMN device_accessory.accessory_name IS 'accessory名称';
COMMENT ON COLUMN device_accessory.accessory_code IS 'accessory编码';
COMMENT ON COLUMN device_accessory.quantity IS '数量';
COMMENT ON COLUMN device_accessory.unit_price IS 'unit price';
COMMENT ON COLUMN device_accessory.purchase_date IS '采购日期';
COMMENT ON COLUMN device_accessory.remark IS '备注';
COMMENT ON COLUMN device_accessory.created_at IS '创建时间';
COMMENT ON TABLE device_entry IS '设备入库记录表';
COMMENT ON COLUMN device_entry.id IS '主键';
COMMENT ON COLUMN device_entry.entry_no IS '入库编号';
COMMENT ON COLUMN device_entry.contract_id IS '采购合同';
COMMENT ON COLUMN device_entry.entry_date IS 'entry日期';
COMMENT ON COLUMN device_entry.entry_type IS 'entry type';
COMMENT ON COLUMN device_entry.operator_id IS '关联操作人';
COMMENT ON COLUMN device_entry.quality_check_passed IS 'quality check passed';
COMMENT ON COLUMN device_entry.quality_checker_id IS '关联qualitychecker';
COMMENT ON COLUMN device_entry.quality_check_date IS 'qualitycheck日期';
COMMENT ON COLUMN device_entry.quality_check_report_url IS 'qualitycheckreport附件地址';
COMMENT ON COLUMN device_entry.installation_completed IS 'installation completed';
COMMENT ON COLUMN device_entry.installer_id IS '关联安装人';
COMMENT ON COLUMN device_entry.installation_date IS 'installation日期';
COMMENT ON COLUMN device_entry.installation_report_url IS 'installationreport附件地址';
COMMENT ON COLUMN device_entry.status IS '状态';
COMMENT ON COLUMN device_entry.remark IS '备注';
COMMENT ON COLUMN device_entry.created_at IS '创建时间';
COMMENT ON COLUMN device_entry.updated_at IS '更新时间';
COMMENT ON COLUMN device_entry.supplier_id IS '供应商';
COMMENT ON COLUMN device_entry.acceptance_id IS '安装验收单';
COMMENT ON COLUMN device_entry.project_id IS '采购项目';
COMMENT ON COLUMN device_entry.plan_id IS '采购计划';
COMMENT ON COLUMN device_entry.trace_no IS '入库追溯编号';
COMMENT ON COLUMN device_entry.business_chain_no IS '采购业务链编号（计划→入库追溯）';
COMMENT ON TABLE device_entry_item IS '设备入库明细表';
COMMENT ON COLUMN device_entry_item.id IS '主键';
COMMENT ON COLUMN device_entry_item.entry_id IS '关联入库';
COMMENT ON COLUMN device_entry_item.device_id IS '关联设备';
COMMENT ON COLUMN device_entry_item.device_name IS '设备名称';
COMMENT ON COLUMN device_entry_item.brand IS '品牌';
COMMENT ON COLUMN device_entry_item.model IS '型号';
COMMENT ON COLUMN device_entry_item.serial_number IS '出厂序列号';
COMMENT ON COLUMN device_entry_item.quantity IS '数量';
COMMENT ON COLUMN device_entry_item.unit_price IS 'unit price';
COMMENT ON COLUMN device_entry_item.total_price IS '合计金额';
COMMENT ON COLUMN device_entry_item.is_accepted IS '是否accepted';
COMMENT ON COLUMN device_entry_item.accepted_device_id IS '关联accepteddevice';
COMMENT ON COLUMN device_entry_item.created_at IS '创建时间';
COMMENT ON TABLE asset_transfer IS '资产流转记录表';
COMMENT ON COLUMN asset_transfer.id IS '主键';
COMMENT ON COLUMN asset_transfer.transfer_no IS '流转编号';
COMMENT ON COLUMN asset_transfer.transfer_type IS 'transfer type';
COMMENT ON COLUMN asset_transfer.device_id IS '关联设备';
COMMENT ON COLUMN asset_transfer.from_dept_id IS '关联fromdept';
COMMENT ON COLUMN asset_transfer.to_dept_id IS '关联todept';
COMMENT ON COLUMN asset_transfer.from_campus_id IS '关联fromcampus';
COMMENT ON COLUMN asset_transfer.to_campus_id IS '关联tocampus';
COMMENT ON COLUMN asset_transfer.applicant_id IS '关联申请人';
COMMENT ON COLUMN asset_transfer.approver_id IS '关联审批人';
COMMENT ON COLUMN asset_transfer.approved_at IS '审核时间';
COMMENT ON COLUMN asset_transfer.transfer_date IS 'transfer日期';
COMMENT ON COLUMN asset_transfer.reason IS 'reason';
COMMENT ON COLUMN asset_transfer.status IS '状态';
COMMENT ON COLUMN asset_transfer.remark IS '备注';
COMMENT ON COLUMN asset_transfer.created_at IS '创建时间';
COMMENT ON COLUMN asset_transfer.updated_at IS '更新时间';
COMMENT ON COLUMN asset_transfer.approval_status IS '审批状态';
COMMENT ON TABLE inventory_check IS '资产盘点表';
COMMENT ON COLUMN inventory_check.id IS '主键';
COMMENT ON COLUMN inventory_check.check_no IS '盘点单号';
COMMENT ON COLUMN inventory_check.check_name IS '盘点名称';
COMMENT ON COLUMN inventory_check.check_year IS '盘点年度';
COMMENT ON COLUMN inventory_check.check_type IS '盘点类型';
COMMENT ON COLUMN inventory_check.campus_id IS '所属院区';
COMMENT ON COLUMN inventory_check.dept_id IS '所属科室';
COMMENT ON COLUMN inventory_check.start_date IS '开始日期';
COMMENT ON COLUMN inventory_check.end_date IS '结束日期';
COMMENT ON COLUMN inventory_check.actual_start_at IS '实际开始时间';
COMMENT ON COLUMN inventory_check.actual_end_at IS '实际结束时间';
COMMENT ON COLUMN inventory_check.checker_id IS '盘点人';
COMMENT ON COLUMN inventory_check.supervisor_id IS '监盘人';
COMMENT ON COLUMN inventory_check.total_count IS '应盘数量';
COMMENT ON COLUMN inventory_check.checked_count IS '已盘数量';
COMMENT ON COLUMN inventory_check.matched_count IS '盘实相符数量';
COMMENT ON COLUMN inventory_check.mismatch_count IS '盘实不符数量';
COMMENT ON COLUMN inventory_check.missing_count IS '盘亏数量';
COMMENT ON COLUMN inventory_check.status IS '状态';
COMMENT ON COLUMN inventory_check.report_url IS '报告附件URL';
COMMENT ON COLUMN inventory_check.remark IS '备注';
COMMENT ON COLUMN inventory_check.created_at IS '创建时间';
COMMENT ON COLUMN inventory_check.updated_at IS '更新时间';
COMMENT ON COLUMN inventory_check.created_by IS '制单人';
COMMENT ON COLUMN inventory_check.approved_by IS '审核人';
COMMENT ON COLUMN inventory_check.approved_at IS '审核时间';
COMMENT ON TABLE inventory_check_item IS '资产盘点明细表';
COMMENT ON COLUMN inventory_check_item.id IS '主键';
COMMENT ON COLUMN inventory_check_item.check_id IS '所属盘点单';
COMMENT ON COLUMN inventory_check_item.device_id IS '关联设备';
COMMENT ON COLUMN inventory_check_item.device_code IS '设备编码';
COMMENT ON COLUMN inventory_check_item.device_name IS '设备名称';
COMMENT ON COLUMN inventory_check_item.expected_location IS '账面位置';
COMMENT ON COLUMN inventory_check_item.actual_location IS '实际位置';
COMMENT ON COLUMN inventory_check_item.is_found IS '是否找到设备';
COMMENT ON COLUMN inventory_check_item.is_matched IS '是否盘实相符';
COMMENT ON COLUMN inventory_check_item.condition_status IS '设备状况';
COMMENT ON COLUMN inventory_check_item.check_date IS '盘点/巡检日期';
COMMENT ON COLUMN inventory_check_item.checker_id IS '盘点人';
COMMENT ON COLUMN inventory_check_item.photos IS '现场照片JSON';
COMMENT ON COLUMN inventory_check_item.remark IS '备注';
COMMENT ON COLUMN inventory_check_item.created_at IS '创建时间';
COMMENT ON TABLE device_scrap IS '设备报废表';
COMMENT ON COLUMN device_scrap.id IS '主键';
COMMENT ON COLUMN device_scrap.scrap_no IS '报废编号';
COMMENT ON COLUMN device_scrap.device_id IS '关联设备';
COMMENT ON COLUMN device_scrap.device_code IS '设备编码';
COMMENT ON COLUMN device_scrap.device_name IS '设备名称';
COMMENT ON COLUMN device_scrap.scrap_reason IS 'scrap reason';
COMMENT ON COLUMN device_scrap.scrap_type IS 'scrap type';
COMMENT ON COLUMN device_scrap.applicant_id IS '关联申请人';
COMMENT ON COLUMN device_scrap.application_date IS 'application日期';
COMMENT ON COLUMN device_scrap.evaluator_id IS '关联evaluator';
COMMENT ON COLUMN device_scrap.evaluation_result IS 'evaluation result';
COMMENT ON COLUMN device_scrap.residual_value IS 'residual value';
COMMENT ON COLUMN device_scrap.approver_id IS '关联审批人';
COMMENT ON COLUMN device_scrap.approved_at IS '审核时间';
COMMENT ON COLUMN device_scrap.scrap_date IS 'scrap日期';
COMMENT ON COLUMN device_scrap.disposal_method IS 'disposal method';
COMMENT ON COLUMN device_scrap.disposal_date IS 'disposal日期';
COMMENT ON COLUMN device_scrap.status IS '状态';
COMMENT ON COLUMN device_scrap.remark IS '备注';
COMMENT ON COLUMN device_scrap.created_at IS '创建时间';
COMMENT ON COLUMN device_scrap.updated_at IS '更新时间';
COMMENT ON COLUMN device_scrap.approval_status IS '审批状态';
COMMENT ON TABLE fault_type_dict IS '故障类型字典表';
COMMENT ON COLUMN fault_type_dict.id IS '主键';
COMMENT ON COLUMN fault_type_dict.fault_code IS 'fault编码';
COMMENT ON COLUMN fault_type_dict.fault_name IS 'fault名称';
COMMENT ON COLUMN fault_type_dict.parent_id IS '关联上级';
COMMENT ON COLUMN fault_type_dict.level IS '层级';
COMMENT ON COLUMN fault_type_dict.is_active IS '是否启用';
COMMENT ON COLUMN fault_type_dict.created_at IS '创建时间';
COMMENT ON TABLE engineer IS '工程师表';
COMMENT ON COLUMN engineer.id IS '主键';
COMMENT ON COLUMN engineer.user_id IS '关联用户';
COMMENT ON COLUMN engineer.engineer_no IS '工程师编号';
COMMENT ON COLUMN engineer.real_name IS '真实姓名';
COMMENT ON COLUMN engineer.specialty IS 'specialty';
COMMENT ON COLUMN engineer.skill_levels IS 'skill levels';
COMMENT ON COLUMN engineer.phone IS '手机号';
COMMENT ON COLUMN engineer.email IS '电子邮箱';
COMMENT ON COLUMN engineer.is_on_duty IS '是否onduty';
COMMENT ON COLUMN engineer.workload_score IS 'workload score';
COMMENT ON COLUMN engineer.created_at IS '创建时间';
COMMENT ON COLUMN engineer.updated_at IS '更新时间';
COMMENT ON TABLE repair_workorder IS '维修工单表';
COMMENT ON COLUMN repair_workorder.id IS '主键';
COMMENT ON COLUMN repair_workorder.wo_no IS '工单编号';
COMMENT ON COLUMN repair_workorder.device_id IS '关联设备';
COMMENT ON COLUMN repair_workorder.device_code IS '设备编码';
COMMENT ON COLUMN repair_workorder.device_name IS '设备名称';
COMMENT ON COLUMN repair_workorder.reporter_id IS '关联reporter';
COMMENT ON COLUMN repair_workorder.report_dept_id IS '关联reportdept';
COMMENT ON COLUMN repair_workorder.report_method IS 'report method';
COMMENT ON COLUMN repair_workorder.report_time IS '报修时间';
COMMENT ON COLUMN repair_workorder.fault_description IS 'fault description';
COMMENT ON COLUMN repair_workorder.fault_photos IS 'fault photos';
COMMENT ON COLUMN repair_workorder.urgency_level IS 'urgency level';
COMMENT ON COLUMN repair_workorder.fault_type_id IS '关联faulttype';
COMMENT ON COLUMN repair_workorder.fault_category IS 'fault category';
COMMENT ON COLUMN repair_workorder.assigned_engineer_id IS '指派工程师';
COMMENT ON COLUMN repair_workorder.assigned_at IS 'assigned时间';
COMMENT ON COLUMN repair_workorder.assigner_id IS '关联assigner';
COMMENT ON COLUMN repair_workorder.response_time IS 'response time';
COMMENT ON COLUMN repair_workorder.arrival_time IS 'arrival time';
COMMENT ON COLUMN repair_workorder.repair_type IS 'repair type';
COMMENT ON COLUMN repair_workorder.repair_start_time IS 'repair start time';
COMMENT ON COLUMN repair_workorder.repair_end_time IS 'repair end time';
COMMENT ON COLUMN repair_workorder.repair_duration_hours IS 'repair duration hours';
COMMENT ON COLUMN repair_workorder.downtime_hours IS 'downtime hours';
COMMENT ON COLUMN repair_workorder.solution_description IS 'solution description';
COMMENT ON COLUMN repair_workorder.spare_parts_used IS 'spare parts used';
COMMENT ON COLUMN repair_workorder.labor_cost IS 'labor cost';
COMMENT ON COLUMN repair_workorder.parts_cost IS 'parts cost';
COMMENT ON COLUMN repair_workorder.total_cost IS 'total cost';
COMMENT ON COLUMN repair_workorder.invoice_no IS '发票编号';
COMMENT ON COLUMN repair_workorder.invoice_url IS 'invoice附件地址';
COMMENT ON COLUMN repair_workorder.verifier_id IS '关联verifier';
COMMENT ON COLUMN repair_workorder.verify_time IS 'verify time';
COMMENT ON COLUMN repair_workorder.verify_result IS 'verify result';
COMMENT ON COLUMN repair_workorder.verify_comment IS 'verify comment';
COMMENT ON COLUMN repair_workorder.satisfaction_rating IS 'satisfaction rating';
COMMENT ON COLUMN repair_workorder.satisfaction_comment IS 'satisfaction comment';
COMMENT ON COLUMN repair_workorder.status IS '状态';
COMMENT ON COLUMN repair_workorder.remark IS '备注';
COMMENT ON COLUMN repair_workorder.created_at IS '创建时间';
COMMENT ON COLUMN repair_workorder.updated_at IS '更新时间';
COMMENT ON TABLE spare_part IS '备件库表';
COMMENT ON COLUMN spare_part.id IS '主键';
COMMENT ON COLUMN spare_part.part_code IS 'part编码';
COMMENT ON COLUMN spare_part.part_name IS 'part名称';
COMMENT ON COLUMN spare_part.category IS 'category';
COMMENT ON COLUMN spare_part.specification IS '规格型号';
COMMENT ON COLUMN spare_part.applicable_devices IS 'applicable devices';
COMMENT ON COLUMN spare_part.supplier_id IS '供应商';
COMMENT ON COLUMN spare_part.unit_price IS 'unit price';
COMMENT ON COLUMN spare_part.stock_quantity IS 'stock quantity';
COMMENT ON COLUMN spare_part.min_stock IS 'min stock';
COMMENT ON COLUMN spare_part.max_stock IS 'max stock';
COMMENT ON COLUMN spare_part.storage_location IS 'storage location';
COMMENT ON COLUMN spare_part.remark IS '备注';
COMMENT ON COLUMN spare_part.is_active IS '是否启用';
COMMENT ON COLUMN spare_part.created_at IS '创建时间';
COMMENT ON COLUMN spare_part.updated_at IS '更新时间';
COMMENT ON TABLE spare_part_usage IS '备件使用记录表';
COMMENT ON COLUMN spare_part_usage.id IS '主键';
COMMENT ON COLUMN spare_part_usage.workorder_id IS '关联workorder';
COMMENT ON COLUMN spare_part_usage.part_id IS '关联part';
COMMENT ON COLUMN spare_part_usage.quantity IS '数量';
COMMENT ON COLUMN spare_part_usage.unit_price IS 'unit price';
COMMENT ON COLUMN spare_part_usage.total_price IS '合计金额';
COMMENT ON COLUMN spare_part_usage.used_at IS 'used时间';
COMMENT ON COLUMN spare_part_usage.operator_id IS '关联操作人';
COMMENT ON TABLE maintenance_template IS '保养模板表';
COMMENT ON COLUMN maintenance_template.id IS '主键';
COMMENT ON COLUMN maintenance_template.template_name IS 'template名称';
COMMENT ON COLUMN maintenance_template.maintenance_level IS 'maintenance level';
COMMENT ON COLUMN maintenance_template.category_id IS '设备分类';
COMMENT ON COLUMN maintenance_template.items IS 'items';
COMMENT ON COLUMN maintenance_template.estimated_duration IS 'estimated duration';
COMMENT ON COLUMN maintenance_template.is_active IS '是否启用';
COMMENT ON COLUMN maintenance_template.created_at IS '创建时间';
COMMENT ON COLUMN maintenance_template.updated_at IS '更新时间';
COMMENT ON TABLE maintenance_plan IS '保养计划表';
COMMENT ON COLUMN maintenance_plan.id IS '主键';
COMMENT ON COLUMN maintenance_plan.plan_name IS '计划名称';
COMMENT ON COLUMN maintenance_plan.device_id IS '关联设备';
COMMENT ON COLUMN maintenance_plan.template_id IS '关联template';
COMMENT ON COLUMN maintenance_plan.maintenance_level IS 'maintenance level';
COMMENT ON COLUMN maintenance_plan.cycle_type IS 'cycle type';
COMMENT ON COLUMN maintenance_plan.cycle_value IS 'cycle value';
COMMENT ON COLUMN maintenance_plan.next_due_date IS '下次到期日';
COMMENT ON COLUMN maintenance_plan.reminder_days_before IS 'reminder days before';
COMMENT ON COLUMN maintenance_plan.assigned_engineer_id IS '指派工程师';
COMMENT ON COLUMN maintenance_plan.status IS '状态';
COMMENT ON COLUMN maintenance_plan.remark IS '备注';
COMMENT ON COLUMN maintenance_plan.created_at IS '创建时间';
COMMENT ON COLUMN maintenance_plan.updated_at IS '更新时间';
COMMENT ON COLUMN maintenance_plan.plan_code IS '订阅计划编码';
COMMENT ON COLUMN maintenance_plan.last_maintained_at IS '上次保养日期';
COMMENT ON COLUMN maintenance_plan.dept_id IS '所属科室';
COMMENT ON TABLE maintenance_record IS '保养执行记录表';
COMMENT ON COLUMN maintenance_record.id IS '主键';
COMMENT ON COLUMN maintenance_record.record_no IS '记录编号';
COMMENT ON COLUMN maintenance_record.plan_id IS '采购计划';
COMMENT ON COLUMN maintenance_record.device_id IS '关联设备';
COMMENT ON COLUMN maintenance_record.device_code IS '设备编码';
COMMENT ON COLUMN maintenance_record.device_name IS '设备名称';
COMMENT ON COLUMN maintenance_record.maintenance_level IS 'maintenance level';
COMMENT ON COLUMN maintenance_record.template_id IS '关联template';
COMMENT ON COLUMN maintenance_record.executor_id IS '关联执行人';
COMMENT ON COLUMN maintenance_record.execute_start_time IS '执行开始时间';
COMMENT ON COLUMN maintenance_record.execute_end_time IS 'execute end time';
COMMENT ON COLUMN maintenance_record.duration_minutes IS 'duration minutes';
COMMENT ON COLUMN maintenance_record.items_result IS 'items result';
COMMENT ON COLUMN maintenance_record.overall_result IS 'overall result';
COMMENT ON COLUMN maintenance_record.issues_found IS 'issues found';
COMMENT ON COLUMN maintenance_record.photos IS '现场照片JSON';
COMMENT ON COLUMN maintenance_record.signature_url IS 'signature附件地址';
COMMENT ON COLUMN maintenance_record.reviewer_id IS '关联reviewer';
COMMENT ON COLUMN maintenance_record.review_time IS 'review time';
COMMENT ON COLUMN maintenance_record.review_comment IS 'review comment';
COMMENT ON COLUMN maintenance_record.status IS '状态';
COMMENT ON COLUMN maintenance_record.remark IS '备注';
COMMENT ON COLUMN maintenance_record.created_at IS '创建时间';
COMMENT ON COLUMN maintenance_record.updated_at IS '更新时间';
COMMENT ON TABLE risk_assessment IS '风险评估表';
COMMENT ON COLUMN risk_assessment.id IS '主键';
COMMENT ON COLUMN risk_assessment.assessment_no IS 'assessment编号';
COMMENT ON COLUMN risk_assessment.device_id IS '关联设备';
COMMENT ON COLUMN risk_assessment.device_code IS '设备编码';
COMMENT ON COLUMN risk_assessment.device_name IS '设备名称';
COMMENT ON COLUMN risk_assessment.assessor_id IS '关联assessor';
COMMENT ON COLUMN risk_assessment.assessment_date IS 'assessment日期';
COMMENT ON COLUMN risk_assessment.risk_level IS '风险等级';
COMMENT ON COLUMN risk_assessment.risk_factors IS 'risk factors';
COMMENT ON COLUMN risk_assessment.assessment_result IS 'assessment result';
COMMENT ON COLUMN risk_assessment.recommendations IS 'recommendations';
COMMENT ON COLUMN risk_assessment.report_url IS '报告附件URL';
COMMENT ON COLUMN risk_assessment.status IS '状态';
COMMENT ON COLUMN risk_assessment.remark IS '备注';
COMMENT ON COLUMN risk_assessment.created_at IS '创建时间';
COMMENT ON COLUMN risk_assessment.updated_at IS '更新时间';
COMMENT ON TABLE adverse_event IS '不良事件表';
COMMENT ON COLUMN adverse_event.id IS '主键';
COMMENT ON COLUMN adverse_event.event_no IS 'event编号';
COMMENT ON COLUMN adverse_event.device_id IS '关联设备';
COMMENT ON COLUMN adverse_event.device_code IS '设备编码';
COMMENT ON COLUMN adverse_event.device_name IS '设备名称';
COMMENT ON COLUMN adverse_event.reporter_id IS '关联reporter';
COMMENT ON COLUMN adverse_event.report_time IS '报修时间';
COMMENT ON COLUMN adverse_event.event_type IS 'event type';
COMMENT ON COLUMN adverse_event.severity_level IS 'severity level';
COMMENT ON COLUMN adverse_event.event_description IS 'event description';
COMMENT ON COLUMN adverse_event.cause_analysis IS 'cause analysis';
COMMENT ON COLUMN adverse_event.impact_description IS 'impact description';
COMMENT ON COLUMN adverse_event.photos IS '现场照片JSON';
COMMENT ON COLUMN adverse_event.handler_id IS '关联handler';
COMMENT ON COLUMN adverse_event.handle_measures IS 'handle measures';
COMMENT ON COLUMN adverse_event.handle_time IS 'handle time';
COMMENT ON COLUMN adverse_event.reported_to_authority IS 'reported to authority';
COMMENT ON COLUMN adverse_event.report_date IS 'report日期';
COMMENT ON COLUMN adverse_event.authority_feedback IS 'authority feedback';
COMMENT ON COLUMN adverse_event.reviewer_id IS '关联reviewer';
COMMENT ON COLUMN adverse_event.review_time IS 'review time';
COMMENT ON COLUMN adverse_event.review_comment IS 'review comment';
COMMENT ON COLUMN adverse_event.status IS '状态';
COMMENT ON COLUMN adverse_event.remark IS '备注';
COMMENT ON COLUMN adverse_event.created_at IS '创建时间';
COMMENT ON COLUMN adverse_event.updated_at IS '更新时间';
COMMENT ON TABLE metrology_record IS '计量管理表';
COMMENT ON COLUMN metrology_record.id IS '主键';
COMMENT ON COLUMN metrology_record.metrology_no IS 'metrology编号';
COMMENT ON COLUMN metrology_record.device_id IS '关联设备';
COMMENT ON COLUMN metrology_record.device_code IS '设备编码';
COMMENT ON COLUMN metrology_record.device_name IS '设备名称';
COMMENT ON COLUMN metrology_record.metrology_type IS 'metrology type';
COMMENT ON COLUMN metrology_record.metrology_org IS 'metrology org';
COMMENT ON COLUMN metrology_record.scheduled_date IS 'scheduled日期';
COMMENT ON COLUMN metrology_record.actual_date IS 'actual日期';
COMMENT ON COLUMN metrology_record.next_due_date IS '下次到期日';
COMMENT ON COLUMN metrology_record.certificate_no IS 'certificate编号';
COMMENT ON COLUMN metrology_record.certificate_url IS 'certificate附件地址';
COMMENT ON COLUMN metrology_record.result IS 'result';
COMMENT ON COLUMN metrology_record.measurement_data IS 'measurement data';
COMMENT ON COLUMN metrology_record.inspector_id IS '关联巡检人';
COMMENT ON COLUMN metrology_record.cost IS 'cost';
COMMENT ON COLUMN metrology_record.status IS '状态';
COMMENT ON COLUMN metrology_record.remark IS '备注';
COMMENT ON COLUMN metrology_record.created_at IS '创建时间';
COMMENT ON COLUMN metrology_record.updated_at IS '更新时间';
COMMENT ON TABLE performance_test IS '性能检测表';
COMMENT ON COLUMN performance_test.id IS '主键';
COMMENT ON COLUMN performance_test.test_no IS 'test编号';
COMMENT ON COLUMN performance_test.device_id IS '关联设备';
COMMENT ON COLUMN performance_test.device_code IS '设备编码';
COMMENT ON COLUMN performance_test.device_name IS '设备名称';
COMMENT ON COLUMN performance_test.test_type IS 'test type';
COMMENT ON COLUMN performance_test.test_standard IS 'test standard';
COMMENT ON COLUMN performance_test.tester_id IS '关联tester';
COMMENT ON COLUMN performance_test.test_date IS 'test日期';
COMMENT ON COLUMN performance_test.test_items IS 'test items';
COMMENT ON COLUMN performance_test.overall_result IS 'overall result';
COMMENT ON COLUMN performance_test.test_report_url IS 'testreport附件地址';
COMMENT ON COLUMN performance_test.status IS '状态';
COMMENT ON COLUMN performance_test.remark IS '备注';
COMMENT ON COLUMN performance_test.created_at IS '创建时间';
COMMENT ON COLUMN performance_test.updated_at IS '更新时间';
COMMENT ON TABLE maintenance_contract IS '维保合同表';
COMMENT ON COLUMN maintenance_contract.id IS '主键';
COMMENT ON COLUMN maintenance_contract.contract_code IS '合同编码';
COMMENT ON COLUMN maintenance_contract.contract_name IS '合同名称';
COMMENT ON COLUMN maintenance_contract.supplier_id IS '供应商';
COMMENT ON COLUMN maintenance_contract.start_date IS '开始日期';
COMMENT ON COLUMN maintenance_contract.end_date IS '结束日期';
COMMENT ON COLUMN maintenance_contract.contract_amount IS 'contract金额';
COMMENT ON COLUMN maintenance_contract.coverage_type IS 'coverage type';
COMMENT ON COLUMN maintenance_contract.covered_devices IS 'covered devices';
COMMENT ON COLUMN maintenance_contract.response_time_hours IS 'response time hours';
COMMENT ON COLUMN maintenance_contract.preventive_visits_per_year IS 'preventive visits per year';
COMMENT ON COLUMN maintenance_contract.contract_file_url IS 'contractfile附件地址';
COMMENT ON COLUMN maintenance_contract.status IS '状态';
COMMENT ON COLUMN maintenance_contract.remark IS '备注';
COMMENT ON COLUMN maintenance_contract.created_at IS '创建时间';
COMMENT ON COLUMN maintenance_contract.updated_at IS '更新时间';
COMMENT ON TABLE maintenance_contract_fulfillment IS '维保履约记录表';
COMMENT ON COLUMN maintenance_contract_fulfillment.id IS '主键';
COMMENT ON COLUMN maintenance_contract_fulfillment.contract_id IS '采购合同';
COMMENT ON COLUMN maintenance_contract_fulfillment.fulfillment_type IS 'fulfillment type';
COMMENT ON COLUMN maintenance_contract_fulfillment.scheduled_date IS 'scheduled日期';
COMMENT ON COLUMN maintenance_contract_fulfillment.actual_date IS 'actual日期';
COMMENT ON COLUMN maintenance_contract_fulfillment.engineer_id IS '关联工程师';
COMMENT ON COLUMN maintenance_contract_fulfillment.service_content IS 'service content';
COMMENT ON COLUMN maintenance_contract_fulfillment.result_description IS 'result description';
COMMENT ON COLUMN maintenance_contract_fulfillment.photos IS '现场照片JSON';
COMMENT ON COLUMN maintenance_contract_fulfillment.signature_url IS 'signature附件地址';
COMMENT ON COLUMN maintenance_contract_fulfillment.evaluation_rating IS 'evaluation rating';
COMMENT ON COLUMN maintenance_contract_fulfillment.evaluation_comment IS 'evaluation comment';
COMMENT ON COLUMN maintenance_contract_fulfillment.status IS '状态';
COMMENT ON COLUMN maintenance_contract_fulfillment.remark IS '备注';
COMMENT ON COLUMN maintenance_contract_fulfillment.created_at IS '创建时间';
COMMENT ON COLUMN maintenance_contract_fulfillment.updated_at IS '更新时间';
COMMENT ON TABLE maintenance_contract_payment IS '维保付款记录表';
COMMENT ON COLUMN maintenance_contract_payment.id IS '主键';
COMMENT ON COLUMN maintenance_contract_payment.contract_id IS '采购合同';
COMMENT ON COLUMN maintenance_contract_payment.payment_no IS '付款编号';
COMMENT ON COLUMN maintenance_contract_payment.payment_stage IS 'payment stage';
COMMENT ON COLUMN maintenance_contract_payment.payment_amount IS 'payment金额';
COMMENT ON COLUMN maintenance_contract_payment.payment_date IS 'payment日期';
COMMENT ON COLUMN maintenance_contract_payment.invoice_no IS '发票编号';
COMMENT ON COLUMN maintenance_contract_payment.invoice_url IS 'invoice附件地址';
COMMENT ON COLUMN maintenance_contract_payment.status IS '状态';
COMMENT ON COLUMN maintenance_contract_payment.remark IS '备注';
COMMENT ON COLUMN maintenance_contract_payment.created_at IS '创建时间';
COMMENT ON COLUMN maintenance_contract_payment.updated_at IS '更新时间';
COMMENT ON TABLE life_support_device IS '生命支持类设备表';
COMMENT ON COLUMN life_support_device.id IS '主键';
COMMENT ON COLUMN life_support_device.device_id IS '关联设备';
COMMENT ON COLUMN life_support_device.device_code IS '设备编码';
COMMENT ON COLUMN life_support_device.device_name IS '设备名称';
COMMENT ON COLUMN life_support_device.criticality_level IS 'criticality level';
COMMENT ON COLUMN life_support_device.backup_required IS 'backup required';
COMMENT ON COLUMN life_support_device.standby_status IS 'standby status';
COMMENT ON COLUMN life_support_device.last_test_date IS 'lasttest日期';
COMMENT ON COLUMN life_support_device.next_test_date IS 'nexttest日期';
COMMENT ON COLUMN life_support_device.emergency_protocol IS 'emergency protocol';
COMMENT ON COLUMN life_support_device.responsible_person_id IS '关联responsibleperson';
COMMENT ON COLUMN life_support_device.remark IS '备注';
COMMENT ON COLUMN life_support_device.created_at IS '创建时间';
COMMENT ON COLUMN life_support_device.updated_at IS '更新时间';
COMMENT ON TABLE emergency_device_pool IS '应急设备库表';
COMMENT ON COLUMN emergency_device_pool.id IS '主键';
COMMENT ON COLUMN emergency_device_pool.pool_name IS 'pool名称';
COMMENT ON COLUMN emergency_device_pool.campus_id IS '所属院区';
COMMENT ON COLUMN emergency_device_pool.location IS 'location';
COMMENT ON COLUMN emergency_device_pool.manager_id IS '关联负责人';
COMMENT ON COLUMN emergency_device_pool.contact_phone IS '联系电话';
COMMENT ON COLUMN emergency_device_pool.devices IS 'devices';
COMMENT ON COLUMN emergency_device_pool.is_available IS '是否available';
COMMENT ON COLUMN emergency_device_pool.remark IS '备注';
COMMENT ON COLUMN emergency_device_pool.created_at IS '创建时间';
COMMENT ON COLUMN emergency_device_pool.updated_at IS '更新时间';
COMMENT ON TABLE emergency_device_allocation IS '应急设备调配记录表';
COMMENT ON COLUMN emergency_device_allocation.id IS '主键';
COMMENT ON COLUMN emergency_device_allocation.allocation_no IS 'allocation编号';
COMMENT ON COLUMN emergency_device_allocation.device_id IS '关联设备';
COMMENT ON COLUMN emergency_device_allocation.from_pool_id IS '关联frompool';
COMMENT ON COLUMN emergency_device_allocation.to_dept_id IS '关联todept';
COMMENT ON COLUMN emergency_device_allocation.applicant_id IS '关联申请人';
COMMENT ON COLUMN emergency_device_allocation.application_time IS 'application time';
COMMENT ON COLUMN emergency_device_allocation.reason IS 'reason';
COMMENT ON COLUMN emergency_device_allocation.urgency_level IS 'urgency level';
COMMENT ON COLUMN emergency_device_allocation.approved_by IS '审核人';
COMMENT ON COLUMN emergency_device_allocation.approved_at IS '审核时间';
COMMENT ON COLUMN emergency_device_allocation.allocation_time IS 'allocation time';
COMMENT ON COLUMN emergency_device_allocation.return_time IS 'return time';
COMMENT ON COLUMN emergency_device_allocation.status IS '状态';
COMMENT ON COLUMN emergency_device_allocation.remark IS '备注';
COMMENT ON COLUMN emergency_device_allocation.created_at IS '创建时间';
COMMENT ON COLUMN emergency_device_allocation.updated_at IS '更新时间';
COMMENT ON TABLE special_device IS '特种设备表（放射、辐射类等）';
COMMENT ON COLUMN special_device.id IS '主键';
COMMENT ON COLUMN special_device.device_id IS '关联设备';
COMMENT ON COLUMN special_device.device_code IS '设备编码';
COMMENT ON COLUMN special_device.device_name IS '设备名称';
COMMENT ON COLUMN special_device.special_type IS 'special type';
COMMENT ON COLUMN special_device.license_no IS 'license编号';
COMMENT ON COLUMN special_device.license_expiry_date IS 'licenseexpiry日期';
COMMENT ON COLUMN special_device.operator_cert_required IS 'operator cert required';
COMMENT ON COLUMN special_device.certified_operators IS 'certified operators';
COMMENT ON COLUMN special_device.safety_measures IS 'safety measures';
COMMENT ON COLUMN special_device.last_inspection_date IS 'lastinspection日期';
COMMENT ON COLUMN special_device.next_inspection_date IS 'nextinspection日期';
COMMENT ON COLUMN special_device.remark IS '备注';
COMMENT ON COLUMN special_device.created_at IS '创建时间';
COMMENT ON COLUMN special_device.updated_at IS '更新时间';
COMMENT ON TABLE leased_device IS '租赁设备表';
COMMENT ON COLUMN leased_device.id IS '主键';
COMMENT ON COLUMN leased_device.device_id IS '关联设备';
COMMENT ON COLUMN leased_device.device_code IS '设备编码';
COMMENT ON COLUMN leased_device.device_name IS '设备名称';
COMMENT ON COLUMN leased_device.lessor_id IS '关联lessor';
COMMENT ON COLUMN leased_device.lease_start_date IS 'leasestart日期';
COMMENT ON COLUMN leased_device.lease_end_date IS 'leaseend日期';
COMMENT ON COLUMN leased_device.monthly_rent IS 'monthly rent';
COMMENT ON COLUMN leased_device.contract_no IS '合同编号';
COMMENT ON COLUMN leased_device.contract_url IS 'contract附件地址';
COMMENT ON COLUMN leased_device.auto_renewal IS 'auto renewal';
COMMENT ON COLUMN leased_device.renewal_notice_days IS 'renewal notice days';
COMMENT ON COLUMN leased_device.status IS '状态';
COMMENT ON COLUMN leased_device.remark IS '备注';
COMMENT ON COLUMN leased_device.created_at IS '创建时间';
COMMENT ON COLUMN leased_device.updated_at IS '更新时间';
COMMENT ON TABLE device_usage_record IS '设备使用记录表（从HIS/PACS/LIS采集）';
COMMENT ON COLUMN device_usage_record.id IS '主键';
COMMENT ON COLUMN device_usage_record.device_id IS '关联设备';
COMMENT ON COLUMN device_usage_record.device_code IS '设备编码';
COMMENT ON COLUMN device_usage_record.device_name IS '设备名称';
COMMENT ON COLUMN device_usage_record.usage_date IS 'usage日期';
COMMENT ON COLUMN device_usage_record.usage_hours IS 'usage hours';
COMMENT ON COLUMN device_usage_record.patient_count IS 'patient数量';
COMMENT ON COLUMN device_usage_record.examination_count IS 'examination数量';
COMMENT ON COLUMN device_usage_record.revenue IS 'revenue';
COMMENT ON COLUMN device_usage_record.data_source IS 'data source';
COMMENT ON COLUMN device_usage_record.source_record_id IS '关联sourcerecord';
COMMENT ON COLUMN device_usage_record.created_at IS '创建时间';
COMMENT ON TABLE device_cost_record IS '设备成本记录表';
COMMENT ON COLUMN device_cost_record.id IS '主键';
COMMENT ON COLUMN device_cost_record.device_id IS '关联设备';
COMMENT ON COLUMN device_cost_record.device_code IS '设备编码';
COMMENT ON COLUMN device_cost_record.device_name IS '设备名称';
COMMENT ON COLUMN device_cost_record.cost_date IS 'cost日期';
COMMENT ON COLUMN device_cost_record.cost_type IS 'cost type';
COMMENT ON COLUMN device_cost_record.cost_amount IS 'cost金额';
COMMENT ON COLUMN device_cost_record.description IS '描述';
COMMENT ON COLUMN device_cost_record.invoice_no IS '发票编号';
COMMENT ON COLUMN device_cost_record.data_source IS 'data source';
COMMENT ON COLUMN device_cost_record.source_record_id IS '关联sourcerecord';
COMMENT ON COLUMN device_cost_record.created_at IS '创建时间';
COMMENT ON TABLE device_benefit_summary IS '设备效益分析汇总表（按月聚合）';
COMMENT ON COLUMN device_benefit_summary.id IS '主键';
COMMENT ON COLUMN device_benefit_summary.device_id IS '关联设备';
COMMENT ON COLUMN device_benefit_summary.device_code IS '设备编码';
COMMENT ON COLUMN device_benefit_summary.device_name IS '设备名称';
COMMENT ON COLUMN device_benefit_summary.summary_year IS 'summary year';
COMMENT ON COLUMN device_benefit_summary.summary_month IS 'summary month';
COMMENT ON COLUMN device_benefit_summary.total_revenue IS 'total revenue';
COMMENT ON COLUMN device_benefit_summary.total_cost IS 'total cost';
COMMENT ON COLUMN device_benefit_summary.net_profit IS 'net profit';
COMMENT ON COLUMN device_benefit_summary.profit_rate IS 'profit rate';
COMMENT ON COLUMN device_benefit_summary.usage_hours IS 'usage hours';
COMMENT ON COLUMN device_benefit_summary.patient_count IS 'patient数量';
COMMENT ON COLUMN device_benefit_summary.utilization_rate IS 'utilization rate';
COMMENT ON COLUMN device_benefit_summary.maintenance_cost IS 'maintenance cost';
COMMENT ON COLUMN device_benefit_summary.repair_cost IS 'repair cost';
COMMENT ON COLUMN device_benefit_summary.depreciation_cost IS 'depreciation cost';
COMMENT ON COLUMN device_benefit_summary.benefit_level IS 'benefit level';
COMMENT ON COLUMN device_benefit_summary.benefit_score IS 'benefit score';
COMMENT ON COLUMN device_benefit_summary.created_at IS '创建时间';
COMMENT ON COLUMN device_benefit_summary.updated_at IS '更新时间';
COMMENT ON TABLE sys_config IS '系统参数表';
COMMENT ON COLUMN sys_config.id IS '主键';
COMMENT ON COLUMN sys_config.config_key IS 'config key';
COMMENT ON COLUMN sys_config.config_value IS 'config value';
COMMENT ON COLUMN sys_config.config_type IS 'config type';
COMMENT ON COLUMN sys_config.description IS '描述';
COMMENT ON COLUMN sys_config.is_system IS '是否system';
COMMENT ON COLUMN sys_config.created_at IS '创建时间';
COMMENT ON COLUMN sys_config.updated_at IS '更新时间';
COMMENT ON TABLE sys_dict IS '数据字典表';
COMMENT ON COLUMN sys_dict.id IS '主键';
COMMENT ON COLUMN sys_dict.dict_type IS 'dict type';
COMMENT ON COLUMN sys_dict.dict_code IS 'dict编码';
COMMENT ON COLUMN sys_dict.dict_label IS 'dict label';
COMMENT ON COLUMN sys_dict.dict_value IS 'dict value';
COMMENT ON COLUMN sys_dict.sort_order IS '排序号';
COMMENT ON COLUMN sys_dict.is_active IS '是否启用';
COMMENT ON COLUMN sys_dict.remark IS '备注';
COMMENT ON COLUMN sys_dict.created_at IS '创建时间';
COMMENT ON TABLE sys_notification IS '消息通知表';
COMMENT ON COLUMN sys_notification.id IS '主键';
COMMENT ON COLUMN sys_notification.title IS '标题';
COMMENT ON COLUMN sys_notification.content IS '内容';
COMMENT ON COLUMN sys_notification.notification_type IS '通知类型';
COMMENT ON COLUMN sys_notification.target_users IS '通知目标用户列表';
COMMENT ON COLUMN sys_notification.target_roles IS 'target roles';
COMMENT ON COLUMN sys_notification.target_depts IS 'target depts';
COMMENT ON COLUMN sys_notification.priority IS '优先级';
COMMENT ON COLUMN sys_notification.is_read IS '是否已读';
COMMENT ON COLUMN sys_notification.read_at IS 'read时间';
COMMENT ON COLUMN sys_notification.related_entity_type IS 'related entity type';
COMMENT ON COLUMN sys_notification.related_entity_id IS '关联relatedentity';
COMMENT ON COLUMN sys_notification.created_at IS '创建时间';
COMMENT ON TABLE notification_message IS '设备效益分析视图';
COMMENT ON COLUMN notification_message.id IS '主键';
COMMENT ON COLUMN notification_message.title IS '标题';
COMMENT ON COLUMN notification_message.content IS '内容';
COMMENT ON COLUMN notification_message.message_type IS '消息类型';
COMMENT ON COLUMN notification_message.is_read IS '是否已读';
COMMENT ON COLUMN notification_message.created_at IS '创建时间';
COMMENT ON TABLE device_outbound IS 'device outbound';
COMMENT ON COLUMN device_outbound.id IS '主键';
COMMENT ON COLUMN device_outbound.outbound_no IS '出库编号';
COMMENT ON COLUMN device_outbound.outbound_type IS 'outbound type';
COMMENT ON COLUMN device_outbound.dept_id IS '所属科室';
COMMENT ON COLUMN device_outbound.receiver_id IS '关联领用人';
COMMENT ON COLUMN device_outbound.outbound_date IS 'outbound日期';
COMMENT ON COLUMN device_outbound.purpose IS 'purpose';
COMMENT ON COLUMN device_outbound.is_urgent IS '是否urgent';
COMMENT ON COLUMN device_outbound.doc_status IS 'doc status';
COMMENT ON COLUMN device_outbound.operator_id IS '关联操作人';
COMMENT ON COLUMN device_outbound.created_at IS '创建时间';
COMMENT ON COLUMN device_outbound.updated_at IS '更新时间';
COMMENT ON TABLE device_outbound_item IS 'device outbound item';
COMMENT ON COLUMN device_outbound_item.id IS '主键';
COMMENT ON COLUMN device_outbound_item.outbound_id IS '关联出库';
COMMENT ON COLUMN device_outbound_item.device_id IS '关联设备';
COMMENT ON COLUMN device_outbound_item.device_code IS '设备编码';
COMMENT ON COLUMN device_outbound_item.device_name IS '设备名称';
COMMENT ON COLUMN device_outbound_item.quantity IS '数量';
COMMENT ON COLUMN device_outbound_item.created_at IS '创建时间';
COMMENT ON TABLE sys_approval_flow IS 'sys approval flow';
COMMENT ON COLUMN sys_approval_flow.id IS '主键';
COMMENT ON COLUMN sys_approval_flow.flow_code IS '流程编码';
COMMENT ON COLUMN sys_approval_flow.flow_name IS '流程名称';
COMMENT ON COLUMN sys_approval_flow.business_type IS '业务类型标识';
COMMENT ON COLUMN sys_approval_flow.is_active IS '是否启用';
COMMENT ON COLUMN sys_approval_flow.created_at IS '创建时间';
COMMENT ON TABLE sys_approval_node IS 'sys approval node';
COMMENT ON COLUMN sys_approval_node.id IS '主键';
COMMENT ON COLUMN sys_approval_node.flow_id IS '关联flow';
COMMENT ON COLUMN sys_approval_node.node_order IS 'node order';
COMMENT ON COLUMN sys_approval_node.node_name IS 'node名称';
COMMENT ON COLUMN sys_approval_node.approver_role IS 'approver role';
COMMENT ON COLUMN sys_approval_node.amount_threshold IS 'amount threshold';
COMMENT ON COLUMN sys_approval_node.created_at IS '创建时间';
COMMENT ON TABLE sys_approval_instance IS 'sys approval instance';
COMMENT ON COLUMN sys_approval_instance.id IS '主键';
COMMENT ON COLUMN sys_approval_instance.flow_id IS '关联flow';
COMMENT ON COLUMN sys_approval_instance.business_type IS '业务类型标识';
COMMENT ON COLUMN sys_approval_instance.business_id IS '业务单据ID';
COMMENT ON COLUMN sys_approval_instance.business_no IS '业务单据编号';
COMMENT ON COLUMN sys_approval_instance.title IS '标题';
COMMENT ON COLUMN sys_approval_instance.applicant_id IS '关联申请人';
COMMENT ON COLUMN sys_approval_instance.status IS '状态';
COMMENT ON COLUMN sys_approval_instance.current_node_order IS 'current node order';
COMMENT ON COLUMN sys_approval_instance.created_at IS '创建时间';
COMMENT ON COLUMN sys_approval_instance.updated_at IS '更新时间';
COMMENT ON TABLE sys_approval_record IS 'sys approval record';
COMMENT ON COLUMN sys_approval_record.id IS '主键';
COMMENT ON COLUMN sys_approval_record.instance_id IS '关联instance';
COMMENT ON COLUMN sys_approval_record.node_order IS 'node order';
COMMENT ON COLUMN sys_approval_record.approver_id IS '关联审批人';
COMMENT ON COLUMN sys_approval_record.action IS 'action';
COMMENT ON COLUMN sys_approval_record.comment IS 'comment';
COMMENT ON COLUMN sys_approval_record.acted_at IS 'acted时间';
COMMENT ON TABLE inspection_plan IS '巡检计划';
COMMENT ON COLUMN inspection_plan.id IS '主键';
COMMENT ON COLUMN inspection_plan.plan_name IS '计划名称';
COMMENT ON COLUMN inspection_plan.device_id IS '关联设备';
COMMENT ON COLUMN inspection_plan.inspection_type IS 'inspection type';
COMMENT ON COLUMN inspection_plan.plan_date IS 'plan日期';
COMMENT ON COLUMN inspection_plan.status IS '状态';
COMMENT ON COLUMN inspection_plan.created_at IS '创建时间';
COMMENT ON COLUMN inspection_plan.plan_code IS '订阅计划编码';
COMMENT ON COLUMN inspection_plan.dept_id IS '所属科室';
COMMENT ON COLUMN inspection_plan.start_date IS '开始日期';
COMMENT ON COLUMN inspection_plan.end_date IS '结束日期';
COMMENT ON COLUMN inspection_plan.frequency IS '执行频率';
COMMENT ON TABLE inspection_record IS '巡检记录';
COMMENT ON COLUMN inspection_record.id IS '主键';
COMMENT ON COLUMN inspection_record.plan_id IS '采购计划';
COMMENT ON COLUMN inspection_record.device_id IS '关联设备';
COMMENT ON COLUMN inspection_record.inspector_id IS '关联巡检人';
COMMENT ON COLUMN inspection_record.inspection_date IS 'inspection日期';
COMMENT ON COLUMN inspection_record.result IS 'result';
COMMENT ON COLUMN inspection_record.remark IS '备注';
COMMENT ON COLUMN inspection_record.status IS '状态';
COMMENT ON COLUMN inspection_record.record_no IS '记录编号';
COMMENT ON COLUMN inspection_record.result_summary IS '结果摘要';
COMMENT ON COLUMN inspection_record.inspect_date IS '巡检日期';
COMMENT ON TABLE inspection_record_item IS 'inspection record item';
COMMENT ON COLUMN inspection_record_item.id IS '主键';
COMMENT ON COLUMN inspection_record_item.record_id IS '关联record';
COMMENT ON COLUMN inspection_record_item.item_name IS 'item名称';
COMMENT ON COLUMN inspection_record_item.check_result IS 'check result';
COMMENT ON COLUMN inspection_record_item.remark IS '备注';
COMMENT ON TABLE spare_part_transaction IS 'spare part transaction';
COMMENT ON COLUMN spare_part_transaction.id IS '主键';
COMMENT ON COLUMN spare_part_transaction.spare_part_id IS '关联sparepart';
COMMENT ON COLUMN spare_part_transaction.txn_type IS 'txn type';
COMMENT ON COLUMN spare_part_transaction.quantity IS '数量';
COMMENT ON COLUMN spare_part_transaction.unit_price IS 'unit price';
COMMENT ON COLUMN spare_part_transaction.workorder_id IS '关联workorder';
COMMENT ON COLUMN spare_part_transaction.operator_id IS '关联操作人';
COMMENT ON COLUMN spare_part_transaction.created_at IS '创建时间';
COMMENT ON TABLE integration_sync_task IS 'integration sync task';
COMMENT ON COLUMN integration_sync_task.id IS '主键';
COMMENT ON COLUMN integration_sync_task.system_code IS 'system编码';
COMMENT ON COLUMN integration_sync_task.task_type IS 'task type';
COMMENT ON COLUMN integration_sync_task.status IS '状态';
COMMENT ON COLUMN integration_sync_task.payload IS 'payload';
COMMENT ON COLUMN integration_sync_task.result IS 'result';
COMMENT ON COLUMN integration_sync_task.created_at IS '创建时间';
COMMENT ON COLUMN integration_sync_task.finished_at IS 'finished时间';
COMMENT ON TABLE warehouse IS 'warehouse';
COMMENT ON COLUMN warehouse.id IS '主键';
COMMENT ON COLUMN warehouse.warehouse_code IS 'warehouse编码';
COMMENT ON COLUMN warehouse.warehouse_name IS 'warehouse名称';
COMMENT ON COLUMN warehouse.campus_id IS '所属院区';
COMMENT ON COLUMN warehouse.dept_id IS '所属科室';
COMMENT ON COLUMN warehouse.address IS '地址';
COMMENT ON COLUMN warehouse.manager_id IS '关联负责人';
COMMENT ON COLUMN warehouse.is_active IS '是否启用';
COMMENT ON COLUMN warehouse.sort_order IS '排序号';
COMMENT ON COLUMN warehouse.created_at IS '创建时间';
COMMENT ON COLUMN warehouse.updated_at IS '更新时间';
COMMENT ON TABLE purchase_acceptance IS '安装验收';
COMMENT ON COLUMN purchase_acceptance.id IS '主键';
COMMENT ON COLUMN purchase_acceptance.acceptance_no IS 'acceptance编号';
COMMENT ON COLUMN purchase_acceptance.contract_id IS '采购合同';
COMMENT ON COLUMN purchase_acceptance.project_id IS '采购项目';
COMMENT ON COLUMN purchase_acceptance.supplier_id IS '供应商';
COMMENT ON COLUMN purchase_acceptance.acceptance_date IS '验收日期';
COMMENT ON COLUMN purchase_acceptance.acceptance_status IS '安装验收状态';
COMMENT ON COLUMN purchase_acceptance.quality_check_passed IS 'quality check passed';
COMMENT ON COLUMN purchase_acceptance.quality_checker_id IS '关联qualitychecker';
COMMENT ON COLUMN purchase_acceptance.quality_check_date IS 'qualitycheck日期';
COMMENT ON COLUMN purchase_acceptance.quality_check_report_url IS 'qualitycheckreport附件地址';
COMMENT ON COLUMN purchase_acceptance.installation_completed IS 'installation completed';
COMMENT ON COLUMN purchase_acceptance.installer_id IS '关联安装人';
COMMENT ON COLUMN purchase_acceptance.installation_date IS 'installation日期';
COMMENT ON COLUMN purchase_acceptance.installation_report_url IS 'installationreport附件地址';
COMMENT ON COLUMN purchase_acceptance.clinical_checker_id IS '关联clinicalchecker';
COMMENT ON COLUMN purchase_acceptance.argument_summary IS 'argument summary';
COMMENT ON COLUMN purchase_acceptance.report_url IS '报告附件URL';
COMMENT ON COLUMN purchase_acceptance.remark IS '备注';
COMMENT ON COLUMN purchase_acceptance.entry_id IS '关联入库';
COMMENT ON COLUMN purchase_acceptance.created_at IS '创建时间';
COMMENT ON COLUMN purchase_acceptance.updated_at IS '更新时间';
COMMENT ON COLUMN purchase_acceptance.approval_status IS '审批状态';
COMMENT ON COLUMN purchase_acceptance.business_chain_no IS '采购业务链编号（计划→入库追溯）';
COMMENT ON COLUMN purchase_acceptance.approved_by IS '审核人';
COMMENT ON COLUMN purchase_acceptance.approved_by_name IS '审核人姓名';
COMMENT ON COLUMN purchase_acceptance.approved_at IS '审核日期';
COMMENT ON TABLE purchase_acceptance_item IS 'purchase acceptance item';
COMMENT ON COLUMN purchase_acceptance_item.id IS '主键';
COMMENT ON COLUMN purchase_acceptance_item.acceptance_id IS '安装验收单';
COMMENT ON COLUMN purchase_acceptance_item.item_name IS 'item名称';
COMMENT ON COLUMN purchase_acceptance_item.check_standard IS 'check standard';
COMMENT ON COLUMN purchase_acceptance_item.check_result IS 'check result';
COMMENT ON COLUMN purchase_acceptance_item.is_passed IS '是否passed';
COMMENT ON COLUMN purchase_acceptance_item.checker_id IS '盘点人';
COMMENT ON COLUMN purchase_acceptance_item.remark IS '备注';
COMMENT ON COLUMN purchase_acceptance_item.sort_order IS '排序号';
COMMENT ON TABLE purchase_acceptance_member IS '安装验收参数';
COMMENT ON COLUMN purchase_acceptance_member.id IS '主键';
COMMENT ON COLUMN purchase_acceptance_member.acceptance_id IS '安装验收单';
COMMENT ON COLUMN purchase_acceptance_member.member_role IS '验收单号（参数行）';
COMMENT ON COLUMN purchase_acceptance_member.user_id IS '关联用户（兼容旧字段）';
COMMENT ON COLUMN purchase_acceptance_member.member_name IS '项目';
COMMENT ON COLUMN purchase_acceptance_member.acceptance_content IS '验收内容';
COMMENT ON COLUMN purchase_acceptance_member.acceptance_result IS '验收结果';
COMMENT ON COLUMN purchase_acceptance_member.signed_at IS 'signed时间';
COMMENT ON COLUMN purchase_acceptance_member.signature_url IS 'signature附件地址';
COMMENT ON COLUMN purchase_acceptance_member.remark IS '备注';
COMMENT ON TABLE purchase_acceptance_device IS '安装验收设备明细';
COMMENT ON COLUMN purchase_acceptance_device.id IS '主键';
COMMENT ON COLUMN purchase_acceptance_device.acceptance_id IS '安装验收单';
COMMENT ON COLUMN purchase_acceptance_device.device_name IS '设备名称';
COMMENT ON COLUMN purchase_acceptance_device.specification IS '设备规格型号';
COMMENT ON COLUMN purchase_acceptance_device.brand IS '品牌';
COMMENT ON COLUMN purchase_acceptance_device.quantity IS '数量';
COMMENT ON COLUMN purchase_acceptance_device.unit_price IS '单价';
COMMENT ON COLUMN purchase_acceptance_device.amount IS '金额';
COMMENT ON COLUMN purchase_acceptance_device.manufacturer_id IS '生产厂家';
COMMENT ON COLUMN purchase_acceptance_device.manufacturer_name IS '生产厂家名称快照';
COMMENT ON COLUMN purchase_acceptance_device.sort_order IS '排序号';
COMMENT ON COLUMN purchase_acceptance_device.created_at IS '创建时间';
COMMENT ON COLUMN purchase_acceptance_device.updated_at IS '更新时间';
COMMENT ON COLUMN purchase_acceptance_device.created_by IS '创建人';
COMMENT ON COLUMN purchase_acceptance_device.created_by_name IS '创建人姓名快照';
COMMENT ON COLUMN purchase_acceptance_device.updated_by IS '更新人';
COMMENT ON COLUMN purchase_acceptance_device.updated_by_name IS '更新人姓名快照';
COMMENT ON COLUMN purchase_acceptance_device.is_deleted IS '软删标记';
COMMENT ON COLUMN purchase_acceptance_device.deleted_at IS '删除时间';
COMMENT ON COLUMN purchase_acceptance_device.deleted_by IS '删除人';
COMMENT ON COLUMN purchase_acceptance_device.deleted_by_name IS '删除人姓名快照';
COMMENT ON TABLE purchase_bidder IS 'purchase bidder';
COMMENT ON COLUMN purchase_bidder.id IS '主键';
COMMENT ON COLUMN purchase_bidder.project_id IS '采购项目';
COMMENT ON COLUMN purchase_bidder.bidder_name IS '投标人名称';
COMMENT ON COLUMN purchase_bidder.bid_amount IS 'bid金额';
COMMENT ON COLUMN purchase_bidder.contact_person IS 'contact person';
COMMENT ON COLUMN purchase_bidder.contact_phone IS '联系电话';
COMMENT ON COLUMN purchase_bidder.is_winner IS '是否winner';
COMMENT ON COLUMN purchase_bidder.bid_doc_url IS 'biddoc附件地址';
COMMENT ON COLUMN purchase_bidder.remark IS '备注';
COMMENT ON COLUMN purchase_bidder.sort_order IS '排序号';
COMMENT ON TABLE purchase_complaint IS 'purchase complaint';
COMMENT ON COLUMN purchase_complaint.id IS '主键';
COMMENT ON COLUMN purchase_complaint.project_id IS '采购项目';
COMMENT ON COLUMN purchase_complaint.complaint_date IS 'complaint日期';
COMMENT ON COLUMN purchase_complaint.complaint_type IS 'complaint type';
COMMENT ON COLUMN purchase_complaint.complainant IS 'complainant';
COMMENT ON COLUMN purchase_complaint.content IS '内容';
COMMENT ON COLUMN purchase_complaint.resolution IS 'resolution';
COMMENT ON COLUMN purchase_complaint.resolved_at IS 'resolved时间';
COMMENT ON COLUMN purchase_complaint.status IS '状态';
COMMENT ON COLUMN purchase_complaint.attachment_url IS 'attachment附件地址';
COMMENT ON TABLE purchase_project_event IS 'purchase project event';
COMMENT ON COLUMN purchase_project_event.id IS '主键';
COMMENT ON COLUMN purchase_project_event.project_id IS '采购项目';
COMMENT ON COLUMN purchase_project_event.event_type IS 'event type';
COMMENT ON COLUMN purchase_project_event.event_date IS 'event日期';
COMMENT ON COLUMN purchase_project_event.event_title IS 'event title';
COMMENT ON COLUMN purchase_project_event.event_desc IS 'event desc';
COMMENT ON COLUMN purchase_project_event.attachment_url IS 'attachment附件地址';
COMMENT ON COLUMN purchase_project_event.created_at IS '创建时间';
COMMENT ON TABLE purchase_alert_snapshot IS 'purchase alert snapshot';
COMMENT ON COLUMN purchase_alert_snapshot.id IS '主键';
COMMENT ON COLUMN purchase_alert_snapshot.alert_key IS 'alert key';
COMMENT ON COLUMN purchase_alert_snapshot.alert_type IS 'alert type';
COMMENT ON COLUMN purchase_alert_snapshot.title IS '标题';
COMMENT ON COLUMN purchase_alert_snapshot.message IS 'message';
COMMENT ON COLUMN purchase_alert_snapshot.level IS '层级';
COMMENT ON COLUMN purchase_alert_snapshot.ref_code IS 'ref编码';
COMMENT ON COLUMN purchase_alert_snapshot.notified_at IS 'notified时间';
COMMENT ON COLUMN purchase_alert_snapshot.resolved_at IS 'resolved时间';
COMMENT ON TABLE import_template_field IS '导入模板字段配置';
COMMENT ON COLUMN import_template_field.id IS '主键';
COMMENT ON COLUMN import_template_field.business_type IS '业务类型标识';
COMMENT ON COLUMN import_template_field.profile_code IS '导入方案编码';
COMMENT ON COLUMN import_template_field.field_key IS '字段键';
COMMENT ON COLUMN import_template_field.field_label IS '字段显示名';
COMMENT ON COLUMN import_template_field.field_type IS '字段数据类型';
COMMENT ON COLUMN import_template_field.target_column IS '映射物理列名';
COMMENT ON COLUMN import_template_field.required IS '是否必填';
COMMENT ON COLUMN import_template_field.sort_order IS '排序号';
COMMENT ON COLUMN import_template_field.is_extension IS '是否扩展字段';
COMMENT ON COLUMN import_template_field.is_active IS '是否启用';
COMMENT ON COLUMN import_template_field.remark IS '备注';
COMMENT ON COLUMN import_template_field.created_at IS '创建时间';
COMMENT ON COLUMN import_template_field.updated_at IS '更新时间';
COMMENT ON TABLE import_profile_binding IS '导入方案绑定';
COMMENT ON COLUMN import_profile_binding.business_type IS '业务类型标识';
COMMENT ON COLUMN import_profile_binding.profile_code IS '导入方案编码';
COMMENT ON COLUMN import_profile_binding.updated_at IS '更新时间';
