import type { FieldSchema } from './pageSchemas'

/** 第一期核心业务完整字段 schema */
export const businessSchemas: Record<string, FieldSchema[]> = {
  purchase_plan: [
    { prop: 'plan_code', label: '计划编号', list: true, group: 'basic', required: true },
    { prop: 'business_chain_no', label: '业务链编号', list: true, group: 'basic', readonly: true },
    { prop: 'plan_year', label: '计划年度', type: 'number', list: true, group: 'basic', required: true },
    { prop: 'plan_type', label: '计划类型', dictType: 'plan_type', group: 'basic' },
    { prop: 'fund_source', label: '资金来源', dictType: 'fund_source', group: 'finance' },
    { prop: 'dept_id', label: '申报科室', linkTable: 'department', group: 'basic' },
    { prop: 'dept_name', label: '申报科室', list: true, group: 'basic', readonly: true },
    { prop: 'applicant_id', label: '申报人', linkTable: 'sys_user', group: 'basic' },
    { prop: 'applicant_name', label: '申报人', list: true, group: 'basic', readonly: true },
    { prop: 'total_budget', label: '预算总额', type: 'number', list: true, group: 'finance', readonly: true },
    { prop: 'approval_status', label: '审批状态', dictType: 'approval_status', list: true, group: 'approval', readonly: true },
    { prop: 'approved_by', label: '审批人', linkTable: 'sys_user', group: 'approval', readonly: true },
    { prop: 'approved_at', label: '审批时间', type: 'datetime', group: 'approval', readonly: true },
    { prop: 'justification', label: '论证说明', type: 'textarea', group: 'remark' },
    { prop: 'is_large_equipment', label: '大型设备', type: 'boolean', group: 'compliance' },
    { prop: 'large_equipment_class', label: '大型设备分类', dictType: 'large_equipment_class', group: 'compliance' },
    { prop: 'benefit_analysis_url', label: '效益分析', type: 'file', group: 'attachment' },
    { prop: 'dept_argument_url', label: '科室论证纪要', type: 'file', group: 'attachment' },
    { prop: 'remark', label: '备注', type: 'textarea', group: 'remark' },
    { prop: 'is_active', label: '启用', type: 'boolean', group: 'other' }
  ],
  purchase_plan_item: [
    { prop: 'device_name', label: '设备名称', list: true, detail: true, required: true },
    { prop: 'category_id', label: '设备分类', linkTable: 'medical_device_category', detail: true },
    { prop: 'use_dept_id', label: '使用科室', linkTable: 'department', detail: true },
    { prop: 'quantity', label: '数量', type: 'number', list: true, detail: true, required: true },
    { prop: 'unit', label: '单位', detail: true },
    { prop: 'estimated_price', label: '预估单价', type: 'number', list: true, detail: true },
    { prop: 'total_price', label: '金额小计', type: 'number', list: true, detail: true },
    { prop: 'specification', label: '规格型号', type: 'textarea', detail: true },
    { prop: 'is_imported', label: '进口设备', type: 'boolean', detail: true },
    { prop: 'registration_no', label: '注册证号', detail: true },
    { prop: 'brand_intent', label: '意向品牌', detail: true },
    { prop: 'is_metrology', label: '需计量', type: 'boolean', detail: true },
    { prop: 'udi_code', label: 'UDI编码', detail: true },
    { prop: 'priority', label: '优先级', type: 'number', detail: true },
    { prop: 'justification', label: '购置理由', type: 'textarea', detail: true }
  ],
  purchase_project: [
    { prop: 'project_code', label: '项目编号', list: true, group: 'basic', required: true },
    { prop: 'business_chain_no', label: '业务链编号', list: true, group: 'basic', readonly: true },
    { prop: 'project_name', label: '项目名称', list: true, group: 'basic', required: true },
    { prop: 'plan_id', label: '关联计划', linkTable: 'purchase_plan', group: 'basic' },
    { prop: 'plan_code', label: '计划编号', list: true, group: 'basic', readonly: true },
    { prop: 'purchase_method', label: '采购方式', dictType: 'purchase_method', list: true, group: 'basic' },
    { prop: 'supplier_id', label: '中标供应商', linkTable: 'supplier', group: 'basic' },
    { prop: 'supplier_name', label: '中标供应商', list: true, group: 'basic', readonly: true },
    { prop: 'total_amount', label: '项目金额', type: 'number', list: true, group: 'finance' },
    { prop: 'budget_amount', label: '预算金额', type: 'number', group: 'finance' },
    { prop: 'bid_open_date', label: '开标日期', type: 'date', list: true, group: 'workflow' },
    { prop: 'award_date', label: '定标日期', type: 'date', group: 'workflow' },
    { prop: 'bid_agency', label: '招标代理机构', group: 'workflow' },
    { prop: 'notice_date', label: '公告日期', type: 'date', group: 'workflow' },
    { prop: 'control_price', label: '招标控制价', type: 'number', group: 'finance' },
    { prop: 'approval_status', label: '审批状态', dictType: 'approval_status', list: true, group: 'workflow', readonly: true },
    { prop: 'status', label: '状态', dictType: 'project_status', list: true, group: 'workflow' },
    { prop: 'bid_sections', label: '招标标段', type: 'textarea', group: 'workflow' },
    { prop: 'bid_evaluation', label: '评标结果', type: 'textarea', group: 'workflow' },
    { prop: 'argument_report_url', label: '论证报告', type: 'file', group: 'attachment' }
  ],
  purchase_contract: [
    { prop: 'contract_code', label: '合同编号', list: true, group: 'basic', required: true },
    { prop: 'business_chain_no', label: '业务链编号', list: true, group: 'basic', readonly: true },
    { prop: 'contract_name', label: '合同名称', list: true, group: 'basic', required: true },
    { prop: 'project_id', label: '采购项目', linkTable: 'purchase_project', group: 'basic' },
    { prop: 'project_name', label: '采购项目', list: true, group: 'basic', readonly: true },
    { prop: 'supplier_id', label: '供应商', linkTable: 'supplier', group: 'basic' },
    { prop: 'supplier_name', label: '供应商', list: true, group: 'basic', readonly: true },
    { prop: 'sign_date', label: '签订日期', type: 'date', list: true, group: 'basic' },
    { prop: 'start_date', label: '开始日期', type: 'date', group: 'basic' },
    { prop: 'end_date', label: '结束日期', type: 'date', group: 'basic' },
    { prop: 'delivery_deadline', label: '交货期限', type: 'date', group: 'basic' },
    { prop: 'contract_amount', label: '合同金额', type: 'number', list: true, group: 'finance' },
    { prop: 'contract_type', label: '合同类型', dictType: 'contract_type', group: 'basic' },
    { prop: 'performance_bond', label: '履约保证金', type: 'number', group: 'finance' },
    { prop: 'registration_cert_url', label: '注册证附件', type: 'file', group: 'attachment' },
    { prop: 'paid_amount', label: '已付金额', type: 'number', list: true, group: 'finance', readonly: true },
    { prop: 'payment_progress', label: '付款进度%', type: 'number', list: true, group: 'finance', readonly: true },
    { prop: 'warranty_period', label: '质保期(月)', type: 'number', group: 'finance' },
    { prop: 'payment_terms', label: '付款条款', type: 'textarea', group: 'finance' },
    { prop: 'contract_file_url', label: '合同附件', type: 'file', group: 'attachment' },
    { prop: 'acceptance_status', label: '安装验收', dictType: 'acceptance_status', list: true, group: 'workflow' },
    { prop: 'acceptance_report_url', label: '验收报告', type: 'file', group: 'attachment' },
    { prop: 'invoice_summary', label: '发票汇总', type: 'textarea', group: 'finance' },
    { prop: 'approval_status', label: '审批状态', dictType: 'approval_status', list: true, group: 'approval', readonly: true },
    { prop: 'status', label: '合同状态', dictType: 'contract_status', list: true, group: 'workflow' },
    { prop: 'remark', label: '备注', type: 'textarea', group: 'remark' }
  ],
  contract_payment: [
    { prop: 'payment_no', label: '付款单号', list: true, detail: true, required: true },
    { prop: 'payment_stage', label: '付款阶段', dictType: 'payment_stage', list: true, detail: true },
    { prop: 'payment_amount', label: '付款金额', type: 'number', list: true, detail: true },
    { prop: 'payment_date', label: '付款日期', type: 'date', detail: true },
    { prop: 'invoice_no', label: '发票号', list: true, detail: true },
    { prop: 'invoice_type', label: '发票类型', dictType: 'invoice_type', detail: true },
    { prop: 'tax_amount', label: '税额', type: 'number', detail: true },
    { prop: 'voucher_no', label: '财务凭证号', detail: true },
    { prop: 'invoice_url', label: '发票附件', type: 'file', detail: true },
    { prop: 'payee_account', label: '收款账户', detail: true },
    { prop: 'status', label: '状态', dictType: 'payment_status', list: true, detail: true },
    { prop: 'approval_status', label: '审批状态', dictType: 'approval_status', list: true, detail: true, readonly: true },
    { prop: 'remark', label: '备注', type: 'textarea', detail: true }
  ],
  purchase_acceptance: [
    { prop: 'acceptance_no', label: '验收单号', list: true, group: 'basic', readonly: true },
    { prop: 'business_chain_no', label: '业务链编号', list: true, group: 'basic', readonly: true },
    { prop: 'contract_id', label: '采购合同', linkTable: 'purchase_contract', group: 'basic', readonly: true },
    { prop: 'contract_code', label: '合同编号', list: true, group: 'basic', readonly: true },
    { prop: 'supplier_name', label: '供应商', list: true, group: 'basic', readonly: true },
    { prop: 'acceptance_date', label: '验收日期', type: 'date', list: true, group: 'workflow' },
    { prop: 'acceptance_status', label: '验收状态', dictType: 'acceptance_status', list: true, group: 'workflow' },
    { prop: 'approval_status', label: '审批状态', dictType: 'approval_status', list: true, group: 'workflow', readonly: true },
    { prop: 'entry_no', label: '入库单号', list: true, group: 'workflow', readonly: true },
    { prop: 'entry_status', label: '入库状态', list: true, group: 'workflow', readonly: true },
    { prop: 'quality_check_passed', label: '质检通过', type: 'boolean', group: 'workflow' },
    { prop: 'quality_checker_id', label: '质检人', linkTable: 'sys_user', group: 'workflow' },
    { prop: 'quality_check_date', label: '质检日期', type: 'date', group: 'workflow' },
    { prop: 'quality_check_report_url', label: '质检报告', type: 'file', group: 'attachment' },
    { prop: 'installation_completed', label: '安装完成', type: 'boolean', group: 'workflow' },
    { prop: 'installer_id', label: '安装人', linkTable: 'sys_user', group: 'workflow' },
    { prop: 'installation_date', label: '安装日期', type: 'date', group: 'workflow' },
    { prop: 'installation_report_url', label: '安装报告', type: 'file', group: 'attachment' },
    { prop: 'clinical_checker_id', label: '临床验收人', linkTable: 'sys_user', group: 'workflow' },
    { prop: 'argument_summary', label: '论证摘要', type: 'textarea', group: 'remark' },
    { prop: 'report_url', label: '验收报告', type: 'file', group: 'attachment' },
    { prop: 'remark', label: '备注', type: 'textarea', group: 'remark' }
  ],
  supplier: [
    { prop: 'supplier_code', label: '供应商编码', list: true, required: true },
    { prop: 'supplier_name', label: '供应商名称', list: true, required: true },
    { prop: 'pinyin_code', label: '拼音简码', list: true },
    { prop: 'unified_social_credit_code', label: '统一社会信用代码', list: true },
    { prop: 'legal_representative', label: '法人代表' },
    { prop: 'contact_person', label: '联系人', list: true },
    { prop: 'contact_phone', label: '联系电话', list: true },
    { prop: 'address', label: '地址', type: 'textarea' },
    { prop: 'bank_name', label: '开户行' },
    { prop: 'bank_account', label: '银行账号' },
    { prop: 'rating', label: '评级', type: 'number', list: true },
    { prop: 'is_authorized', label: '授权经销商', type: 'boolean', list: true },
    { prop: 'is_active', label: '启用', type: 'boolean', list: true }
  ],
  manufacturer: [
    { prop: 'manufacturer_code', label: '厂商编码', list: true, required: true },
    { prop: 'manufacturer_name', label: '厂商名称', list: true, required: true },
    { prop: 'pinyin_code', label: '拼音简码', list: true },
    { prop: 'country', label: '国家/地区', list: true },
    { prop: 'is_domestic', label: '国产厂商', type: 'boolean', list: true },
    { prop: 'contact_phone', label: '联系电话', list: true },
    { prop: 'website', label: '官网' },
    { prop: 'is_active', label: '启用', type: 'boolean', list: true }
  ],
  medical_device_category: [
    { prop: 'category_code', label: '分类编码(68码)', list: true, required: true },
    { prop: 'category_name', label: '分类名称', list: true, required: true },
    { prop: 'parent_code', label: '上级编码', list: true },
    { prop: 'level', label: '层级', type: 'number', list: true },
    { prop: 'full_path', label: '完整路径' },
    { prop: 'sort_order', label: '排序', type: 'number', list: true },
    { prop: 'is_active', label: '启用', type: 'boolean', list: true }
  ],
  asset_category: [
    { prop: 'category_code', label: '分类编码', list: true, required: true },
    { prop: 'category_name', label: '分类名称', list: true, required: true },
    { prop: 'parent_id', label: '上级分类', linkTable: 'asset_category' },
    { prop: 'depreciation_years', label: '折旧年限', type: 'number', list: true },
    { prop: 'residual_rate', label: '残值率(%)', type: 'number', list: true },
    { prop: 'sort_order', label: '排序', type: 'number', list: true },
    { prop: 'is_active', label: '启用', type: 'boolean', list: true }
  ],
  finance_category: [
    { prop: 'finance_code', label: '财务编码', list: true, required: true },
    { prop: 'finance_name', label: '财务名称', list: true, required: true },
    { prop: 'parent_id', label: '上级分类', linkTable: 'finance_category' },
    { prop: 'account_subject', label: '会计科目', list: true },
    { prop: 'fund_source', label: '资金来源', dictType: 'fund_source', list: true },
    { prop: 'sort_order', label: '排序', type: 'number', list: true },
    { prop: 'is_active', label: '启用', type: 'boolean', list: true }
  ],
  unit_dict: [
    { prop: 'unit_code', label: '单位编码', list: true, required: true },
    { prop: 'unit_name', label: '单位名称', list: true, required: true },
    { prop: 'unit_type', label: '单位类型', dictType: 'unit_type', list: true },
    { prop: 'sort_order', label: '排序', type: 'number', list: true },
    { prop: 'is_active', label: '启用', type: 'boolean', list: true }
  ],
  medical_device: [
    { prop: 'device_code', label: '设备编码', list: true, group: 'basic', required: true },
    { prop: 'device_name', label: '设备名称', list: true, group: 'basic', required: true },
    { prop: 'brand', label: '品牌', list: true, group: 'basic' },
    { prop: 'specification', label: '规格', list: true, group: 'basic' },
    { prop: 'model', label: '型号', list: true, group: 'basic' },
    { prop: 'registration_no', label: '注册证号', group: 'basic' },
    { prop: 'serial_number', label: '序列号', group: 'basic' },
    { prop: 'device_unit', label: '单位', group: 'basic' },
    { prop: 'category_id', label: '设备分类(68码)', linkTable: 'medical_device_category', group: 'basic' },
    { prop: 'asset_category_id', label: '资产分类', linkTable: 'asset_category', group: 'basic' },
    { prop: 'finance_category_id', label: '财务分类', linkTable: 'finance_category', group: 'basic' },
    { prop: 'standby_current_max_ma', label: '待机电流上限(mA)', type: 'number', group: 'basic' },
    { prop: 'standby_current_min_ma', label: '待机电流下限(mA)', type: 'number', group: 'basic' },
    { prop: 'country_of_origin', label: '原产国', group: 'basic' },
    { prop: 'is_imported', label: '进口设备', type: 'boolean', group: 'basic' },
    { prop: 'pinyin_code', label: '拼音简码', group: 'basic' },
    { prop: 'dept_id', label: '领用科室', linkTable: 'department', list: true, group: 'basic' },
    { prop: 'manage_dept_id', label: '管理科室', linkTable: 'department', group: 'basic' },
    { prop: 'original_value', label: '折旧起点', type: 'number', list: true, group: 'finance' },
    { prop: 'net_value', label: '当前净值', type: 'number', list: true, group: 'finance' },
    { prop: 'residual_rate', label: '残值率(%)', type: 'number', group: 'finance', placeholder: '按百分比如：5%' },
    { prop: 'depreciation_years', label: '折旧年限', type: 'number', group: 'finance' },
    { prop: 'monthly_depreciation', label: '月折旧', type: 'number', group: 'finance' },
    { prop: 'accumulated_depreciation', label: '累计折旧', type: 'number', group: 'finance' },
    { prop: 'financial_code', label: '财务编码', group: 'finance' },
    { prop: 'accrued_disposal_cost', label: '预提清理费用', type: 'number', group: 'finance' },
    { prop: 'depreciation_start_date', label: '开始折旧日期', type: 'date', group: 'finance' },
    { prop: 'depreciated_months', label: '已折旧月份', type: 'number', group: 'finance' },
    { prop: 'estimated_useful_life_months', label: '预计使用年限(单位：月)', type: 'number', group: 'finance' },
    { prop: 'monthly_depreciation_rate', label: '月折旧率', type: 'number', group: 'finance' },
    { prop: 'depreciation_status', label: '折旧状态', dictType: 'depreciation_status', group: 'finance' },
    { prop: 'campus_id', label: '院区', linkTable: 'campus', group: 'location' },
    { prop: 'building_id', label: '楼宇', linkTable: 'building', group: 'location' },
    { prop: 'warehouse_id', label: '所在库房', linkTable: 'warehouse', group: 'location' },
    { prop: 'location_floor', label: '楼层', group: 'location' },
    { prop: 'room_number', label: '房间号', group: 'location' },
    { prop: 'location_detail', label: '位置详情', group: 'location', span: 24 },
    { prop: 'supplier_uscc', label: '社会统一信用代码', group: 'vendor' },
    { prop: 'supplier_id', label: '供应商', linkTable: 'supplier', group: 'vendor' },
    { prop: 'supplier_contact', label: '负责人', group: 'vendor' },
    { prop: 'supplier_phone', label: '供应商电话', group: 'vendor' },
    { prop: 'maintenance_uscc', label: '社会统一信用代码', group: 'vendor' },
    { prop: 'maintenance_company', label: '维修公司', group: 'vendor' },
    { prop: 'maintenance_engineer', label: '工程师', group: 'vendor' },
    { prop: 'maintenance_phone', label: '维修电话', group: 'vendor' },
    { prop: 'manufacturer_uscc', label: '社会统一信用代码', group: 'vendor' },
    { prop: 'manufacturer_id', label: '生产厂商', linkTable: 'manufacturer', group: 'vendor' },
    { prop: 'contract_name', label: '合同名称', group: 'time' },
    { prop: 'purchase_date', label: '购置日期', type: 'date', group: 'time' },
    { prop: 'enable_date', label: '启用日期', type: 'date', list: true, group: 'time' },
    { prop: 'production_date', label: '生产日期', type: 'date', group: 'time' },
    { prop: 'service_life_years', label: '使用年限', type: 'number', group: 'time' },
    { prop: 'service_expiry_date', label: '使用到期日期', type: 'date', group: 'time', readonly: true },
    { prop: 'calibration_period_days', label: '计量周期(天)', type: 'number', group: 'time' },
    { prop: 'last_calibration_date', label: '上次计量日期', type: 'date', group: 'time' },
    { prop: 'next_calibration_date', label: '下次计量日期', type: 'date', group: 'time', readonly: true },
    { prop: 'warranty_end_date', label: '保修截止', type: 'date', group: 'time' },
    { prop: 'contract_sign_date', label: '签订日期', type: 'date', group: 'time' },
    { prop: 'contract_price', label: '合同价格', type: 'number', group: 'time' },
    { prop: 'contract_submit_time', label: '送审时间', type: 'datetime', group: 'time' },
    { prop: 'bid_win_date', label: '中标日期', type: 'date', group: 'time' },
    { prop: 'supply_notice_date', label: '通知供货时间', type: 'date', group: 'time' },
    { prop: 'delivery_deadline', label: '交货截止日期', type: 'date', group: 'time' },
    { prop: 'first_acceptance_date', label: '首次验收日期', type: 'date', group: 'time' },
    { prop: 'second_acceptance_date', label: '二次验收日期', type: 'date', group: 'time' },
    { prop: 'warranty_expiry_date', label: '出保日期', type: 'date', group: 'time' },
    { prop: 'material_category_code', label: '物料分类编码', group: 'accounting' },
    { prop: 'material_group', label: '物料分组', group: 'accounting' },
    { prop: 'asset_class_code', label: '资产类别编码', group: 'accounting' },
    { prop: 'asset_class_name', label: '资产类别', group: 'accounting' },
    { prop: 'acceptance_date', label: '验收日期', type: 'date', group: 'accounting' },
    { prop: 'kingdee_asset_code', label: '金蝶资产编码', group: 'accounting', readonly: true },
    { prop: 'invoice_no', label: '发票号', group: 'accounting' },
    { prop: 'invoice_date', label: '发票日期', type: 'date', group: 'accounting' },
    { prop: 'expense_item_code', label: '费用项目编号', group: 'accounting' },
    { prop: 'expense_item_name', label: '费用项目名称', group: 'accounting' },
    { prop: 'fund_source', label: '资金来源', group: 'accounting' },
    { prop: 'lease_fee_per_use', label: '租借按次费用', type: 'number', group: 'accounting', placeholder: '元/次' },
    { prop: 'lease_fee_per_day', label: '租借按天费用', type: 'number', group: 'accounting', placeholder: '元/天' },
    { prop: 'device_status', label: '设备状态', dictType: 'device_status', list: true, group: 'status' },
    { prop: 'risk_level', label: '风险等级', dictType: 'risk_level', list: true, group: 'status' },
    { prop: 'is_life_support', label: '生命支持', type: 'boolean', group: 'status' },
    { prop: 'is_emergency', label: '应急设备', type: 'boolean', group: 'status' },
    { prop: 'is_metrology', label: '计量设备', type: 'boolean', list: true, group: 'status' },
    { prop: 'is_shared_device', label: '公用设备', type: 'boolean', list: true, group: 'status' },
    { prop: 'is_maintain_device', label: '保养设备', type: 'boolean', list: true, group: 'status' },
    { prop: 'is_inspection_device', label: '巡检设备', type: 'boolean', list: true, group: 'status' },
    { prop: 'is_pm_device', label: '预防性维护设备', type: 'boolean', list: true, group: 'status', width: 140 },
    { prop: 'metrology_type_code', label: '计量检定类型', linkTable: 'metrology_type_code', group: 'compliance' },
    { prop: 'shared_fee_mode', label: '借调计费方式', dictType: 'shared_fee_mode', group: 'compliance' },
    { prop: 'shared_fee_time_unit', label: '计时单位', dictType: 'shared_fee_time_unit', group: 'compliance' },
    { prop: 'shared_fee_unit_price', label: '借调单价(元)', type: 'number', group: 'compliance' },
    { prop: 'electronic_tag_barcode', label: '电子标签条码', group: 'compliance' },
    { prop: 'boot_current_min_ma', label: '开机电流下限', type: 'number', group: 'compliance' },
    { prop: 'boot_current_max_ma', label: '开机电流上限', type: 'number', group: 'compliance' },
    { prop: 'risk_assessment', label: '风险评估', group: 'other' },
    { prop: 'inventory_category', label: '存货类别', group: 'other' },
    { prop: 'after_sales_engineer', label: '售后工程师', group: 'other' },
    { prop: 'after_sales_engineer_phone', label: '售后工程师电话', group: 'other' },
    { prop: 'warranty_start_date', label: '保修开始', type: 'date', group: 'other' },
    { prop: 'warranty_service_end_date', label: '保修结束', type: 'date', group: 'other' },
    { prop: 'warranty_period_years', label: '质保期/年', type: 'number', group: 'other' },
    { prop: 'warranty_type', label: '保修类型', group: 'other' },
    { prop: 'has_network_function', label: '设备是否配备联网功能', type: 'boolean', group: 'other' },
    { prop: 'same_batch_purchase_count', label: '同批购进相同型号设备台数', type: 'number', group: 'other' },
    { prop: 'remark', label: '备注', type: 'textarea', group: 'other', span: 24 },
    { prop: 'standard_function_count', label: '标准功能数量', type: 'number', group: 'other' },
    { prop: 'purchase_expected_benefit', label: '申购预计效益', group: 'other' },
    { prop: 'rated_workload', label: '额定工作量', group: 'other' },
    { prop: 'is_active', label: '启用', type: 'boolean', group: 'other' },
    { prop: 'qr_code_url', label: '二维码URL', group: 'attachment', readonly: true },
    { prop: 'label_printed', label: '已打标签', type: 'boolean', group: 'attachment' },
  ],
  device_entry: [
    { prop: 'entry_no', label: '入库单号', list: true, group: 'basic', readonly: true },
    { prop: 'trace_no', label: '业务追溯号', list: true, group: 'basic', readonly: true },
    { prop: 'business_chain_no', label: '业务链编号', list: true, group: 'basic', readonly: true },
    { prop: 'contract_id', label: '采购合同', linkTable: 'purchase_contract', group: 'basic' },
    { prop: 'contract_code', label: '合同编号', list: true, group: 'basic', readonly: true },
    { prop: 'supplier_name', label: '供应商', list: true, group: 'basic', readonly: true },
    { prop: 'entry_date', label: '入库日期', type: 'date', list: true, group: 'basic' },
    { prop: 'entry_type', label: '入库类型', dictType: 'entry_type', list: true, group: 'basic' },
    { prop: 'warehouse_id', label: '入库库房', linkTable: 'warehouse', list: true, group: 'basic' },
    { prop: 'operator_id', label: '经办人', linkTable: 'sys_user', group: 'basic' },
    { prop: 'quality_check_passed', label: '质量验收', type: 'boolean', list: true, group: 'workflow' },
    { prop: 'quality_checker_id', label: '验收人', linkTable: 'sys_user', group: 'workflow' },
    { prop: 'quality_check_date', label: '验收日期', type: 'date', group: 'workflow' },
    { prop: 'quality_check_report_url', label: '验收报告', group: 'attachment' },
    { prop: 'installation_completed', label: '安装完成', type: 'boolean', group: 'workflow' },
    { prop: 'installation_date', label: '安装日期', type: 'date', group: 'workflow' },
    { prop: 'status', label: '状态', dictType: 'entry_status', list: true, group: 'workflow' },
    { prop: 'remark', label: '备注', type: 'textarea', group: 'remark' }
  ],
  device_entry_item: [
    { prop: 'device_name', label: '设备名称', list: true, detail: true, required: true },
    { prop: 'brand', label: '品牌', detail: true },
    { prop: 'model', label: '型号', detail: true },
    { prop: 'serial_number', label: '序列号', detail: true },
    { prop: 'quantity', label: '数量', type: 'number', detail: true },
    { prop: 'unit_price', label: '单价', type: 'number', detail: true },
    { prop: 'total_price', label: '金额', type: 'number', detail: true },
    { prop: 'is_accepted', label: '已验收', type: 'boolean', detail: true }
  ],
  device_outbound: [
    { prop: 'outbound_no', label: '出库单号', list: true, readonly: true },
    { prop: 'outbound_date', label: '出库日期', type: 'date', list: true },
    { prop: 'dept_id', label: '领用科室', linkTable: 'department', list: true },
    { prop: 'receiver_id', label: '领用人', linkTable: 'sys_user', list: true },
    { prop: 'warehouse_id', label: '出库库房', linkTable: 'warehouse', list: true },
    { prop: 'warehouse_name', label: '库房', list: true, readonly: true },
    { prop: 'dept_name', label: '科室', list: true, readonly: true },
    { prop: 'purpose', label: '用途', type: 'textarea' },
    { prop: 'doc_status', label: '审批状态', dictType: 'approval_status', list: true },
    { prop: 'status', label: '出库状态', dictType: 'outbound_status', list: true },
    { prop: 'remark', label: '备注', type: 'textarea' }
  ],
  device_outbound_item: [
    { prop: 'device_code', label: '设备编码', list: true, detail: true },
    { prop: 'device_name', label: '设备名称', list: true, detail: true },
    { prop: 'device_id', label: '设备', linkTable: 'medical_device', detail: true },
    { prop: 'quantity', label: '数量', type: 'number', detail: true }
  ],
  asset_transfer: [
    { prop: 'transfer_no', label: '流转单号', list: true, readonly: true },
    { prop: 'transfer_type', label: '流转类型', dictType: 'transfer_type', list: true },
    { prop: 'device_id', label: '设备', linkTable: 'medical_device', list: true },
    { prop: 'from_dept_id', label: '转出科室', linkTable: 'department', list: true },
    { prop: 'to_dept_id', label: '转入科室', linkTable: 'department', list: true },
    { prop: 'from_campus_id', label: '转出院区', linkTable: 'campus' },
    { prop: 'to_campus_id', label: '转入院区', linkTable: 'campus' },
    { prop: 'from_warehouse_id', label: '转出库房', linkTable: 'warehouse', list: true },
    { prop: 'to_warehouse_id', label: '转入库房', linkTable: 'warehouse', list: true },
    { prop: 'transfer_date', label: '流转日期', type: 'date', list: true },
    { prop: 'reason', label: '流转原因', type: 'textarea' },
    { prop: 'status', label: '状态', dictType: 'transfer_status', list: true },
    { prop: 'remark', label: '备注', type: 'textarea' }
  ],
  inventory_check: [
    { prop: 'check_no', label: '盘点单号', list: true, readonly: true },
    { prop: 'check_name', label: '盘点名称', list: true, required: true },
    { prop: 'check_year', label: '盘点年度', type: 'number', list: true },
    { prop: 'check_type', label: '盘点类型', dictType: 'check_type', list: true },
    { prop: 'campus_id', label: '院区', linkTable: 'campus', list: true },
    { prop: 'dept_id', label: '科室', linkTable: 'department', list: true },
    { prop: 'warehouse_id', label: '盘点库房', linkTable: 'warehouse', list: true },
    { prop: 'start_date', label: '计划开始', type: 'date', list: true },
    { prop: 'end_date', label: '计划结束', type: 'date' },
    { prop: 'checker_id', label: '盘点人', linkTable: 'sys_user' },
    { prop: 'supervisor_id', label: '监盘人', linkTable: 'sys_user' },
    { prop: 'created_by', label: '制单人', linkTable: 'sys_user', list: true, readonly: true },
    { prop: 'created_at', label: '制单时间', type: 'datetime', list: true, readonly: true },
    { prop: 'approved_by', label: '审核人', linkTable: 'sys_user', list: true, readonly: true },
    { prop: 'approved_at', label: '审核时间', type: 'datetime', list: true, readonly: true },
    { prop: 'audit_status', label: '审核状态', dictType: 'audit_status', list: true, readonly: true },
    { prop: 'total_count', label: '应盘数量', type: 'number', list: true, readonly: true },
    { prop: 'checked_count', label: '已盘数量', type: 'number', list: true, readonly: true },
    { prop: 'matched_count', label: '账实相符', type: 'number', list: true, readonly: true },
    { prop: 'mismatch_count', label: '差异数量', type: 'number', list: true, readonly: true },
    { prop: 'status', label: '状态', dictType: 'check_status', list: true },
    { prop: 'remark', label: '备注', type: 'textarea' }
  ],
  inventory_check_item: [
    { prop: 'device_code', label: '设备编码', list: true, detail: true, readonly: true },
    { prop: 'device_name', label: '设备名称', list: true, detail: true, readonly: true },
    { prop: 'expected_location', label: '账面位置', detail: true, readonly: true },
    { prop: 'actual_location', label: '实盘位置', detail: true },
    { prop: 'is_found', label: '是否找到', type: 'boolean', detail: true },
    { prop: 'is_matched', label: '账实相符', type: 'boolean', detail: true },
    { prop: 'condition_status', label: '设备状况', dictType: 'condition_status', detail: true },
    { prop: 'remark', label: '备注', type: 'textarea', detail: true }
  ],
  device_return: [
    { prop: 'return_no', label: '退货单号', list: true, readonly: true },
    { prop: 'outbound_id', label: '关联出库单', linkTable: 'device_outbound', group: 'basic' },
    { prop: 'outbound_no', label: '出库单号', list: true, readonly: true },
    { prop: 'warehouse_id', label: '退回库房', linkTable: 'warehouse', list: true },
    { prop: 'warehouse_name', label: '库房', list: true, readonly: true },
    { prop: 'dept_id', label: '退货科室', linkTable: 'department', list: true },
    { prop: 'returner_id', label: '退货人', linkTable: 'sys_user' },
    { prop: 'return_date', label: '退货日期', type: 'date', list: true },
    { prop: 'return_type', label: '退货类型', dictType: 'return_type', list: true },
    { prop: 'reason', label: '退货原因', type: 'textarea', list: true },
    { prop: 'approval_status', label: '审批状态', dictType: 'approval_status', list: true, readonly: true },
    { prop: 'status', label: '退货状态', dictType: 'return_status', list: true },
    { prop: 'remark', label: '备注', type: 'textarea' }
  ],
  device_return_item: [
    { prop: 'device_code', label: '设备编码', list: true, detail: true },
    { prop: 'device_name', label: '设备名称', list: true, detail: true },
    { prop: 'device_id', label: '设备', linkTable: 'medical_device', detail: true },
    { prop: 'quantity', label: '数量', type: 'number', detail: true },
    { prop: 'condition_note', label: '状况说明', type: 'textarea', detail: true }
  ],
  adverse_event: [
    { prop: 'event_no', label: '事件编号', list: true, group: 'basic', readonly: true },
    { prop: 'device_id', label: '关联设备', linkTable: 'medical_device', list: true, group: 'basic', required: true },
    { prop: 'device_code', label: '设备编码', list: true, group: 'basic', readonly: true },
    { prop: 'device_name', label: '设备名称', list: true, group: 'basic', readonly: true },
    { prop: 'dept_name', label: '所属科室', list: true, group: 'basic', readonly: true },
    { prop: 'reporter_id', label: '上报人', linkTable: 'sys_user', group: 'basic' },
    { prop: 'reporter_name', label: '上报人', list: true, group: 'basic', readonly: true },
    { prop: 'report_time', label: '上报时间', type: 'datetime', list: true, group: 'basic' },
    { prop: 'event_type', label: '事件类型', dictType: 'adverse_event_type', list: true, group: 'event' },
    { prop: 'severity_level', label: '严重等级', dictType: 'adverse_severity', list: true, group: 'event' },
    { prop: 'event_description', label: '事件描述', type: 'textarea', list: true, group: 'event', required: true },
    { prop: 'cause_analysis', label: '原因分析', type: 'textarea', group: 'event' },
    { prop: 'impact_description', label: '影响描述', type: 'textarea', group: 'event' },
    { prop: 'status', label: '处理状态', dictType: 'adverse_status', list: true, group: 'workflow', readonly: true },
    { prop: 'handler_id', label: '处理人', linkTable: 'sys_user', group: 'workflow' },
    { prop: 'handle_measures', label: '处理措施', type: 'textarea', group: 'workflow' },
    { prop: 'handle_time', label: '处理时间', type: 'datetime', group: 'workflow', readonly: true },
    { prop: 'reviewer_id', label: '审核人', linkTable: 'sys_user', group: 'workflow' },
    { prop: 'review_comment', label: '审核意见', type: 'textarea', group: 'workflow' },
    { prop: 'review_time', label: '审核时间', type: 'datetime', group: 'workflow', readonly: true },
    { prop: 'reported_to_authority', label: '已报监管', type: 'boolean', list: true, group: 'authority' },
    { prop: 'report_date', label: '监管上报日', type: 'date', group: 'authority' },
    { prop: 'authority_feedback', label: '监管反馈', type: 'textarea', group: 'authority' },
    { prop: 'remark', label: '备注', type: 'textarea', group: 'remark' }
  ],
  device_scrap: [
    { prop: 'scrap_no', label: '报废单号', list: true, readonly: true },
    { prop: 'device_id', label: '设备', linkTable: 'medical_device', list: true },
    { prop: 'device_code', label: '设备编码', list: true, readonly: true },
    { prop: 'device_name', label: '设备名称', list: true, readonly: true },
    { prop: 'scrap_reason', label: '报废原因', type: 'textarea', list: true, required: true },
    { prop: 'scrap_type', label: '报废类型', dictType: 'scrap_type', list: true },
    { prop: 'application_date', label: '申请日期', type: 'date', list: true },
    { prop: 'evaluator_id', label: '评估人', linkTable: 'sys_user' },
    { prop: 'evaluation_result', label: '评估结论', type: 'textarea' },
    { prop: 'residual_value', label: '残值', type: 'number' },
    { prop: 'disposal_method', label: '处置方式', dictType: 'disposal_method' },
    { prop: 'disposal_date', label: '处置日期', type: 'date' },
    { prop: 'status', label: '状态', dictType: 'scrap_status', list: true },
    { prop: 'remark', label: '备注', type: 'textarea' }
  ],
  inspection_type: [
    { prop: 'type_code', label: '类型编码', list: true, required: true },
    { prop: 'type_name', label: '类型名称', list: true, required: true },
    { prop: 'sort_order', label: '排序', type: 'number', list: true },
    { prop: 'description', label: '说明', type: 'textarea' },
    { prop: 'is_active', label: '启用', type: 'boolean', list: true }
  ],
  inspection_template_item: [
    { prop: 'item_code', label: '项目编码', list: true },
    { prop: 'item_name', label: '项目名称', list: true, required: true },
    { prop: 'item_content', label: '巡检内容', type: 'textarea', list: true },
    { prop: 'standard_value', label: '标准值', list: true },
    { prop: 'check_method', label: '检查方法' },
    { prop: 'sort_order', label: '排序', type: 'number' },
    { prop: 'is_required', label: '必检', type: 'boolean', list: true }
  ],
  inspection_template: [
    { prop: 'template_code', label: '模板编码', list: true, required: true },
    { prop: 'template_name', label: '模板名称', list: true, required: true },
    { prop: 'inspection_type_id', label: '巡检类型', linkTable: 'inspection_type', list: true },
    { prop: 'description', label: '说明', type: 'textarea' },
    { prop: 'estimated_duration', label: '预计工时(分)', type: 'number' },
    { prop: 'is_active', label: '启用', type: 'boolean', list: true }
  ],
  inspection_plan: [
    { prop: 'plan_code', label: '计划编号', list: true },
    { prop: 'plan_name', label: '计划名称', list: true, required: true },
    { prop: 'template_id', label: '巡检模板', linkTable: 'inspection_template', list: true },
    { prop: 'device_id', label: '设备', linkTable: 'medical_device', list: true },
    { prop: 'dept_id', label: '责任科室', linkTable: 'department', list: true },
    { prop: 'cycle_days', label: '周期(天)', type: 'number', list: true },
    { prop: 'next_due_date', label: '下次巡检', type: 'date', list: true },
    { prop: 'last_inspected_at', label: '上次巡检', type: 'date' },
    { prop: 'approval_status', label: '审核状态', dictType: 'inspect_approval_status', list: true },
    { prop: 'status', label: '状态', dictType: 'plan_status', list: true }
  ],
  inspection_execution: [
    { prop: 'execution_no', label: '执行单号', list: true, readonly: true },
    { prop: 'template_id', label: '巡检模板', linkTable: 'inspection_template', list: true },
    { prop: 'planned_date', label: '计划日期', type: 'date', list: true },
    { prop: 'assigned_inspector_id', label: '指派巡检人', linkTable: 'sys_user', list: true },
    { prop: 'status', label: '状态', dictType: 'inspect_exec_status', list: true },
    { prop: 'remark', label: '备注', type: 'textarea' }
  ],
  inspection_execution_item: [
    { prop: 'device_code', label: '设备编码', list: true, readonly: true },
    { prop: 'device_name', label: '设备名称', list: true, readonly: true },
    { prop: 'overall_result', label: '巡检结果', dictType: 'inspect_result', list: true },
    { prop: 'status', label: '状态', dictType: 'inspect_exec_item_status', list: true }
  ],
  inspection_record: [
    { prop: 'record_no', label: '记录编号', list: true },
    { prop: 'plan_id', label: '巡检计划', linkTable: 'inspection_plan', list: true },
    { prop: 'inspector_id', label: '巡检人', linkTable: 'sys_user', list: true },
    { prop: 'inspect_date', label: '巡检日期', type: 'date', list: true },
    { prop: 'result_summary', label: '巡检结果', type: 'textarea', list: true },
    { prop: 'status', label: '状态', dictType: 'inspection_status', list: true }
  ],
  metrology_category: [
    { prop: 'category_code', label: '类别编码', list: true, required: true },
    { prop: 'category_name', label: '类别名称', list: true, required: true },
    { prop: 'sort_order', label: '排序', type: 'number', list: true },
    { prop: 'description', label: '说明', type: 'textarea' },
    { prop: 'is_active', label: '启用', type: 'boolean', list: true }
  ],
  metrology_type: [
    { prop: 'type_code', label: '类型编码', list: true, required: true, group: 'basic' },
    { prop: 'type_name', label: '类型名称', list: true, required: true, group: 'basic' },
    { prop: 'classification_group', label: '分类维度', dictType: 'metrology_classification_group', list: true, required: true, group: 'basic' },
    { prop: 'parent_id', label: '上级类型', linkTable: 'metrology_type', list: true, group: 'basic' },
    { prop: 'regulatory_attr', label: '法规属性', dictType: 'metrology_regulatory_attr', list: true, group: 'rule' },
    { prop: 'traceability_mode', label: '溯源方式', dictType: 'metrology_traceability_mode', list: true, group: 'rule' },
    { prop: 'timing_kind', label: '实施时机', dictType: 'metrology_timing_kind', group: 'rule' },
    { prop: 'location_kind', label: '执行地点', dictType: 'metrology_location_kind', group: 'rule' },
    { prop: 'management_grade', label: '管理分级', dictType: 'metrology_management_grade', list: true, group: 'rule' },
    { prop: 'cycle_rule', label: '周期规则', list: true, group: 'rule' },
    { prop: 'certificate_kind', label: '证书类型', dictType: 'metrology_certificate_kind', group: 'rule' },
    { prop: 'legal_basis', label: '法规依据', type: 'textarea', group: 'detail' },
    { prop: 'executor_scope', label: '执行机构范围', type: 'textarea', group: 'detail' },
    { prop: 'description', label: '说明', type: 'textarea', group: 'detail' },
    { prop: 'sort_order', label: '排序', type: 'number', list: true, group: 'basic' },
    { prop: 'is_active', label: '启用', type: 'boolean', list: true, group: 'basic' }
  ],
  metrology_org: [
    { prop: 'org_code', label: '机构编码', list: true, required: true },
    { prop: 'org_name', label: '机构名称', list: true, required: true },
    { prop: 'qualification_no', label: '资质编号', list: true },
    { prop: 'contact_person', label: '联系人' },
    { prop: 'contact_phone', label: '联系电话' },
    { prop: 'address', label: '地址', type: 'textarea' },
    { prop: 'is_active', label: '启用', type: 'boolean', list: true }
  ],
  metrology_template_item: [
    { prop: 'item_code', label: '项目编码', list: true },
    { prop: 'item_name', label: '项目名称', list: true, required: true },
    { prop: 'item_content', label: '检定内容', type: 'textarea', list: true },
    { prop: 'standard_value', label: '标准值', list: true },
    { prop: 'tolerance_range', label: '允差范围' },
    { prop: 'is_required', label: '必检', type: 'boolean', list: true }
  ],
  metrology_template: [
    { prop: 'template_code', label: '模板编码', list: true, required: true },
    { prop: 'template_name', label: '模板名称', list: true, required: true },
    { prop: 'category_id', label: '计量类别', linkTable: 'metrology_category', list: true },
    { prop: 'description', label: '说明', type: 'textarea' },
    { prop: 'estimated_duration', label: '预计工时(分)', type: 'number' },
    { prop: 'is_active', label: '启用', type: 'boolean', list: true }
  ],
  metrology_plan: [
    { prop: 'plan_code', label: '计划编号', list: true },
    { prop: 'plan_name', label: '计划名称', list: true, required: true },
    { prop: 'template_id', label: '计量模板', linkTable: 'metrology_template', list: true },
    { prop: 'device_id', label: '设备', linkTable: 'medical_device', list: true },
    { prop: 'category_id', label: '计量类别', linkTable: 'metrology_category', list: true },
    { prop: 'org_id', label: '检定机构', linkTable: 'metrology_org', list: true },
    { prop: 'cycle_days', label: '周期(天)', type: 'number', list: true },
    { prop: 'next_due_date', label: '下次检定', type: 'date', list: true },
    { prop: 'last_calibrated_at', label: '上次检定', type: 'date' },
    { prop: 'approval_status', label: '审核状态', dictType: 'metrology_approval_status', list: true },
    { prop: 'status', label: '状态', dictType: 'plan_status', list: true }
  ],
  metrology_execution: [
    { prop: 'execution_no', label: '执行单号', list: true, readonly: true },
    { prop: 'template_id', label: '计量模板', linkTable: 'metrology_template', list: true },
    { prop: 'org_id', label: '检定机构', linkTable: 'metrology_org', list: true },
    { prop: 'planned_date', label: '计划日期', type: 'date', list: true },
    { prop: 'status', label: '状态', dictType: 'metrology_exec_status', list: true },
    { prop: 'remark', label: '备注', type: 'textarea' }
  ],
  metrology_execution_item: [
    { prop: 'device_code', label: '设备编码', list: true, readonly: true },
    { prop: 'device_name', label: '设备名称', list: true, readonly: true },
    { prop: 'certificate_no', label: '证书编号', list: true },
    { prop: 'cost', label: '检定费用', type: 'number', list: true },
    { prop: 'overall_result', label: '检定结果', dictType: 'metrology_result', list: true },
    { prop: 'status', label: '状态', dictType: 'metrology_exec_item_status', list: true }
  ],
  repair_workorder: [
    { prop: 'wo_no', label: '工单号', list: true, group: 'basic', readonly: true },
    { prop: 'device_id', label: '设备', widget: 'repairDevicePicker', list: true, group: 'basic' },
    { prop: 'device_code', label: '设备编码', list: true, group: 'basic', readonly: true },
    { prop: 'device_name', label: '设备名称', list: true, group: 'basic', readonly: true },
    { prop: 'reporter_id', label: '报修人', linkTable: 'sys_user', group: 'basic', readonly: true },
    { prop: 'report_dept_id', label: '报修科室', linkTable: 'department', group: 'basic', readonly: true },
    { prop: 'report_method', label: '报修渠道', dictType: 'report_method', group: 'basic' },
    { prop: 'report_time', label: '报修时间', type: 'datetime', list: true, group: 'basic' },
    { prop: 'fault_description', label: '故障描述', type: 'textarea', list: true, group: 'basic', required: true },
    { prop: 'urgency_level', label: '紧急程度', dictType: 'urgency', list: true, group: 'basic' },
    { prop: 'fault_type_id', label: '故障类型', linkTable: 'fault_type_dict', group: 'basic' },
    { prop: 'assigned_user_id', label: '工程师', linkTable: 'repair_engineer', list: true, group: 'workflow' },
    { prop: 'assigned_at', label: '派工时间', type: 'datetime', group: 'workflow' },
    { prop: 'response_time', label: '响应时间', type: 'datetime', group: 'workflow' },
    { prop: 'arrival_time', label: '到场时间', type: 'datetime', group: 'workflow' },
    { prop: 'repair_start_time', label: '维修开始', type: 'datetime', group: 'workflow' },
    { prop: 'repair_end_time', label: '维修结束', type: 'datetime', group: 'workflow' },
    { prop: 'repair_duration_hours', label: '维修工时', type: 'number', group: 'workflow' },
    { prop: 'solution_description', label: '处理方案', type: 'textarea', group: 'workflow' },
    { prop: 'labor_cost', label: '人工费', type: 'number', group: 'finance' },
    { prop: 'parts_cost', label: '备件费', type: 'number', group: 'finance' },
    { prop: 'total_cost', label: '总费用', type: 'number', list: true, group: 'finance' },
    { prop: 'invoice_no', label: '发票号', group: 'finance' },
    { prop: 'verify_result', label: '验收结果', dictType: 'verify_result', group: 'workflow' },
    { prop: 'verify_comment', label: '验收意见', type: 'textarea', group: 'workflow' },
    { prop: 'satisfaction_rating', label: '满意度', type: 'number', group: 'workflow' },
    { prop: 'status', label: '状态', dictType: 'wo_status', list: true, group: 'workflow', readonly: true },
    { prop: 'repair_sub_status', label: '维修子状态', dictType: 'repair_sub_status', group: 'workflow' },
    { prop: 'remark', label: '备注', type: 'textarea', group: 'remark' }
  ],
  engineer: [
    { prop: 'engineer_no', label: '工号', list: true, required: true },
    { prop: 'real_name', label: '姓名', list: true, required: true },
    { prop: 'user_id', label: '关联用户', linkTable: 'sys_user' },
    { prop: 'specialty', label: '专业方向', list: true },
    { prop: 'phone', label: '电话', list: true },
    { prop: 'email', label: '邮箱' },
    { prop: 'is_on_duty', label: '在岗', type: 'boolean', list: true },
    { prop: 'workload_score', label: '工作量', type: 'number', list: true, readonly: true }
  ],
  spare_part: [
    { prop: 'part_code', label: '配件编码', list: true, required: true },
    { prop: 'part_name', label: '配件名称', list: true, required: true },
    { prop: 'specification', label: '规格', list: true },
    { prop: 'model', label: '型号', list: true },
    { prop: 'unit_id', label: '单位', linkTable: 'unit_dict', list: true },
    { prop: 'unit_price', label: '单价', type: 'number', list: true },
    { prop: 'manufacturer_id', label: '生产厂家', linkTable: 'manufacturer', list: true },
    { prop: 'supplier_id', label: '供应商', linkTable: 'supplier' },
    { prop: 'warehouse_id', label: '库房', linkTable: 'warehouse', list: true },
    { prop: 'category', label: '分类', list: true },
    { prop: 'stock_quantity', label: '库存', type: 'number', list: true },
    { prop: 'min_stock', label: '最低库存', type: 'number', list: true },
    { prop: 'storage_location', label: '库位' },
    { prop: 'is_active', label: '启用', type: 'boolean', list: true }
  ],
  fault_type_dict: [
    { prop: 'fault_code', label: '故障编码', list: true, required: true },
    { prop: 'fault_name', label: '故障名称', list: true, required: true },
    { prop: 'level', label: '层级', type: 'number', list: true },
    { prop: 'is_active', label: '启用', type: 'boolean', list: true }
  ],
  repair_process_type: [
    { prop: 'type_code', label: '类型编码', list: true, required: true },
    { prop: 'type_name', label: '类型名称', list: true, required: true },
    { prop: 'sort_order', label: '排序', type: 'number', list: true },
    { prop: 'is_active', label: '启用', type: 'boolean', list: true },
    { prop: 'can_add_parts', label: '允许配件', type: 'boolean', list: true },
    { prop: 'can_engineer_add', label: '工程师可新增', type: 'boolean', list: true },
    { prop: 'engineer_add_rule', label: '新增规则', list: true }
  ],
  maintenance_level: [
    { prop: 'level_code', label: '级别编码', list: true, required: true },
    { prop: 'level_name', label: '级别名称', list: true, required: true },
    { prop: 'sort_order', label: '排序', type: 'number', list: true },
    { prop: 'description', label: '说明', type: 'textarea' },
    { prop: 'is_active', label: '启用', type: 'boolean', list: true }
  ],
  maintenance_template_item: [
    { prop: 'item_code', label: '项目编码', list: true },
    { prop: 'item_name', label: '项目名称', list: true, required: true },
    { prop: 'item_content', label: '保养内容', type: 'textarea', list: true },
    { prop: 'standard_value', label: '标准值', list: true },
    { prop: 'check_method', label: '检查方法' },
    { prop: 'sort_order', label: '排序', type: 'number' },
    { prop: 'is_required', label: '必检', type: 'boolean', list: true }
  ],
  maintenance_template: [
    { prop: 'template_code', label: '模板编码', list: true, required: true },
    { prop: 'template_name', label: '模板名称', list: true, required: true },
    { prop: 'maintenance_level_id', label: '保养级别', linkTable: 'maintenance_level', list: true },
    { prop: 'description', label: '说明', type: 'textarea' },
    { prop: 'estimated_duration', label: '预计工时(分)', type: 'number' },
    { prop: 'is_active', label: '启用', type: 'boolean', list: true }
  ],
  maintenance_plan: [
    { prop: 'plan_code', label: '计划编码', list: true },
    { prop: 'plan_name', label: '计划名称', list: true, required: true },
    { prop: 'template_id', label: '保养模板', linkTable: 'maintenance_template', list: true },
    { prop: 'device_id', label: '设备', linkTable: 'medical_device', list: true },
    { prop: 'dept_id', label: '责任科室', linkTable: 'department' },
    { prop: 'cycle_type', label: '周期类型', dictType: 'cycle_type', list: true },
    { prop: 'cycle_value', label: '周期值', type: 'number' },
    { prop: 'cycle_days', label: '周期(天)', type: 'number', list: true },
    { prop: 'next_due_date', label: '下次保养', type: 'date', list: true },
    { prop: 'last_maintained_at', label: '上次保养', type: 'date' },
    { prop: 'approval_status', label: '审核状态', dictType: 'maintain_approval_status', list: true },
    { prop: 'status', label: '状态', dictType: 'maintain_plan_status', list: true }
  ],
  maintenance_execution: [
    { prop: 'execution_no', label: '执行单号', list: true, readonly: true },
    { prop: 'template_id', label: '保养模板', linkTable: 'maintenance_template', list: true },
    { prop: 'planned_date', label: '计划日期', type: 'date', list: true },
    { prop: 'assigned_engineer_id', label: '指派工程师', linkTable: 'engineer', list: true },
    { prop: 'status', label: '状态', dictType: 'maintain_exec_status', list: true },
    { prop: 'remark', label: '备注', type: 'textarea' }
  ],
  maintenance_execution_item: [
    { prop: 'device_code', label: '设备编码', list: true, readonly: true },
    { prop: 'device_name', label: '设备名称', list: true, readonly: true },
    { prop: 'overall_result', label: '保养结果', dictType: 'maintain_result', list: true },
    { prop: 'status', label: '状态', dictType: 'maintain_exec_item_status', list: true }
  ],
  maintenance_record: [
    { prop: 'record_no', label: '记录编号', list: true, readonly: true },
    { prop: 'plan_id', label: '保养计划', linkTable: 'maintenance_plan', list: true },
    { prop: 'device_id', label: '设备', linkTable: 'medical_device', list: true },
    { prop: 'maintainer_id', label: '保养人', linkTable: 'sys_user', list: true },
    { prop: 'maintained_at', label: '保养时间', type: 'datetime', list: true },
    { prop: 'maintenance_level', label: '保养级别', dictType: 'maintenance_level', list: true },
    { prop: 'result', label: '保养结果', dictType: 'maintain_result', list: true },
    { prop: 'findings', label: '发现问题', type: 'textarea' },
    { prop: 'actions_taken', label: '处理措施', type: 'textarea' },
    { prop: 'status', label: '状态', dictType: 'maintain_record_status', list: true }
  ],
  life_support_device: [
    { prop: 'device_id', label: '关联设备', linkTable: 'medical_device', list: true, group: 'basic', required: true },
    { prop: 'device_code', label: '设备编码', list: true, group: 'basic', readonly: true },
    { prop: 'device_name', label: '设备名称', list: true, group: 'basic', readonly: true },
    { prop: 'dept_name', label: '所属科室', list: true, group: 'basic', readonly: true },
    { prop: 'criticality_level', label: '关键等级', dictType: 'criticality_level', list: true, group: 'status' },
    { prop: 'backup_required', label: '需备份', type: 'boolean', group: 'status' },
    { prop: 'standby_status', label: '备用状态', dictType: 'standby_status', list: true, group: 'status' },
    { prop: 'last_test_date', label: '上次测试', type: 'date', group: 'compliance' },
    { prop: 'next_test_date', label: '下次测试', type: 'date', list: true, group: 'compliance' },
    { prop: 'responsible_person_id', label: '责任人', linkTable: 'sys_user', group: 'basic' },
    { prop: 'responsible_person_name', label: '责任人', list: true, group: 'basic', readonly: true },
    { prop: 'emergency_protocol', label: '应急预案', type: 'textarea', group: 'compliance' },
    { prop: 'remark', label: '备注', type: 'textarea', group: 'remark' }
  ],
  special_device: [
    { prop: 'device_id', label: '关联设备', linkTable: 'medical_device', list: true, group: 'basic', required: true },
    { prop: 'device_code', label: '设备编码', list: true, group: 'basic', readonly: true },
    { prop: 'device_name', label: '设备名称', list: true, group: 'basic', readonly: true },
    { prop: 'dept_name', label: '所属科室', list: true, group: 'basic', readonly: true },
    { prop: 'special_type', label: '特种类型', dictType: 'special_type', list: true, group: 'basic' },
    { prop: 'license_no', label: '许可证号', list: true, group: 'compliance' },
    { prop: 'license_expiry_date', label: '许可证到期', type: 'date', list: true, group: 'compliance' },
    { prop: 'operator_cert_required', label: '需操作证', type: 'boolean', group: 'compliance' },
    { prop: 'safety_measures', label: '安全措施', type: 'textarea', group: 'compliance' },
    { prop: 'last_inspection_date', label: '上次检验', type: 'date', group: 'compliance' },
    { prop: 'next_inspection_date', label: '下次检验', type: 'date', list: true, group: 'compliance' },
    { prop: 'remark', label: '备注', type: 'textarea', group: 'remark' }
  ],
  emergency_device_pool: [
    { prop: 'pool_name', label: '库名称', list: true, required: true, group: 'basic' },
    { prop: 'campus_id', label: '院区', linkTable: 'campus', list: true, group: 'basic' },
    { prop: 'campus_name', label: '院区', list: true, group: 'basic', readonly: true },
    { prop: 'location', label: '位置', list: true, group: 'basic' },
    { prop: 'manager_id', label: '负责人', linkTable: 'sys_user', group: 'basic' },
    { prop: 'manager_name', label: '负责人', list: true, group: 'basic', readonly: true },
    { prop: 'contact_phone', label: '联系电话', list: true, group: 'basic' },
    { prop: 'is_available', label: '可用', type: 'boolean', list: true, group: 'status' },
    { prop: 'remark', label: '备注', type: 'textarea', group: 'remark' }
  ],
  emergency_device_allocation: [
    { prop: 'allocation_no', label: '调配单号', list: true, group: 'basic', readonly: true },
    { prop: 'device_id', label: '设备', linkTable: 'medical_device', list: true, group: 'basic', required: true },
    { prop: 'device_code', label: '设备编码', list: true, group: 'basic', readonly: true },
    { prop: 'device_name', label: '设备名称', list: true, group: 'basic', readonly: true },
    { prop: 'from_pool_id', label: '来源库', linkTable: 'emergency_device_pool', group: 'basic', required: true },
    { prop: 'pool_name', label: '来源库', list: true, group: 'basic', readonly: true },
    { prop: 'to_dept_id', label: '调入科室', linkTable: 'department', group: 'basic', required: true },
    { prop: 'to_dept_name', label: '调入科室', list: true, group: 'basic', readonly: true },
    { prop: 'urgency_level', label: '紧急程度', dictType: 'urgency_level', list: true, group: 'workflow' },
    { prop: 'reason', label: '调配原因', type: 'textarea', group: 'workflow' },
    { prop: 'status', label: '状态', dictType: 'allocation_status', list: true, group: 'workflow', readonly: true },
    { prop: 'application_time', label: '申请时间', type: 'datetime', list: true, group: 'time', readonly: true },
    { prop: 'allocation_time', label: '调配时间', type: 'datetime', group: 'time', readonly: true },
    { prop: 'return_time', label: '归还时间', type: 'datetime', group: 'time', readonly: true },
    { prop: 'remark', label: '备注', type: 'textarea', group: 'remark' }
  ],
  leased_device: [
    { prop: 'device_id', label: '关联设备', linkTable: 'medical_device', list: true, group: 'basic' },
    { prop: 'device_code', label: '设备编码', list: true, group: 'basic' },
    { prop: 'device_name', label: '设备名称', list: true, group: 'basic' },
    { prop: 'dept_name', label: '使用科室', list: true, group: 'basic', readonly: true },
    { prop: 'lessor_id', label: '出租方', linkTable: 'supplier', group: 'basic' },
    { prop: 'lessor_name', label: '出租方', list: true, group: 'basic', readonly: true },
    { prop: 'contract_no', label: '合同编号', list: true, group: 'finance' },
    { prop: 'lease_start_date', label: '起租日', type: 'date', list: true, group: 'time' },
    { prop: 'lease_end_date', label: '到期日', type: 'date', list: true, group: 'time' },
    { prop: 'monthly_rent', label: '月租金', type: 'number', list: true, group: 'finance' },
    { prop: 'auto_renewal', label: '自动续租', type: 'boolean', group: 'finance' },
    { prop: 'renewal_notice_days', label: '提醒天数', type: 'number', group: 'finance' },
    { prop: 'status', label: '状态', dictType: 'lease_status', list: true, group: 'status' },
    { prop: 'remark', label: '备注', type: 'textarea', group: 'remark' }
  ],
  shared_device: [
    { prop: 'device_code', label: '设备编码', list: true, group: 'basic', readonly: true },
    { prop: 'device_name', label: '设备名称', list: true, group: 'basic', readonly: true },
    { prop: 'dept_name', label: '归属科室', list: true, group: 'basic', readonly: true },
    { prop: 'shared_loan_status', label: '借调状态', dictType: 'shared_loan_display_status', list: true, group: 'status', readonly: true },
    { prop: 'shared_fee_mode', label: '计费方式', dictType: 'shared_fee_mode', list: true, group: 'finance', required: true },
    { prop: 'shared_fee_time_unit', label: '计时单位', dictType: 'shared_fee_time_unit', group: 'finance' },
    { prop: 'shared_fee_unit_price', label: '单价(元)', type: 'number', list: true, group: 'finance', required: true },
    { prop: 'location_detail', label: '存放位置', list: true, group: 'basic' },
    { prop: 'is_shared_device', label: '公用设备', type: 'boolean', group: 'status', readonly: true }
  ],
  shared_device_loan: [
    { prop: 'loan_no', label: '借调单号', list: true, group: 'basic', readonly: true },
    { prop: 'device_id', label: '公用设备', linkTable: 'shared_medical_device', list: true, group: 'basic', required: true },
    { prop: 'device_code', label: '设备编码', list: true, group: 'basic', readonly: true },
    { prop: 'device_name', label: '设备名称', list: true, group: 'basic', readonly: true },
    { prop: 'from_dept_name', label: '出借科室', list: true, group: 'basic', readonly: true },
    { prop: 'to_dept_id', label: '借入科室', linkTable: 'department', list: true, group: 'basic', required: true },
    { prop: 'to_dept_name', label: '借入科室', list: true, group: 'basic', readonly: true },
    { prop: 'loan_start', label: '计划开始', type: 'date', list: true, group: 'time', required: true },
    { prop: 'loan_end', label: '计划结束', type: 'date', list: true, group: 'time', required: true },
    { prop: 'fee_mode', label: '计费方式(快照)', dictType: 'shared_fee_mode', list: true, group: 'finance', readonly: true },
    { prop: 'fee_time_unit', label: '计时单位(快照)', dictType: 'shared_fee_time_unit', group: 'finance', readonly: true },
    { prop: 'fee_unit_price', label: '单价(快照)', type: 'number', list: true, group: 'finance', readonly: true },
    { prop: 'billing_start_at', label: '计费开始', type: 'datetime', group: 'time', readonly: true },
    { prop: 'billing_end_at', label: '计费结束', type: 'datetime', group: 'time', readonly: true },
    { prop: 'reason', label: '借调原因', type: 'textarea', list: true, group: 'workflow' },
    { prop: 'status', label: '状态', dictType: 'loan_status', list: true, group: 'workflow', readonly: true },
    { prop: 'applicant_name', label: '申请人', list: true, group: 'workflow', readonly: true },
    { prop: 'loan_time', label: '借出时间', type: 'datetime', group: 'time', readonly: true },
    { prop: 'return_time', label: '归还时间', type: 'datetime', group: 'time', readonly: true },
    { prop: 'remark', label: '备注', type: 'textarea', group: 'remark' }
  ],
  shared_device_return: [
    { prop: 'return_no', label: '归还单号', list: true, group: 'basic', readonly: true },
    { prop: 'loan_id', label: '借调单', linkTable: 'shared_device_loan', group: 'basic', required: true },
    { prop: 'loan_no', label: '借调单号', list: true, group: 'basic', readonly: true },
    { prop: 'device_name', label: '设备名称', list: true, group: 'basic', readonly: true },
    { prop: 'return_date', label: '归还日期', type: 'date', list: true, group: 'time', required: true },
    { prop: 'condition_desc', label: '设备状况', type: 'textarea', list: true, group: 'workflow' },
    { prop: 'status', label: '状态', dictType: 'return_status', list: true, group: 'workflow', readonly: true },
    { prop: 'applicant_name', label: '申请人', list: true, group: 'workflow', readonly: true },
    { prop: 'remark', label: '备注', type: 'textarea', group: 'remark' }
  ],
  shared_device_fee: [
    { prop: 'fee_no', label: '收费单号', list: true, group: 'basic', readonly: true },
    { prop: 'loan_id', label: '借调单', linkTable: 'shared_device_loan', list: true, group: 'basic', required: true },
    { prop: 'loan_no', label: '借调单号', list: true, group: 'basic', readonly: true },
    { prop: 'device_name', label: '设备名称', list: true, group: 'basic', readonly: true },
    { prop: 'fee_amount', label: '收费金额', type: 'number', list: true, group: 'finance', required: true },
    { prop: 'fee_date', label: '收费日期', type: 'date', list: true, group: 'finance', required: true },
    { prop: 'paid_status', label: '收费状态', dictType: 'paid_status', list: true, group: 'finance' },
    { prop: 'remark', label: '备注', type: 'textarea', group: 'remark' }
  ],
  pm_type: [
    { prop: 'type_code', label: '类型编码', list: true, required: true },
    { prop: 'type_name', label: '类型名称', list: true, required: true },
    { prop: 'risk_level', label: '风险等级', dictType: 'pm_risk_level', list: true },
    { prop: 'sort_order', label: '排序', type: 'number', list: true },
    { prop: 'description', label: '说明', type: 'textarea' },
    { prop: 'is_active', label: '启用', type: 'boolean', list: true }
  ],
  pm_template_item: [
    { prop: 'item_code', label: '项目编码', list: true },
    { prop: 'item_name', label: '项目名称', list: true, required: true },
    { prop: 'item_content', label: '维护内容', type: 'textarea', list: true },
    { prop: 'standard_value', label: '标准值', list: true },
    { prop: 'check_method', label: '检查方法' },
    { prop: 'sort_order', label: '排序', type: 'number' },
    { prop: 'is_required', label: '必检', type: 'boolean', list: true }
  ],
  pm_template: [
    { prop: 'template_code', label: '模板编码', list: true, required: true },
    { prop: 'template_name', label: '模板名称', list: true, required: true },
    { prop: 'pm_type_id', label: 'PM类型', linkTable: 'pm_type', list: true },
    { prop: 'description', label: '说明', type: 'textarea' },
    { prop: 'estimated_duration', label: '预计工时(分)', type: 'number' },
    { prop: 'is_active', label: '启用', type: 'boolean', list: true }
  ],
  pm_plan: [
    { prop: 'plan_code', label: '计划编码', list: true },
    { prop: 'plan_name', label: '计划名称', list: true, required: true },
    { prop: 'template_id', label: 'PM模板', linkTable: 'pm_template', list: true },
    { prop: 'device_id', label: '设备', linkTable: 'medical_device', list: true },
    { prop: 'dept_id', label: '责任科室', linkTable: 'department' },
    { prop: 'cycle_type', label: '周期类型', dictType: 'cycle_type', list: true },
    { prop: 'cycle_value', label: '周期值', type: 'number' },
    { prop: 'cycle_days', label: '周期(天)', type: 'number', list: true },
    { prop: 'next_due_date', label: '下次维护', type: 'date', list: true },
    { prop: 'last_maintained_at', label: '上次维护', type: 'date' },
    { prop: 'approval_status', label: '审核状态', dictType: 'maintain_approval_status', list: true },
    { prop: 'status', label: '状态', dictType: 'maintain_plan_status', list: true }
  ],
  pm_execution: [
    { prop: 'execution_no', label: '执行单号', list: true, readonly: true },
    { prop: 'template_id', label: 'PM模板', linkTable: 'pm_template', list: true },
    { prop: 'planned_date', label: '计划日期', type: 'date', list: true },
    { prop: 'assigned_engineer_id', label: '指派工程师', linkTable: 'engineer', list: true },
    { prop: 'status', label: '状态', dictType: 'maintain_exec_status', list: true },
    { prop: 'remark', label: '备注', type: 'textarea' }
  ],
  pm_execution_item: [
    { prop: 'device_code', label: '设备编码', list: true, readonly: true },
    { prop: 'device_name', label: '设备名称', list: true, readonly: true },
    { prop: 'overall_result', label: '维护结果', dictType: 'maintain_result', list: true },
    { prop: 'status', label: '状态', dictType: 'maintain_exec_item_status', list: true }
  ],
  benefit_mapping: [
    { prop: 'device_id', label: '关联设备', linkTable: 'medical_device', list: true, required: true },
    { prop: 'device_code', label: '设备编码', list: true, readonly: true },
    { prop: 'device_name', label: '设备名称', list: true, readonly: true },
    { prop: 'his_item_code', label: 'HIS项目编码', list: true },
    { prop: 'his_item_name', label: 'HIS项目名称', list: true },
    { prop: 'pacs_modality', label: 'PACS模态', list: true },
    { prop: 'charge_code', label: '收费编码', list: true },
    { prop: 'charge_name', label: '收费名称', list: true },
    { prop: 'unit_price', label: '单价', type: 'number', list: true },
    { prop: 'is_active', label: '启用', type: 'boolean', list: true },
    { prop: 'remark', label: '备注', type: 'textarea' }
  ],
  device_usage_record: [
    { prop: 'device_id', label: '设备', linkTable: 'medical_device', list: true, required: true },
    { prop: 'device_code', label: '设备编码', list: true, readonly: true },
    { prop: 'device_name', label: '设备名称', list: true, readonly: true },
    { prop: 'usage_date', label: '使用日期', type: 'date', list: true, required: true },
    { prop: 'usage_hours', label: '使用机时', type: 'number', list: true },
    { prop: 'patient_count', label: '人次', type: 'number', list: true },
    { prop: 'examination_count', label: '检查次数', type: 'number' },
    { prop: 'revenue', label: '收入', type: 'number', list: true },
    { prop: 'data_source', label: '数据来源', dictType: 'benefit_data_source', list: true }
  ],
  device_cost_record: [
    { prop: 'device_id', label: '设备', linkTable: 'medical_device', list: true, required: true },
    { prop: 'device_code', label: '设备编码', list: true, readonly: true },
    { prop: 'device_name', label: '设备名称', list: true, readonly: true },
    { prop: 'cost_date', label: '成本日期', type: 'date', list: true, required: true },
    { prop: 'cost_type', label: '成本类型', dictType: 'cost_type', list: true, required: true },
    { prop: 'cost_amount', label: '金额', type: 'number', list: true, required: true },
    { prop: 'invoice_no', label: '发票号', list: true },
    { prop: 'description', label: '说明', type: 'textarea', list: true },
    { prop: 'data_source', label: '数据来源', dictType: 'benefit_data_source' }
  ],
  device_benefit_summary: [
    { prop: 'device_code', label: '设备编码', list: true, readonly: true },
    { prop: 'device_name', label: '设备名称', list: true, readonly: true },
    { prop: 'dept_name', label: '科室', list: true, readonly: true },
    { prop: 'summary_year', label: '年', type: 'number', list: true, readonly: true },
    { prop: 'summary_month', label: '月', type: 'number', list: true, readonly: true },
    { prop: 'total_revenue', label: '总收入', type: 'number', list: true, readonly: true },
    { prop: 'total_cost', label: '总成本', type: 'number', list: true, readonly: true },
    { prop: 'net_profit', label: '净利润', type: 'number', list: true, readonly: true },
    { prop: 'profit_rate', label: '利润率', type: 'number', list: true, readonly: true },
    { prop: 'usage_hours', label: '使用机时', type: 'number', list: true, readonly: true },
    { prop: 'utilization_rate', label: '利用率', type: 'number', list: true, readonly: true },
    { prop: 'benefit_level', label: '效益等级', dictType: 'benefit_level', list: true, readonly: true },
    { prop: 'benefit_score', label: '效益评分', type: 'number', list: true, readonly: true }
  ],
  power_base_station: [
    { prop: 'station_code', label: '基站编码', list: true, required: true },
    { prop: 'station_name', label: '基站名称', list: true, required: true },
    { prop: 'campus_id', label: '院区', linkTable: 'campus', list: true },
    { prop: 'location', label: '安装位置', list: true },
    { prop: 'ip_address', label: 'IP地址', list: true },
    { prop: 'protocol_type', label: '协议类型', dictType: 'power_protocol_type', list: true },
    { prop: 'status', label: '状态', dictType: 'power_station_status', list: true },
    { prop: 'is_active', label: '启用', type: 'boolean', list: true },
    { prop: 'remark', label: '备注', type: 'textarea' }
  ],
  power_tag: [
    { prop: 'tag_code', label: '标签编码', list: true, required: true },
    { prop: 'tag_name', label: '标签名称', list: true, required: true, group: 'basic' },
    { prop: 'device_code', label: '设备编码', list: true, readonly: true },
    { prop: 'device_name', label: '设备名称', list: true, readonly: true },
    { prop: 'specification', label: '规格', list: true, readonly: true },
    { prop: 'model', label: '型号', list: true, readonly: true },
    { prop: 'serial_number', label: '序列号', list: true, readonly: true },
    { prop: 'manufacturer_name', label: '生产厂家', list: true, readonly: true },
    { prop: 'dept_name', label: '所属科室', list: true, readonly: true },
    { prop: 'device_id', label: '关联设备', widget: 'devicePicker', linkTable: 'medical_device' },
    { prop: 'station_name', label: '所属基站', list: true, readonly: true },
    { prop: 'station_id', label: '所属基站', widget: 'stationPicker', linkTable: 'power_base_station' },
    { prop: 'standby_current_max_ma', label: '电流上限(mA)', type: 'number', list: true, readonly: true },
    { prop: 'standby_current_min_ma', label: '电流下限(mA)', type: 'number', list: true, readonly: true },
    { prop: 'rated_power', label: '额定功率(W)', type: 'number', list: true },
    { prop: 'install_date', label: '安装日期', type: 'date', list: true },
    { prop: 'is_active', label: '启用', type: 'boolean', list: true },
    { prop: 'remark', label: '备注', type: 'textarea' }
  ],
  power_device_status: [
    { prop: 'device_code', label: '设备编码', list: true, readonly: true },
    { prop: 'device_name', label: '设备名称', list: true, readonly: true },
    { prop: 'current_amp', label: '电流(A)', type: 'number', list: true, readonly: true },
    { prop: 'voltage', label: '电压(V)', type: 'number', list: true, readonly: true },
    { prop: 'power_watt', label: '功率(W)', type: 'number', list: true, readonly: true },
    { prop: 'work_state', label: '运行状态', dictType: 'power_work_state', list: true, readonly: true },
    { prop: 'collected_at', label: '采集时间', list: true, readonly: true }
  ],
  power_monitor_record: [
    { prop: 'record_date', label: '日期', type: 'date', list: true, readonly: true },
    { prop: 'device_code', label: '设备编码', list: true, readonly: true },
    { prop: 'device_name', label: '设备名称', list: true, readonly: true },
    { prop: 'run_hours', label: '运行时长(h)', type: 'number', list: true, readonly: true },
    { prop: 'idle_hours', label: '待机时长(h)', type: 'number', list: true, readonly: true },
    { prop: 'offline_hours', label: '离线时长(h)', type: 'number', list: true, readonly: true },
    { prop: 'avg_current', label: '平均电流', type: 'number', list: true, readonly: true },
    { prop: 'peak_current', label: '峰值电流', type: 'number', list: true, readonly: true },
    { prop: 'energy_kwh', label: '用电量(kWh)', type: 'number', list: true, readonly: true }
  ]
}
