import type { FieldSchema } from './pageSchemas'

/** 第一期核心业务完整字段 schema */
export const businessSchemas: Record<string, FieldSchema[]> = {
  purchase_plan: [
    { prop: 'plan_code', label: '计划编号', list: true, group: 'basic', required: true },
    { prop: 'business_chain_no', label: '业务链编号', list: true, group: 'basic', readonly: true },
    { prop: 'plan_year', label: '计划年度', type: 'number', list: true, group: 'basic', required: true },
    { prop: 'plan_type', label: '计划类型', dictType: 'plan_type', group: 'basic' },
    { prop: 'fund_source', label: '资金来源', dictType: 'fund_source', group: 'finance' },
    { prop: 'dept_id', label: '申报科室', linkTable: 'department', group: 'basic' },
    { prop: 'dept_name', label: '申报科室', list: true, group: 'basic', readonly: true },
    { prop: 'applicant_id', label: '申报人', linkTable: 'sys_user', group: 'basic' },
    { prop: 'applicant_name', label: '申报人', list: true, group: 'basic', readonly: true },
    { prop: 'total_budget', label: '预算总额', type: 'number', list: true, group: 'finance', readonly: true },
    { prop: 'approval_status', label: '审批状态', dictType: 'approval_status', list: true, group: 'approval', readonly: true },
    { prop: 'approved_by', label: '审批人', linkTable: 'sys_user', group: 'approval', readonly: true },
    { prop: 'approved_at', label: '审批时间', type: 'datetime', group: 'approval', readonly: true },
    { prop: 'justification', label: '论证说明', type: 'textarea', group: 'remark' },
    { prop: 'is_large_equipment', label: '大型设备', type: 'boolean', group: 'compliance' },
    { prop: 'large_equipment_class', label: '大型设备分类', dictType: 'large_equipment_class', group: 'compliance' },
    { prop: 'benefit_analysis_url', label: '效益分析', type: 'file', group: 'attachment' },
    { prop: 'dept_argument_url', label: '科室论证纪要', type: 'file', group: 'attachment' },
    { prop: 'remark', label: '备注', type: 'textarea', group: 'remark' },
    { prop: 'is_active', label: '启用', type: 'boolean', group: 'other' }
  ],
  purchase_plan_item: [
    { prop: 'device_name', label: '设备名称', list: true, detail: true, required: true },
    { prop: 'category_id', label: '设备分类', linkTable: 'medical_device_category', detail: true },
    { prop: 'use_dept_id', label: '使用科室', linkTable: 'department', detail: true },
    { prop: 'quantity', label: '数量', type: 'number', list: true, detail: true, required: true },
    { prop: 'unit', label: '单位', detail: true },
    { prop: 'estimated_price', label: '预估单价', type: 'number', list: true, detail: true },
    { prop: 'total_price', label: '金额小计', type: 'number', list: true, detail: true },
    { prop: 'specification', label: '规格型号', type: 'textarea', detail: true },
    { prop: 'is_imported', label: '进口设备', type: 'boolean', detail: true },
    { prop: 'registration_no', label: '注册证号', detail: true },
    { prop: 'brand_intent', label: '意向品牌', detail: true },
    { prop: 'is_metrology', label: '需计量', type: 'boolean', detail: true },
    { prop: 'udi_code', label: 'UDI编码', detail: true },
    { prop: 'priority', label: '优先级', type: 'number', detail: true },
    { prop: 'justification', label: '购置理由', type: 'textarea', detail: true }
  ],
  purchase_project: [
    { prop: 'project_code', label: '项目编号', list: true, group: 'basic', required: true },
    { prop: 'business_chain_no', label: '业务链编号', list: true, group: 'basic', readonly: true },
    { prop: 'project_name', label: '项目名称', list: true, group: 'basic', required: true },
    { prop: 'plan_id', label: '关联计划', linkTable: 'purchase_plan', group: 'basic' },
    { prop: 'plan_code', label: '计划编号', list: true, group: 'basic', readonly: true },
    { prop: 'purchase_method', label: '采购方式', dictType: 'purchase_method', list: true, group: 'basic' },
    { prop: 'supplier_id', label: '中标供应商', linkTable: 'supplier', group: 'basic' },
    { prop: 'supplier_name', label: '中标供应商', list: true, group: 'basic', readonly: true },
    { prop: 'total_amount', label: '项目金额', type: 'number', list: true, group: 'finance' },
    { prop: 'budget_amount', label: '预算金额', type: 'number', group: 'finance' },
    { prop: 'bid_open_date', label: '开标日期', type: 'date', list: true, group: 'workflow' },
    { prop: 'award_date', label: '定标日期', type: 'date', group: 'workflow' },
    { prop: 'bid_agency', label: '招标代理机构', group: 'workflow' },
    { prop: 'notice_date', label: '公告日期', type: 'date', group: 'workflow' },
    { prop: 'control_price', label: '招标控制价', type: 'number', group: 'finance' },
    { prop: 'approval_status', label: '审批状态', dictType: 'approval_status', list: true, group: 'workflow', readonly: true },
    { prop: 'status', label: '状态', dictType: 'project_status', list: true, group: 'workflow' },
    { prop: 'bid_sections', label: '招标标段', type: 'textarea', group: 'workflow' },
    { prop: 'bid_evaluation', label: '评标结果', type: 'textarea', group: 'workflow' },
    { prop: 'argument_report_url', label: '论证报告', type: 'file', group: 'attachment' }
  ],
  purchase_contract: [
    { prop: 'contract_code', label: '合同编号', list: true, group: 'basic', required: true },
    { prop: 'business_chain_no', label: '业务链编号', list: true, group: 'basic', readonly: true },
    { prop: 'contract_name', label: '合同名称', list: true, group: 'basic', required: true },
    { prop: 'project_id', label: '采购项目', linkTable: 'purchase_project', group: 'basic' },
    { prop: 'project_name', label: '采购项目', list: true, group: 'basic', readonly: true },
    { prop: 'supplier_id', label: '供应商', linkTable: 'supplier', group: 'basic' },
    { prop: 'supplier_name', label: '供应商', list: true, group: 'basic', readonly: true },
    { prop: 'sign_date', label: '签订日期', type: 'date', list: true, group: 'basic' },
    { prop: 'start_date', label: '开始日期', type: 'date', group: 'basic' },
    { prop: 'end_date', label: '结束日期', type: 'date', group: 'basic' },
    { prop: 'delivery_deadline', label: '交货期限', type: 'date', group: 'basic' },
    { prop: 'contract_amount', label: '合同金额', type: 'number', list: true, group: 'finance' },
    { prop: 'contract_type', label: '合同类型', dictType: 'contract_type', group: 'basic' },
    { prop: 'performance_bond', label: '履约保证金', type: 'number', group: 'finance' },
    { prop: 'registration_cert_url', label: '注册证附件', type: 'file', group: 'attachment' },
    { prop: 'paid_amount', label: '已付金额', type: 'number', list: true, group: 'finance', readonly: true },
    { prop: 'payment_progress', label: '付款进度%', type: 'number', list: true, group: 'finance', readonly: true },
    { prop: 'warranty_period', label: '质保期(月)', type: 'number', group: 'finance' },
    { prop: 'payment_terms', label: '付款条款', type: 'textarea', group: 'finance' },
    { prop: 'contract_file_url', label: '合同附件', type: 'file', group: 'attachment' },
    { prop: 'acceptance_status', label: '安装验收', dictType: 'acceptance_status', list: true, group: 'workflow' },
    { prop: 'acceptance_report_url', label: '验收报告', type: 'file', group: 'attachment' },
    { prop: 'invoice_summary', label: '发票汇总', type: 'textarea', group: 'finance' },
    { prop: 'approval_status', label: '审批状态', dictType: 'approval_status', list: true, group: 'approval', readonly: true },
    { prop: 'status', label: '合同状态', dictType: 'contract_status', list: true, group: 'workflow' },
    { prop: 'remark', label: '备注', type: 'textarea', group: 'remark' }
  ],
  contract_payment: [
    { prop: 'payment_no', label: '付款单号', list: true, detail: true, required: true },
    { prop: 'payment_stage', label: '付款阶段', dictType: 'payment_stage', list: true, detail: true },
    { prop: 'payment_amount', label: '付款金额', type: 'number', list: true, detail: true },
    { prop: 'payment_date', label: '付款日期', type: 'date', detail: true },
    { prop: 'invoice_no', label: '发票号', list: true, detail: true },
    { prop: 'invoice_type', label: '发票类型', dictType: 'invoice_type', detail: true },
    { prop: 'tax_amount', label: '税额', type: 'number', detail: true },
    { prop: 'voucher_no', label: '财务凭证号', detail: true },
    { prop: 'invoice_url', label: '发票附件', type: 'file', detail: true },
    { prop: 'payee_account', label: '收款账户', detail: true },
    { prop: 'status', label: '状态', dictType: 'payment_status', list: true, detail: true },
    { prop: 'approval_status', label: '审批状态', dictType: 'approval_status', list: true, detail: true, readonly: true },
    { prop: 'remark', label: '备注', type: 'textarea', detail: true }
  ],
  purchase_acceptance: [
    { prop: 'acceptance_no', label: '验收单号', list: true, group: 'basic', readonly: true },
    { prop: 'business_chain_no', label: '业务链编号', list: true, group: 'basic', readonly: true },
    { prop: 'contract_id', label: '采购合同', linkTable: 'purchase_contract', group: 'basic', readonly: true },
    { prop: 'contract_code', label: '合同编号', list: true, group: 'basic', readonly: true },
    { prop: 'supplier_name', label: '供应商', list: true, group: 'basic', readonly: true },
    { prop: 'acceptance_date', label: '验收日期', type: 'date', list: true, group: 'workflow' },
    { prop: 'acceptance_status', label: '验收状态', dictType: 'acceptance_status', list: true, group: 'workflow' },
    { prop: 'approval_status', label: '审批状态', dictType: 'approval_status', list: true, group: 'workflow', readonly: true },
    { prop: 'quality_check_passed', label: '质检通过', type: 'boolean', group: 'workflow' },
    { prop: 'quality_checker_id', label: '质检人', linkTable: 'sys_user', group: 'workflow' },
    { prop: 'quality_check_date', label: '质检日期', type: 'date', group: 'workflow' },
    { prop: 'quality_check_report_url', label: '质检报告', type: 'file', group: 'attachment' },
    { prop: 'installation_completed', label: '安装完成', type: 'boolean', group: 'workflow' },
    { prop: 'installer_id', label: '安装人', linkTable: 'sys_user', group: 'workflow' },
    { prop: 'installation_date', label: '安装日期', type: 'date', group: 'workflow' },
    { prop: 'installation_report_url', label: '安装报告', type: 'file', group: 'attachment' },
    { prop: 'clinical_checker_id', label: '临床验收人', linkTable: 'sys_user', group: 'workflow' },
    { prop: 'argument_summary', label: '论证摘要', type: 'textarea', group: 'remark' },
    { prop: 'report_url', label: '验收报告', type: 'file', group: 'attachment' },
    { prop: 'remark', label: '备注', type: 'textarea', group: 'remark' }
  ],
  supplier: [
    { prop: 'supplier_code', label: '供应商编码', list: true, required: true },
    { prop: 'supplier_name', label: '供应商名称', list: true, required: true },
    { prop: 'pinyin_code', label: '拼音简码', list: true },
    { prop: 'unified_social_credit_code', label: '统一社会信用代码', list: true },
    { prop: 'legal_representative', label: '法人代表' },
    { prop: 'contact_person', label: '联系人', list: true },
    { prop: 'contact_phone', label: '联系电话', list: true },
    { prop: 'address', label: '地址', type: 'textarea' },
    { prop: 'bank_name', label: '开户行' },
    { prop: 'bank_account', label: '银行账号' },
    { prop: 'rating', label: '评级', type: 'number', list: true },
    { prop: 'is_authorized', label: '授权经销商', type: 'boolean', list: true },
    { prop: 'is_active', label: '启用', type: 'boolean', list: true }
  ],
  manufacturer: [
    { prop: 'manufacturer_code', label: '厂商编码', list: true, required: true },
    { prop: 'manufacturer_name', label: '厂商名称', list: true, required: true },
    { prop: 'pinyin_code', label: '拼音简码', list: true },
    { prop: 'country', label: '国家/地区', list: true },
    { prop: 'is_domestic', label: '国产厂商', type: 'boolean', list: true },
    { prop: 'contact_phone', label: '联系电话', list: true },
    { prop: 'website', label: '官网' },
    { prop: 'is_active', label: '启用', type: 'boolean', list: true }
  ],
  medical_device_category: [
    { prop: 'category_code', label: '分类编码(68码)', list: true, required: true },
    { prop: 'category_name', label: '分类名称', list: true, required: true },
    { prop: 'parent_code', label: '上级编码', list: true },
    { prop: 'level', label: '层级', type: 'number', list: true },
    { prop: 'full_path', label: '完整路径' },
    { prop: 'sort_order', label: '排序', type: 'number', list: true },
    { prop: 'is_active', label: '启用', type: 'boolean', list: true }
  ],
  medical_device: [
    { prop: 'device_code', label: '设备编码', list: true, group: 'basic', required: true },
    { prop: 'device_name', label: '设备名称', list: true, group: 'basic', required: true },
    { prop: 'brand', label: '品牌', list: true, group: 'basic' },
    { prop: 'specification', label: '规格', list: true, group: 'basic' },
    { prop: 'model', label: '型号', list: true, group: 'basic' },
    { prop: 'registration_no', label: '注册证号', group: 'basic' },
    { prop: 'serial_number', label: '序列号', group: 'basic' },
    { prop: 'category_id', label: '设备分类', linkTable: 'medical_device_category', group: 'basic' },
    { prop: 'manufacturer_id', label: '生产厂商', linkTable: 'manufacturer', group: 'basic' },
    { prop: 'supplier_id', label: '供应商', linkTable: 'supplier', group: 'basic' },
    { prop: 'country_of_origin', label: '原产国', group: 'basic' },
    { prop: 'is_imported', label: '进口设备', type: 'boolean', group: 'basic' },
    { prop: 'original_value', label: '原值', type: 'number', list: true, group: 'finance' },
    { prop: 'net_value', label: '净值', type: 'number', list: true, group: 'finance' },
    { prop: 'depreciation_years', label: '折旧年限', type: 'number', group: 'finance' },
    { prop: 'monthly_depreciation', label: '月折旧', type: 'number', group: 'finance' },
    { prop: 'accumulated_depreciation', label: '累计折旧', type: 'number', group: 'finance' },
    { prop: 'financial_code', label: '财务编码', group: 'finance' },
    { prop: 'campus_id', label: '院区', linkTable: 'campus', group: 'location' },
    { prop: 'building_id', label: '建筑物', linkTable: 'building', group: 'location' },
    { prop: 'dept_id', label: '领用科室', linkTable: 'department', list: true, group: 'location' },
    { prop: 'location_detail', label: '位置详情', group: 'location' },
    { prop: 'purchase_date', label: '购置日期', type: 'date', group: 'time' },
    { prop: 'acceptance_date', label: '验收日期', type: 'date', group: 'time' },
    { prop: 'enable_date', label: '启用日期', type: 'date', list: true, group: 'time' },
    { prop: 'production_date', label: '生产日期', type: 'date', group: 'time' },
    { prop: 'service_life_years', label: '使用年限', type: 'number', group: 'time' },
    { prop: 'service_expiry_date', label: '使用到期日期', type: 'date', group: 'time', readonly: true },
    { prop: 'calibration_period_days', label: '计量周期(天)', type: 'number', group: 'time' },
    { prop: 'last_calibration_date', label: '上次计量日期', type: 'date', group: 'time' },
    { prop: 'next_calibration_date', label: '下次计量日期', type: 'date', group: 'time', readonly: true },
    { prop: 'warranty_end_date', label: '保修截止', type: 'date', group: 'time' },
    { prop: 'device_status', label: '设备状态', dictType: 'device_status', list: true, group: 'status' },
    { prop: 'risk_level', label: '风险等级', dictType: 'risk_level', list: true, group: 'status' },
    { prop: 'is_life_support', label: '生命支持', type: 'boolean', group: 'status' },
    { prop: 'is_emergency', label: '应急设备', type: 'boolean', group: 'status' },
    { prop: 'qr_code_url', label: '二维码URL', group: 'attachment', readonly: true },
    { prop: 'label_printed', label: '已打标签', type: 'boolean', group: 'attachment' },
    { prop: 'remark', label: '备注', type: 'textarea', group: 'remark' },
    { prop: 'is_active', label: '启用', type: 'boolean', group: 'other' }
  ],
  device_entry: [
    { prop: 'entry_no', label: '入库单号', list: true, group: 'basic', readonly: true },
    { prop: 'trace_no', label: '业务追溯号', list: true, group: 'basic', readonly: true },
    { prop: 'business_chain_no', label: '业务链编号', list: true, group: 'basic', readonly: true },
    { prop: 'contract_id', label: '采购合同', linkTable: 'purchase_contract', group: 'basic' },
    { prop: 'contract_code', label: '合同编号', list: true, group: 'basic', readonly: true },
    { prop: 'supplier_name', label: '供应商', list: true, group: 'basic', readonly: true },
    { prop: 'entry_date', label: '入库日期', type: 'date', list: true, group: 'basic' },
    { prop: 'entry_type', label: '入库类型', dictType: 'entry_type', list: true, group: 'basic' },
    { prop: 'operator_id', label: '经办人', linkTable: 'sys_user', group: 'basic' },
    { prop: 'quality_check_passed', label: '质量验收', type: 'boolean', list: true, group: 'workflow' },
    { prop: 'quality_checker_id', label: '验收人', linkTable: 'sys_user', group: 'workflow' },
    { prop: 'quality_check_date', label: '验收日期', type: 'date', group: 'workflow' },
    { prop: 'quality_check_report_url', label: '验收报告', group: 'attachment' },
    { prop: 'installation_completed', label: '安装完成', type: 'boolean', group: 'workflow' },
    { prop: 'installation_date', label: '安装日期', type: 'date', group: 'workflow' },
    { prop: 'status', label: '状态', dictType: 'entry_status', list: true, group: 'workflow' },
    { prop: 'remark', label: '备注', type: 'textarea', group: 'remark' }
  ],
  device_entry_item: [
    { prop: 'device_name', label: '设备名称', list: true, detail: true, required: true },
    { prop: 'brand', label: '品牌', detail: true },
    { prop: 'model', label: '型号', detail: true },
    { prop: 'serial_number', label: '序列号', detail: true },
    { prop: 'quantity', label: '数量', type: 'number', detail: true },
    { prop: 'unit_price', label: '单价', type: 'number', detail: true },
    { prop: 'total_price', label: '金额', type: 'number', detail: true },
    { prop: 'is_accepted', label: '已验收', type: 'boolean', detail: true }
  ],
  device_outbound: [
    { prop: 'outbound_no', label: '出库单号', list: true, readonly: true },
    { prop: 'outbound_date', label: '出库日期', type: 'date', list: true },
    { prop: 'dept_id', label: '领用科室', linkTable: 'department', list: true },
    { prop: 'recipient_id', label: '领用人', linkTable: 'sys_user' },
    { prop: 'warehouse_id', label: '出库库房', linkTable: 'warehouse' },
    { prop: 'purpose', label: '用途', type: 'textarea' },
    { prop: 'doc_status', label: '审批状态', dictType: 'approval_status', list: true },
    { prop: 'status', label: '出库状态', dictType: 'outbound_status', list: true },
    { prop: 'remark', label: '备注', type: 'textarea' }
  ],
  device_outbound_item: [
    { prop: 'device_code', label: '设备编码', list: true, detail: true },
    { prop: 'device_name', label: '设备名称', list: true, detail: true },
    { prop: 'device_id', label: '设备', linkTable: 'medical_device', detail: true },
    { prop: 'quantity', label: '数量', type: 'number', detail: true }
  ],
  asset_transfer: [
    { prop: 'transfer_no', label: '流转单号', list: true, readonly: true },
    { prop: 'transfer_type', label: '流转类型', dictType: 'transfer_type', list: true },
    { prop: 'device_id', label: '设备', linkTable: 'medical_device', list: true },
    { prop: 'from_dept_id', label: '转出科室', linkTable: 'department', list: true },
    { prop: 'to_dept_id', label: '转入科室', linkTable: 'department', list: true },
    { prop: 'from_campus_id', label: '转出院区', linkTable: 'campus' },
    { prop: 'to_campus_id', label: '转入院区', linkTable: 'campus' },
    { prop: 'transfer_date', label: '流转日期', type: 'date', list: true },
    { prop: 'reason', label: '流转原因', type: 'textarea' },
    { prop: 'status', label: '状态', dictType: 'transfer_status', list: true },
    { prop: 'remark', label: '备注', type: 'textarea' }
  ],
  inventory_check: [
    { prop: 'check_no', label: '盘点单号', list: true, readonly: true },
    { prop: 'check_name', label: '盘点名称', list: true, required: true },
    { prop: 'check_year', label: '盘点年度', type: 'number', list: true },
    { prop: 'check_type', label: '盘点类型', dictType: 'check_type', list: true },
    { prop: 'campus_id', label: '院区', linkTable: 'campus', list: true },
    { prop: 'dept_id', label: '科室', linkTable: 'department', list: true },
    { prop: 'start_date', label: '计划开始', type: 'date', list: true },
    { prop: 'end_date', label: '计划结束', type: 'date' },
    { prop: 'checker_id', label: '盘点人', linkTable: 'sys_user' },
    { prop: 'supervisor_id', label: '监盘人', linkTable: 'sys_user' },
    { prop: 'created_by', label: '制单人', linkTable: 'sys_user', list: true, readonly: true },
    { prop: 'created_at', label: '制单时间', type: 'datetime', list: true, readonly: true },
    { prop: 'approved_by', label: '审核人', linkTable: 'sys_user', list: true, readonly: true },
    { prop: 'approved_at', label: '审核时间', type: 'datetime', list: true, readonly: true },
    { prop: 'audit_status', label: '审核状态', dictType: 'audit_status', list: true, readonly: true },
    { prop: 'total_count', label: '应盘数量', type: 'number', list: true, readonly: true },
    { prop: 'checked_count', label: '已盘数量', type: 'number', list: true, readonly: true },
    { prop: 'matched_count', label: '账实相符', type: 'number', list: true, readonly: true },
    { prop: 'mismatch_count', label: '差异数量', type: 'number', list: true, readonly: true },
    { prop: 'status', label: '状态', dictType: 'check_status', list: true },
    { prop: 'remark', label: '备注', type: 'textarea' }
  ],
  inventory_check_item: [
    { prop: 'device_code', label: '设备编码', list: true, detail: true, readonly: true },
    { prop: 'device_name', label: '设备名称', list: true, detail: true, readonly: true },
    { prop: 'expected_location', label: '账面位置', detail: true, readonly: true },
    { prop: 'actual_location', label: '实盘位置', detail: true },
    { prop: 'is_found', label: '是否找到', type: 'boolean', detail: true },
    { prop: 'is_matched', label: '账实相符', type: 'boolean', detail: true },
    { prop: 'condition_status', label: '设备状况', dictType: 'condition_status', detail: true },
    { prop: 'remark', label: '备注', type: 'textarea', detail: true }
  ],
  device_scrap: [
    { prop: 'scrap_no', label: '报废单号', list: true, readonly: true },
    { prop: 'device_id', label: '设备', linkTable: 'medical_device', list: true },
    { prop: 'device_code', label: '设备编码', list: true, readonly: true },
    { prop: 'device_name', label: '设备名称', list: true, readonly: true },
    { prop: 'scrap_reason', label: '报废原因', type: 'textarea', list: true, required: true },
    { prop: 'scrap_type', label: '报废类型', dictType: 'scrap_type', list: true },
    { prop: 'application_date', label: '申请日期', type: 'date', list: true },
    { prop: 'evaluator_id', label: '评估人', linkTable: 'sys_user' },
    { prop: 'evaluation_result', label: '评估结论', type: 'textarea' },
    { prop: 'residual_value', label: '残值', type: 'number' },
    { prop: 'disposal_method', label: '处置方式', dictType: 'disposal_method' },
    { prop: 'disposal_date', label: '处置日期', type: 'date' },
    { prop: 'status', label: '状态', dictType: 'scrap_status', list: true },
    { prop: 'remark', label: '备注', type: 'textarea' }
  ],
  inspection_plan: [
    { prop: 'plan_code', label: '计划编号', list: true },
    { prop: 'plan_name', label: '计划名称', list: true, required: true },
    { prop: 'plan_type', label: '巡检类型', dictType: 'inspection_type', list: true },
    { prop: 'dept_id', label: '责任科室', linkTable: 'department', list: true },
    { prop: 'start_date', label: '开始日期', type: 'date', list: true },
    { prop: 'end_date', label: '结束日期', type: 'date' },
    { prop: 'frequency', label: '频次', dictType: 'inspection_frequency' },
    { prop: 'status', label: '状态', dictType: 'plan_status', list: true }
  ],
  inspection_record: [
    { prop: 'record_no', label: '记录编号', list: true },
    { prop: 'plan_id', label: '巡检计划', list: true },
    { prop: 'inspector_id', label: '巡检人', linkTable: 'sys_user', list: true },
    { prop: 'inspect_date', label: '巡检日期', type: 'date', list: true },
    { prop: 'result_summary', label: '巡检结果', type: 'textarea', list: true },
    { prop: 'status', label: '状态', dictType: 'inspection_status', list: true }
  ],
  repair_workorder: [
    { prop: 'wo_no', label: '工单号', list: true, group: 'basic', readonly: true },
    { prop: 'device_id', label: '设备', widget: 'repairDevicePicker', list: true, group: 'basic' },
    { prop: 'device_code', label: '设备编码', list: true, group: 'basic', readonly: true },
    { prop: 'device_name', label: '设备名称', list: true, group: 'basic', readonly: true },
    { prop: 'reporter_id', label: '报修人', linkTable: 'sys_user', group: 'basic' },
    { prop: 'report_dept_id', label: '报修科室', linkTable: 'department', group: 'basic', readonly: true },
    { prop: 'report_method', label: '报修渠道', dictType: 'report_method', group: 'basic' },
    { prop: 'report_time', label: '报修时间', type: 'datetime', list: true, group: 'basic' },
    { prop: 'fault_description', label: '故障描述', type: 'textarea', list: true, group: 'basic', required: true },
    { prop: 'urgency_level', label: '紧急程度', dictType: 'urgency', list: true, group: 'basic' },
    { prop: 'fault_type_id', label: '故障类型', group: 'basic' },
    { prop: 'assigned_engineer_id', label: '工程师', linkTable: 'engineer', list: true, group: 'workflow' },
    { prop: 'assigned_at', label: '派工时间', type: 'datetime', group: 'workflow' },
    { prop: 'response_time', label: '响应时间', type: 'datetime', group: 'workflow' },
    { prop: 'arrival_time', label: '到场时间', type: 'datetime', group: 'workflow' },
    { prop: 'repair_start_time', label: '维修开始', type: 'datetime', group: 'workflow' },
    { prop: 'repair_end_time', label: '维修结束', type: 'datetime', group: 'workflow' },
    { prop: 'repair_duration_hours', label: '维修工时', type: 'number', group: 'workflow' },
    { prop: 'solution_description', label: '处理方案', type: 'textarea', group: 'workflow' },
    { prop: 'labor_cost', label: '人工费', type: 'number', group: 'finance' },
    { prop: 'parts_cost', label: '备件费', type: 'number', group: 'finance' },
    { prop: 'total_cost', label: '总费用', type: 'number', list: true, group: 'finance' },
    { prop: 'invoice_no', label: '发票号', group: 'finance' },
    { prop: 'verify_result', label: '验收结果', dictType: 'verify_result', group: 'workflow' },
    { prop: 'verify_comment', label: '验收意见', type: 'textarea', group: 'workflow' },
    { prop: 'satisfaction_rating', label: '满意度', type: 'number', group: 'workflow' },
    { prop: 'status', label: '状态', dictType: 'wo_status', list: true, group: 'workflow', readonly: true },
    { prop: 'remark', label: '备注', type: 'textarea', group: 'remark' }
  ],
  engineer: [
    { prop: 'engineer_no', label: '工号', list: true, required: true },
    { prop: 'real_name', label: '姓名', list: true, required: true },
    { prop: 'user_id', label: '关联用户', linkTable: 'sys_user' },
    { prop: 'specialty', label: '专业方向', list: true },
    { prop: 'phone', label: '电话', list: true },
    { prop: 'email', label: '邮箱' },
    { prop: 'is_on_duty', label: '在岗', type: 'boolean', list: true },
    { prop: 'workload_score', label: '工作量', type: 'number', list: true, readonly: true }
  ],
  spare_part: [
    { prop: 'part_code', label: '备件编码', list: true, required: true },
    { prop: 'part_name', label: '备件名称', list: true, required: true },
    { prop: 'category', label: '分类', list: true },
    { prop: 'specification', label: '规格', type: 'textarea' },
    { prop: 'supplier_id', label: '供应商', linkTable: 'supplier' },
    { prop: 'unit_price', label: '单价', type: 'number', list: true },
    { prop: 'stock_quantity', label: '库存', type: 'number', list: true },
    { prop: 'min_stock', label: '最低库存', type: 'number', list: true },
    { prop: 'warehouse_id', label: '库房', linkTable: 'warehouse' },
    { prop: 'is_active', label: '启用', type: 'boolean', list: true }
  ],
  fault_type_dict: [
    { prop: 'fault_code', label: '故障编码', list: true, required: true },
    { prop: 'fault_name', label: '故障名称', list: true, required: true },
    { prop: 'level', label: '层级', type: 'number', list: true },
    { prop: 'is_active', label: '启用', type: 'boolean', list: true }
  ],
  maintenance_template: [
    { prop: 'template_code', label: '模板编码', list: true, required: true },
    { prop: 'template_name', label: '模板名称', list: true, required: true },
    { prop: 'maintenance_level', label: '保养级别', dictType: 'maintenance_level', list: true },
    { prop: 'check_items', label: '保养项目', type: 'textarea' },
    { prop: 'estimated_duration', label: '预计工时', type: 'number' },
    { prop: 'is_active', label: '启用', type: 'boolean', list: true }
  ],
  maintenance_plan: [
    { prop: 'plan_code', label: '计划编码', list: true },
    { prop: 'plan_name', label: '计划名称', list: true, required: true },
    { prop: 'template_id', label: '保养模板', linkTable: 'maintenance_template', list: true },
    { prop: 'device_id', label: '设备', linkTable: 'medical_device', list: true },
    { prop: 'dept_id', label: '责任科室', linkTable: 'department' },
    { prop: 'cycle_type', label: '周期类型', dictType: 'cycle_type', list: true },
    { prop: 'cycle_value', label: '周期值', type: 'number' },
    { prop: 'next_due_date', label: '下次保养', type: 'date', list: true },
    { prop: 'last_maintained_at', label: '上次保养', type: 'date' },
    { prop: 'status', label: '状态', dictType: 'maintain_plan_status', list: true }
  ],
  maintenance_record: [
    { prop: 'record_no', label: '记录编号', list: true, readonly: true },
    { prop: 'plan_id', label: '保养计划', list: true },
    { prop: 'device_id', label: '设备', linkTable: 'medical_device', list: true },
    { prop: 'maintainer_id', label: '保养人', linkTable: 'sys_user', list: true },
    { prop: 'maintained_at', label: '保养时间', type: 'datetime', list: true },
    { prop: 'maintenance_level', label: '保养级别', dictType: 'maintenance_level', list: true },
    { prop: 'result', label: '保养结果', dictType: 'maintain_result', list: true },
    { prop: 'findings', label: '发现问题', type: 'textarea' },
    { prop: 'actions_taken', label: '处理措施', type: 'textarea' },
    { prop: 'status', label: '状态', dictType: 'maintain_record_status', list: true }
  ]
}
