/** 设备台账等详情页字段中文标签 */
export const deviceFieldLabels: Record<string, string> = {
  id: 'ID',
  device_code: '设备编码',
  device_name: '设备名称',
  brand: '品牌',
  model: '型号',
  serial_number: '序列号',
  category_id: '设备分类',
  manufacturer_id: '生产厂商',
  supplier_id: '供应商',
  country_of_origin: '原产国',
  is_imported: '是否进口',
  original_value: '原值',
  net_value: '净值',
  depreciation_years: '折旧年限',
  monthly_depreciation: '月折旧',
  accumulated_depreciation: '累计折旧',
  financial_code: '财务编码',
  campus_id: '院区',
  building_id: '建筑物',
  dept_id: '使用科室',
  location_detail: '位置详情',
  purchase_date: '购置日期',
  acceptance_date: '验收日期',
  enable_date: '启用日期',
  warranty_end_date: '保修截止',
  device_status: '设备状态',
  risk_level: '风险等级',
  is_life_support: '生命支持',
  is_emergency: '应急设备',
  qr_code_url: '二维码',
  label_printed: '已打标签',
  remark: '备注',
  is_active: '启用',
  created_at: '创建时间',
  updated_at: '更新时间'
}

export const groupTitles: Record<string, string> = {
  basic: '基本信息',
  finance: '财务信息',
  location: '位置信息',
  time: '时间信息',
  status: '状态信息',
  attachment: '附件',
  remark: '备注',
  other: '其他'
}

export const deviceFieldGroups: Record<string, string> = {
  device_code: 'basic',
  device_name: 'basic',
  brand: 'basic',
  model: 'basic',
  serial_number: 'basic',
  category_id: 'basic',
  manufacturer_id: 'basic',
  supplier_id: 'basic',
  country_of_origin: 'basic',
  is_imported: 'basic',
  original_value: 'finance',
  net_value: 'finance',
  depreciation_years: 'finance',
  monthly_depreciation: 'finance',
  accumulated_depreciation: 'finance',
  financial_code: 'finance',
  campus_id: 'location',
  building_id: 'location',
  dept_id: 'location',
  location_detail: 'location',
  purchase_date: 'time',
  acceptance_date: 'time',
  enable_date: 'time',
  warranty_end_date: 'time',
  device_status: 'status',
  risk_level: 'status',
  is_life_support: 'status',
  is_emergency: 'status',
  qr_code_url: 'attachment',
  label_printed: 'attachment',
  remark: 'remark'
}
